In [15]:
import pymongo,json
import sys
import pandas as pd

In [16]:
def mongoConnect():    
    try:
      client = pymongo.MongoClient("mongodb+srv://jcomeaux:444Jayla.@cluster0.qjm0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
      
    # return a friendly error if a URI error is thrown 
    except pymongo.errors.ConfigurationError:
      print("An Invalid URI host error was received. Is your Atlas host name correct in your connection string?")
      sys.exit(1)
        
    return client

client = mongoConnect()
db = client["Fire"]      # replace with your database name
collection = db["VPD"] # replace with your collection name

# Read all records
# records = collection.find()
# for record in records:
#     print(record)
# print("DONE")

recs = list(collection.find())
df = pd.DataFrame(recs)
print(df)

                          _id  statefule  batch_size  forecast_period  \
0    67c3ec8f9f8c93b67411ab93      False          48                8
1    67c3ec9b9f8c93b67411ab94      False          48                8
2    67c3eca89f8c93b67411ab95      False          48                8
3    67c3ecb49f8c93b67411ab96      False          48                8
4    67c3ecc19f8c93b67411ab97      False          48                8
..                        ...        ...         ...              ...
255  67d64b3a25f5eb0e62c59b09       True          56                8
256  67d64b5b25f5eb0e62c59b0a       True          56                8
257  67d64b7c25f5eb0e62c59b0b       True          56                8
258  67d64b9f25f5eb0e62c59b0c       True          56                8
259  67d64bc025f5eb0e62c59b0d       True          56                8

     features  timesteps  shuffle  TotalLength  learningRate  \
0           6         24    False          420         0.002
1           6         24    False          420         0.002
2           6         24    False          420         0.002
3           6         24    False          420         0.002
4           6         24    False          420         0.002
..        ...        ...      ...          ...           ...
255         6         24    False          420         0.002
256         6         24    False          420         0.002
257         6         24    False          420         0.002
258         6         24    False          420         0.002
259         6         24    False          420         0.002

                                               history  earlyStoppingLength  \
0    {'loss': [0.0891372486948967, 0.07234407961368...                  100
1    {'loss': [0.017181525006890297, 0.023382451385...                  100
2    {'loss': [0.009490793570876122, 0.015723206102...                  100
3    {'loss': [0.011466928757727146, 0.010548892430...                  100
4    {'loss': [0.00421214010566473, 0.0083453562110...                  100
..                                                 ...                  ...
255  {'loss': [0.004548251628875732, 0.012068430893...                   15
256  {'loss': [0.0065688216127455235, 0.01446945313...                   15
257  {'loss': [0.00833149440586567, 0.0129899317398...                   15
258  {'loss': [0.0038470446597784758, 0.01316633261...                   15
259  {'loss': [0.008571578189730644, 0.015251549892...                   15

     epochBest  changeWeights                    date  testError  trainError  \
0          100           True 2025-03-01 22:28:35.329   0.406009    0.224982
1          100           True 2025-03-01 22:28:35.329   0.364325    0.104216
2          100           True 2025-03-01 22:28:35.329   0.383692    0.115948
3          100           True 2025-03-01 22:28:35.329   0.410618    0.070342
4          100           True 2025-03-01 22:28:35.329   0.399200    0.071963
..         ...            ...                     ...        ...         ...
255        150          False 2025-03-15 21:50:12.836   0.351707    0.157996
256        150          False 2025-03-15 21:50:12.836   0.472254    0.195647
257        150          False 2025-03-15 21:50:12.836   0.424418    0.164424
258        150          False 2025-03-15 21:50:12.836   0.413376    0.189860
259        150          False 2025-03-15 21:50:12.836   0.357271    0.203319

                                                y_test  \
0    [0.41543625000000034, 0.25733643724696353, 0.1...
1    [0.41543625000000034, 0.25733643724696353, 0.1...
2    [0.41543625000000034, 0.25733643724696353, 0.1...
3    [0.41543625000000034, 0.25733643724696353, 0.1...
4    [0.41543625000000034, 0.25733643724696353, 0.1...
..                                                 ...
255  [0.41543625000000034, 0.25733643724696353, 0.1...
256  [0.41543625000000034, 0.25733643724696353, 0.1...
257  [0.41543625000000034, 0.25733643724696353, 0.1...
258  [0.41543625000000034, 0.25733643724696353, 0.1...
259  [0.41543625000000034, 0.25733643724696353, 0.1...

                                                 y_hat  neurons
0    [0.6490093469619751, 0.4962880313396454, 0.330...      NaN
1    [0.5390886664390564, 0.44875937700271606, 0.27...      NaN
2    [0.44792526960372925, 0.3475313186645508, 0.22...      NaN
3    [0.5522405505180359, 0.41050687432289124, 0.22...      NaN
4    [0.45166653394699097, 0.32198846340179443, 0.1...      NaN
..                                                 ...      ...
255  [0.054537031799554825, -0.06379106640815735, -...    200.0
256  [0.09724868088960648, 0.02917511574923992, -0....    200.0
257  [0.09479764848947525, -0.02446725033223629, -0...    200.0
258  [0.1585140824317932, 0.09288448840379715, 0.00...    200.0
259  [0.07414036989212036, -0.04720684140920639, -0...    200.0

[260 rows x 19 columns]

In [17]:
df.shape

(260, 19)

In [18]:
df.head()

,_id,statefule,batch_size,forecast_period,features,timesteps,shuffle,TotalLength,learningRate,history,earlyStoppingLength,epochBest,changeWeights,date,testError,trainError,y_test,y_hat,neurons
0,67c3ec8f9f8c93b67411ab93,False,48,8,6,24,False,420,0.002,"{'loss': [0.0891372486948967, 0.07234407961368...",100,100,True,2025-03-01 22:28:35.329,0.406009,0.224982,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.6490093469619751, 0.4962880313396454, 0.330...",NaN
1,67c3ec9b9f8c93b67411ab94,False,48,8,6,24,False,420,0.002,"{'loss': [0.017181525006890297, 0.023382451385...",100,100,True,2025-03-01 22:28:35.329,0.364325,0.104216,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.5390886664390564, 0.44875937700271606, 0.27...",NaN
2,67c3eca89f8c93b67411ab95,False,48,8,6,24,False,420,0.002,"{'loss': [0.009490793570876122, 0.015723206102...",100,100,True,2025-03-01 22:28:35.329,0.383692,0.115948,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.44792526960372925, 0.3475313186645508, 0.22...",NaN
3,67c3ecb49f8c93b67411ab96,False,48,8,6,24,False,420,0.002,"{'loss': [0.011466928757727146, 0.010548892430...",100,100,True,2025-03-01 22:28:35.329,0.410618,0.070342,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.5522405505180359, 0.41050687432289124, 0.22...",NaN
4,67c3ecc19f8c93b67411ab97,False,48,8,6,24,False,420,0.002,"{'loss': [0.00421214010566473, 0.0083453562110...",100,100,True,2025-03-01 22:28:35.329,0.399200,0.071963,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.45166653394699097, 0.32198846340179443, 0.1...",NaN

In [19]:
df["forecast_period"].value_counts()

forecast_period
8    260
Name: count, dtype: int64

In [20]:
df["batch_size"].value_counts()

batch_size
48    170
24     20
64     20
56     20
60     20
72     10
Name: count, dtype: int64

In [21]:
df["timesteps"].value_counts()

timesteps
24    240
12     10
36     10
Name: count, dtype: int64

In [24]:
df.groupby(["batch_size","earlyStoppingLength","neurons"])[["trainError","testError"]].mean()

                                        trainError  testError
batch_size earlyStoppingLength neurons
24         150                 200.0      0.122403   0.524502
48         15                  200.0      0.160434   0.425303
           100                 100.0      0.072244   0.442269
                               200.0      0.083674   0.403008
           150                 200.0      0.188465   0.442639
           200                 200.0      0.053912   0.336473
56         15                  200.0      0.178313   0.381306
60         15                  200.0      0.164854   0.365837
64         15                  200.0      0.156797   0.445933
           150                 200.0      0.147044   0.528034
72         15                  200.0      0.192572   0.452933