In [2]:
import pandas as pd
import sys
sys.path.insert(0, '/mnt/c/users/cojoe/Python-Stuff')
import JCLib
import threading
import PySimpleGUI as sg
import pyglet,tkinter
# import OpenGL
# from OpenGL import GLU
pyglet.font.add_file('/etc/fonts/fonts/CENTAUR.TTF')

## Liquor Licenses

In [ ]:
df = pd.read_csv("~/bic_etl/cdor/regulations_liquor/data_transformed/liquorLicenses.csv")

In [ ]:
df.shape

In [ ]:
df.head()

In [ ]:
df.isna().sum()

In [ ]:
Orig = pd.read_excel("~/bic_etl/cdor/regulations_liquor/data_source/liquorLicenses.xlsx",engine="openpyxl")

In [ ]:
Orig

In [ ]:
Orig.shape

In [ ]:
Orig.tail()

## Temporary Liquor Licenses

### CIM data

In [ ]:
TempCIM = pd.read_csv("https://data.colorado.gov/api/views/d4s4-xqg6/rows.csv?accessType=DOWNLOAD")

In [ ]:
TempCIM.head()

In [ ]:
TempCIM.shape

In [ ]:
TempCIM.isna().sum()

In [ ]:
TempCIM["eventDate"].value_counts()

### Locally converted file

In [ ]:
tempNew = pd.read_csv("~/bic_etl/cdor/regulations_liquor/data_transformed/tempSalesRooms.csv")

In [ ]:
tempNew.shape

In [ ]:
tempNew.tail()

In [ ]:
tempNew.isna().sum()

In [ ]:
tempNew["EVENT DATES"].value_counts()

In [ ]:
tempNew.head()

In [ ]:
tempNew.isna().sum()

In [ ]:
tempNew.dtypes

### Local Original File

In [ ]:
#tempOrig= pd.read_excel("~/bic_etl/cdor/regulations_liquor/data_source/tempSalesRooms.xlsx",skiprows=1,engine="openpyxl")
tempOrig= pd.read_excel("~/bic_etl/cdor/regulations_liquor/data_source/tempSalesRooms.xlsx",skiprows=1)

In [ ]:
tempOrig.shape

In [ ]:
tempOrig.head()

In [ ]:
tempOrig.columns

In [ ]:
tempOrig['(WDO) = Wednesdays Only                          \n(ThO) = Thursdays Only                                  \n(FO) = Fridays Only                                        \n(SO) = Saturdays Only                                 \n(SuO) = Sundays Only                    \n(WO) = Weekends Only'].value_counts()

In [ ]:
tempOrig.shape

In [ ]:
tempOrig["EVENT DATES"].value_counts()

In [ ]:
tempOrig.columns

In [ ]:
tempOrig.dtypes

In [ ]:
tempOrig.isna().sum()

In [ ]:
tempOrig["EVENT DATES"].str.len().value_counts()

In [ ]:
for nn,row in tempOrig.iterrows():
    print(row["EVENT DATES"])

In [ ]:
for nn,row in tempNew.iterrows():
    print(row["EVENT DATES"])

In [ ]:
tempNew.shape

In [ ]:
tempOrig.shape

In [ ]:
pd.show_versions()

In [ ]:
print(tempNew.shape)
print(tempOrig.shape)

In [ ]:
tempNew.columns

In [ ]:
print(tempNew[["Licensee (DBA)","Licensee #"]].head())
print("---------")
print(tempOrig[["Licensee (DBA)","Licensee #"]].head())

## Special Events

### Original Data

In [ ]:
spcl = pd.read_excel("~/bic_etl/cdor/regulations_liquor/data_source/specialEvents.xlsx",engine="openpyxl")

In [ ]:
spcl.shape

In [ ]:
spcl.isna().sum()

In [ ]:
spcl2 = pd.read_excel("~/bic_etl/cdor/regulations_liquor/data_source/specialEvents.xlsx")

In [ ]:
spcl2.shape

In [ ]:
spcl.tail()

In [ ]:
spclCim = pd.read_csv("https://data.colorado.gov/api/views/d6t8-xish/rows.csv?accessType=DOWNLOAD")

In [ ]:
spclCim.head()

In [ ]:
spclCim.isna().sum()

## Business Entities

### Original file

In [ ]:
df = pd.read_csv("corpmstr.tsv",sep="\t")

## Retail Reports by County

### Original Data

In [ ]:
file="Retail Reports by County in Colorado County.csv"
file = f"~/bic_etl/cdor/retail_reports/data_source/{file}"
print(file)
retRepCntyOrig = pd.read_csv(file,header=4,skipfooter=10)

In [ ]:
JCLib.missingAnal(retRepCntyOrig)

In [ ]:
print(retRepCntyOrig.dtypes)
retRepCntyOrig["Month"].value_counts()

In [ ]:
def mapMonth(row):
    val = row["Month"]
    valo=val
    if val < 10:
       val=f"0{val}"
    else:
        val=str(val)
    return val
    

retRepCntyOrig['monthD'] = retRepCntyOrig.apply(mapMonth,axis=1)
print(retRepCntyOrig["monthD"].value_counts())
retRepCntyOrig['date'] = retRepCntyOrig["Year"].astype(str) + "/" + retRepCntyOrig["monthD"]
print(retRepCntyOrig['date'].dtypes)
retRepCntyOrig['date'] = pd.to_datetime(retRepCntyOrig["date"],format="%Y/%m").dt.normalize()
print(retRepCntyOrig['date'].value_counts())

In [ ]:
JCLib.invYrMo(retRepCntyOrig,"date","%Y%m",2)

### Converted File

In [ ]:
file='Retail Reports by County in Colorado ready for CIM.csv'
file = f"~/bic_etl/cdor/retail_reports/data_transformed/{file}"
print(file)
retRepCntyConv = pd.read_csv(file)

In [ ]:
JCLib.missingAnal(retRepCntyConv)

In [ ]:
retRepCntyConv

In [ ]:
retRepCntyConv.shape

### CIM

In [ ]:
retRepCntyCIM = pd.read_csv("https://data.colorado.gov/api/views/x8tb-f3vh/rows.csv?accessType=DOWNLOAD")

In [ ]:
retRepCntyCIM.shape

In [ ]:
retRepCntyCIM.head()

In [ ]:
JCLib.missingAnal(retRepCntyCIM)

In [ ]:
retRepCntyCIM['year'].astype(str) + retRepCntyCIM['month'].astype(str)

In [ ]:
pd.to_datetime(retRepCntyCIM['year'].astype(str)+retRepCntyCIM['month'].astype(str),format="%Y%M").dt.mont

In [ ]:
def mapMonth(row):
    val = row["month"]
    valo=val
    if val < 10:
       val=f"0{val}"
    else:
        val=str(val)
    return val
    

retRepCntyCIM['monthD'] = retRepCntyCIM.apply(mapMonth,axis=1)
print(retRepCntyCIM["monthD"].value_counts())
retRepCntyCIM['date'] = retRepCntyCIM["year"].astype(str) + "/" + retRepCntyCIM["monthD"]
print(retRepCntyCIM['date'].dtypes)
retRepCntyCIM['date'] = pd.to_datetime(retRepCntyCIM["date"],format="%Y/%m").dt.normalize()
print(retRepCntyCIM['date'].value_counts())

In [ ]:
retRepCntyCIM['date'].value_counts()

In [ ]:
retRepCntyCIM["date"]

In [ ]:

JCLib.invYrMo(retRepCntyCIM,"date","%Y-%m-%d",2)

In [ ]:
retRepCntyCIM.head()

In [ ]:
retRepCntyCIM["year"].max()

In [ ]:
retRepCntyCIM.tail()

In [ ]:
dir(JCLib)

## Recently Approved Retail Licensces

### Original Data

In [2]:
recRetLicOrig = pd.read_excel("~/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved.xlsx",engine="openpyxl")

In [ ]:
recRetLicOrig.head()

In [ ]:
dir(JCLib)

In [ ]:
JCLib.invYrMo(recRetLicOrig,"ISSUE DATE","%Y-%m-%d",2)

### CIM

In [25]:
recRetLicCIM = pd.read_csv("~/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv")

In [26]:
recRetLicCIM.head()

,Licensee Name,Doing Business As,License Type,Issue Date,License Number,Street Address,City,State,Zip,Location
0,SUSHI HAO II INC,RED GINGER,Hotel & Restaurant (city),02/15/2023,03-18221,550 NORTH BROADWAY SUITE E,Denver,CO,80203,"550 NORTH BROADWAY SUITE E\nDenver, CO 80203\n..."
1,MOUNT GOLIAN GRILL LLC,MOUNT GOLIAN GRILL,Takeout & Delivery Permit,02/06/2023,03-17947,322A NORTH MAIN STREET,Breckenridge,CO,80424,"322A NORTH MAIN STREET\nBreckenridge, CO 80424..."
2,SHINS MNGMT INC,SUKIYA RAMEN,Hotel & Restaurant (city),02/10/2023,03-17888,1472 SOUTH PEARL STREET #201,Denver,CO,80210,"1472 SOUTH PEARL STREET #201\nDenver, CO 80210..."
3,CLUB GREENWOOD,CLUB GREENWOOD,Lodging & Entertainment (City),02/22/2023,03-18166,5801 SOUTH QUEBEC STREET,Greenwood Village,CO,80111,"5801 SOUTH QUEBEC STREET\nGreenwood Village, C..."
4,"LITTLE JAYDEN, LLC",MOUSA WINE & SPIRITS,Liquor Store (city),02/21/2023,03-18489,1957 SOUTH FEDERAL BOULEVARD,Denver,CO,80219,"1957 SOUTH FEDERAL BOULEVARD\nDenver, CO 80219..."

In [ ]:
JCLib.invYrMo(recRetLicCIM,"Issue Date","%m/%d/%Y",2)

### Converted

In [3]:
recRetLicConv = pd.read_csv("~/bic_etl/cdor/regulations_liquor/data_transformed/recentlyApproved.csv")

In [ ]:
recRetLicConv.head()

In [ ]:
JCLib.analyzeDF(recRetLicConv)

In [ ]:
dir(JCLib)

In [ ]:
JCLib.analyzeDfGui(recRetLicOrig,"")

In [5]:
recRetLicOrig.columns

Index(['LICENSEE NAME', 'DOING BUSINESS AS', 'LICENSE TYPE', 'ISSUE DATE',
       'LICENSE #', 'STREET ADDRESS', 'CITY', 'STATE', 'ZIP'],
      dtype='object')

In [4]:
recRetLicConv.columns

Index(['Licensee Name', 'Doing Business As', 'License Type', 'Issue Date',
       'License Number', 'Street Address', 'City', 'State', 'Zip'],
      dtype='object')

### CIM

In [2]:
recRetLicCIM = pd.read_csv("https://data.colorado.gov/api/views/htyp-tqzh/rows.csv?accessType=DOWNLOAD")

In [19]:
recRetLicCIM.head()

,Licensee Name,Doing Business As,License Type,Issue Date,License Number,Street Address,City,State,Zip,Location
0,PAGOSA BAR LLC,PAGOSA BAR,Tavern (city),05/24/2023,03-18828,460 PAGOSA STREET,Pagosa Springs,CO,81147,"460 PAGOSA STREET\nPagosa Springs, CO 81147\n(..."
1,SPIRITED 2706 LARIMER LLC,AMERICAN BONDED,Tavern (city),05/21/2023,03-18712,2706 LARIMER STREET,Denver,CO,80205,"2706 LARIMER STREET\nDenver, CO 80205\n(39.759..."
2,S&S CASTLE ROCK LLC,SCISSORS & SCOTCH,Tavern (city),05/10/2023,03-18305,20 WILCOX STREET UNIT C-104,Castle Rock,CO,80104,"20 WILCOX STREET UNIT C-104\nCastle Rock, CO 8..."
3,K & B ENTERPRISES INC,TEA & PHO CO,Hotel & Restaurant (county),05/11/2023,03-18824,"5934 SOUTH KIPLING PARKWAY UNITS C, D, & E",Littleton,CO,80127,"5934 SOUTH KIPLING PARKWAY UNITS C, D, & E\nLi..."
4,THOUGHTS LLC,Legends A Meadery,Importer (vinous & spirituous),05/18/2023,03-18760,22,Johnstown,CO,80534,"22\nJohnstown, CO 80534\n(40.3347511, -104.912..."

In [8]:



stats,nstats,ndates,columnsNoDate = dfStringAnal(recRetLicCIM)

Licensee Name
Doing Business As
License Type
Issue Date
License Number
Street Address
City
State
Zip
Location

In [7]:
def dfStringAnal(df):
    stats = {}
    nstats = {}
    ndates={}
    nums = ["int64","float64"]
    columnsNoDate=[]
    for col in df: 
        print(col)
        if df[col].dtypes == "object":
            columnsNoDate.append(col)
            stats[col] = {}
            stats[col]["digits"] = df[col].str.contains("\d").sum()
            stats[col]["non-digits"] = df[col].str.contains("\D").sum()
            stats[col]["numeric"] = df[col].str.replace(".","",1).str.isdecimal().sum()
            
            
            stats[col]["word"] = df[col].str.contains("\w").sum()
#            stats[col]["non-word"] = df["B1_PER_ID1"].str.contains("\S").sum()
            stats[col]["non-word"] = df[col].str.contains("[^a-zA-Z0-9_ \-]").sum() 
            stats[col]["white-spc"] = df[col].str.contains("\s").sum()   
    
            stats[col]["_"] = df[col].str.contains("_").sum()                        
            stats[col]["-"] = df[col].str.contains("-").sum()   
            stats[col]["#"] = df[col].str.contains("#").sum() 
            stats[col]["missing"] = df[col].isna().sum() 
        elif df[col].dtypes in nums:
            
            columnsNoDate.append(col)            
            amin,amax,amen,astd = df[col].agg(["min","max","mean","std"])
            
            nstats[col]={}
            nstats[col]["Min"] = amin
            nstats[col]["Max"] = amax
            nstats[col]["Mean"] = amen
            nstats[col]["Std"] = astd
            nstats[col]["Missing"] =df[col].isna().sum()
        else:
            print("LOOKIE WHAT I FOUND",df[col].dtypes)
            ndates[col]={}
            ndates[col]["Start"] = df[col].min()
            ndates[col]["End"] = df[col].max()
            ndates[col]["# Unique Dates"] = df[col].nunique()
            
            
            
    nrecs=0
    return stats,nstats,ndates,columnsNoDate

In [3]:
def inventoryYrMoDy(df,column):
    ''' invYrMo,invYrMoDy = inventoryYrMoDy(df,"Date Column")
    Compute Year-Month and Year-Month-Day inventory counts
    for a date column in the dataframe.  It is expected the 
    column is already a PANDAS date-time object'''
    amax=df[column].max()
    amin=df[column].min()
    print(amin.year,amax.year)
    invYrMo = {}
    invYrMoDy = {}

    for yr in range(amin.year,amax.year+1):
        invYrMo[yr]={}
        invYrMoDy[yr]={}
        for mo in range(1,13):
            invYrMo[yr][mo]=0
            invYrMoDy[yr][mo]={}      
            for dy in range(1,32):
                invYrMoDy[yr][mo][dy]=0

    x = df[column].value_counts()
    for xx in sorted(x.index):
        d=xx
        invYrMo[d.year][d.month]+= x[xx]
        invYrMoDy[d.year][d.month][d.day]+= x[xx]   
        
    return invYrMo,invYrMoDy

def showDates(df,col,windowParent):
   
    head_YrMo = ["Year","Jan","Feb","Mar","Apr","May","Jun","Jul","Aug","Sep","Oct","Dec"]
    fname = col.replace(" ","")  #  output name used for file if output written
  
    iYrMo,iYrMoDy=inventoryYrMoDy(df,col)
    
    valuesYrMo=[]
    for yr in sorted(iYrMo.keys()):
        tmp = [yr]
        for mo in range(1,13):
            tmp.append(iYrMo[yr][mo])       
        valuesYrMo.append(tmp)


    
    layout2 = [    
                   [sg.Text(f"Year-Month Inventory",text_color="black"),sg.Text(f" {col}",text_color="red")],
                   [sg.Button('Close')],
                   [sg.Button('Show YrMoDy Inv')],
                   [sg.Table(values=valuesYrMo,
                       background_color='white',vertical_scroll_only=False,
                       auto_size_columns=False,enable_events=True,def_col_width=10,font="CENTAUR 10",
                       justification='center',alternating_row_color='tan',
                       key='-TABLEDATE-', headings = head_YrMo)]
            ]
    window2 = sg.Window(f"Inventory", layout2,finalize=True,resizable=True, grab_anywhere=False)
    table3n = window2['-TABLEDATE-']
    table3n.bind('<Button-1>', "Click")
#    window2['-TABLE2-'].expand(True, True)
    
    try:
        while True:
                event, vals = window2.read()
                print(event,vals)
            #    window, event, values = sg.read_all_windows()
                if event == sg.WIN_CLOSED or event == 'Close':
                    window2.close()
            #        sys.exit(1)
                    what = "QUIT"
                    break
                elif event == 'Show YrMoDy Inv':
                    head_YrMoDy = ["Year","Month"] + [f"Day {nn}" for nn in range(1,32)]
                    valuesYrMoDy=[]                             
                    for yr in sorted(iYrMoDy.keys()):
                        for mo in range(1,13):
                            tmp = [yr,mo]
                            for dy in range(1,32):
                                tmp.append(iYrMoDy[yr][mo][dy])         
                            valuesYrMoDy.append(tmp)
                    layout3 = [    
                       [sg.Text(f"Year-Month Inventory",text_color="black"),sg.Text(f" {col}",text_color="red")],
                       [sg.Button('Close')],
                       
                       [sg.Table(values=valuesYrMoDy,
                           background_color='white',vertical_scroll_only=False,
                           auto_size_columns=False,enable_events=True,def_col_width=8,font="CENTAUR 8",
                           justification='center',alternating_row_color='tan',
                           key='-TABLEDATE-', headings = head_YrMoDy)]
                    ]
                    window3 = sg.Window(f"Year-Month-Day Inventory", layout3,finalize=True,resizable=True, grab_anywhere=False)

                    try:
                        while True:
                            event, vals = window3.read()
                            print(event,vals)
                        #    window, event, values = sg.read_all_windows()
                            if event == sg.WIN_CLOSED or event == 'Close':
                                window3.close()
                                break
                    except Exception as e:
                        print(e)
                        print("Inventory YRMODY Table")
                    
                    
                    
    except Exception as e:
        print(e)
        print("inventory YrMo")








def dfStringShow(df,col,statType):
    print(col,statType)
    if df[col].dtypes == "object":
        if statType == "digits":
          tmp = df.loc[df[col].notna() & df[col].str.contains("\d")]
        elif statType == "non-digits":
          tmp = df.loc[df[col].notna() & df[col].str.contains("\D")]
        elif statType == "numeric":
          tmp = df.loc[df[col].notna() & df[col].str.replace(".","",1).str.isdecimal()]
        elif statType == "word":
          tmp = df.loc[df[col].notna() & df[col].str.contains("\w")]
        elif statType == "non-word":
          tmp = df.loc[df[col].notna() & df[col].str.contains("[^a-zA-Z0-9_ \-]")]
        elif statType == "white-spc":
          tmp = df.loc[df[col].notna() & df[col].str.contains("\s")]
        elif statType == "_":
          tmp = df.loc[df[col].notna() & df[col].str.contains("_")]
        elif statType == "-":
          tmp = df.loc[df[col].notna() & df[col].str.contains("-")]
        elif statType == "#":
          tmp = df.loc[df[col].notna() & df[col].str.contains("#")]
        elif statType == "missing":
          tmp = df.loc[df[col].isna()]

        return tmp   
    
def showDFN(col,unq,windowParent):
   
 
    fname = col.replace(" ","")  #  output name used for file if output written
  
    valuesUNQ = list(zip(unq.index.tolist(),unq.tolist()))

    titleSort=1
    hUNQ = []
    hUNQ.append("Values")
    hUNQ.append("Count")

    
    sortState = []
    for val in hUNQ:
        sortState.append(1)
        
    layout2 = [    
                   [sg.Text(f"Unique Values for Column",text_color="black"),sg.Text(f" {col}",text_color="red")],
                   [sg.Button('Close')],
                   [sg.Button('Write Unique'),sg.Table(values=valuesUNQ,font="CENTAUR 15",
                       background_color='white',vertical_scroll_only=False,col_widths=[20,20],
                       auto_size_columns=False,enable_events=True,def_col_width=25,
                       justification='right',alternating_row_color='tan',
                       key='-TABLE3N-', headings = hUNQ)]
            ]
    window2 = sg.Window(f"DataFrame", layout2,finalize=True,resizable=True, grab_anywhere=False)
    table3n = window2['-TABLE3N-']
    table3n.bind('<Button-1>', "Click")
#    window2['-TABLE2-'].expand(True, True)
    
    try:
        while True:
                event, vals = window2.read()
                print(event,vals)
            #    window, event, values = sg.read_all_windows()
                if event == sg.WIN_CLOSED or event == 'Close':
                    window2.close()
            #        sys.exit(1)
                    what = "QUIT"
                    break
                elif event == "Write Unique":
                    fout = open(f"{fname}.unq.txt","a+")
                    fout.write(f"\nColumn:Type:({col},Count)\n")
                    fout.writelines([f"{col}:UNIQUE:{line}\n" for line in valuesUNQ])
                    fout.close()
                    text = f"{col} Wrote Unique Records to file {fname}.unq.txt\n"
                    windowParent["-PINFO-"].update(text,append="True")
                elif event == "-TABLE3N-Click":
                    e = table3n.user_bind_event
                    region = table3n.Widget.identify('region', e.x, e.y)
                    if region == 'heading':
                         column = int(table3n.Widget.identify_column(e.x)[1:])
                         
                         if column-1 < len(sortState):  # check to be certain column selected in range
                             sortState[column-1]*=-1
                             if sortState[column-1] == -1:
                                sortAsc=False
                             else:
                                sortAsc=True
                             valuesUNQ = sorted(valuesUNQ, key=lambda element: (element[column-1]),reverse=sortAsc)  
                             window2['-TABLE3N-'].update(values=valuesUNQ)
                    elif region == 'separator':
                        continue
                    else:
                        continue
    except Exception as e:
        print(e)
        print("Table 2")



def showDF(df,col,st,unq,regex,idcol,windowParent):
    print("ID COL ",idcol)
    h = []
    cols=[]
    fname = col.replace(" ","")  #  output name used for file if output written
    h.append("Index")
    if len(idcol) > 0:
        h.append(idcol)
        cols.append(idcol)
    h.append(col)
    cols.append(col)
   
    if len(idcol) > 0:
      tmp = df.loc[:,cols]
      values = list(zip(tmp.index.tolist(),tmp.loc[:,idcol].tolist(),tmp.loc[:,col].tolist()))
    else:
      tmp = df.loc[:,col]
      values = list(zip(tmp.index.tolist(),tmp.tolist()))
    header= h
    valuesUNQ = list(zip(unq.index.tolist(),unq.tolist()))
#    print([f"{line}\n" for line in valuesUNQ])

    titleSort=1
    hUNQ = []
    hUNQ.append("Values")
    hUNQ.append("Count")

    
    sortState = []
    for val in hUNQ:
        sortState.append(1)
        
    layout2 = [    
                   [sg.Text(f"Showing Rows for Column"),sg.Text(f" {col}",text_color="red"),sg.Text(f" and Reg Ex",text_color="black"),sg.Text(f"{st} : {regex[st]}",text_color="red")],
                   [sg.Text(f"Total Rows with "),sg.Text(f" {regex[st]}",text_color="red"),sg.Text(f": {tmp.shape[0]} ")],
                   [sg.Button('Close')],
                   [sg.Button('Write Bad'),sg.Table(values=values,
                       background_color='green',vertical_scroll_only=False,font="CENTAUR 15",
                       auto_size_columns=True,enable_events=False,def_col_width=30,
                       justification='right',alternating_row_color='brown',
                       key='-TABLE2-', headings = header)],
                   [sg.Button('Write Unique'),sg.Table(values=valuesUNQ,
                       background_color='white',vertical_scroll_only=False,col_widths=60,font='Courier 10 bold ' ,
                       auto_size_columns=True,enable_events=True,def_col_width=25,
                       justification='right',alternating_row_color='tan',
                       key='-TABLE3-', headings = hUNQ)]
            ]
    window2 = sg.Window(f"DataFrame", layout2,finalize=True,resizable=True, grab_anywhere=False)
    table2 = window2['-TABLE2-']
    table3 = window2['-TABLE3-']
    table3.bind('<Button-1>', "Click")
#    window2['-TABLE2-'].expand(True, True)
    
    try:
        while True:
                event, vals = window2.read()
                print(event,vals)
            #    window, event, values = sg.read_all_windows()
                if event == sg.WIN_CLOSED or event == 'Close':
                    window2.close()
            #        sys.exit(1)
                    what = "QUIT"
                    break
                elif event == "Write Unique":
                    fout = open(f"{fname}.unq.txt","a+")
                    fout.write(f"\nColumn:Type:({col},Count)\n")
                    fout.writelines([f"{col}:UNIQUE:{line}\n" for line in valuesUNQ])
                    fout.close()
                    text = f"{col} Wrote Unique Records to file {fname}.unq.txt\n"
                    windowParent["-PINFO-"].update(text,append="True")
                elif event == "Write Bad":
                    fout = open(f"{fname}.bad.txt","a+")
                    fout.write(f"Column:Type:Desc:Reg Ex:(Index,{idcol},{col})\n")
                    fout.writelines([f"{col}:BAD:{st}:{regex[st]}:{line}\n" for line in values])
                    fout.close()
                    text = f"{col} Wrote Bad Records to file {fname}.bad.txt\n"
                    windowParent["-PINFO-"].update(text,append="True")
                elif event == "-TABLE3-Click":
                    e = table3.user_bind_event
                    region = table3.Widget.identify('region', e.x, e.y)
                    if region == 'heading':
                         column = int(table3.Widget.identify_column(e.x)[1:])
                         
                         if column-1 < len(sortState):  # check to be certain column selected in range
                             sortState[column-1]*=-1
                             if sortState[column-1] == -1:
                                sortAsc=False
                             else:
                                sortAsc=True
                             valuesUNQ = sorted(valuesUNQ, key=lambda element: (element[column-1]),reverse=sortAsc)  
                             window2['-TABLE3-'].update(values=valuesUNQ)
                    elif region == 'separator':
                        continue
                    else:
                        continue
    except Exception as e:
        print(e)
        print("Table 2")





def analyzeDfGui(dfO,idcol,windowP,file):
    
    df = dfO.copy()
    regex = {}
    regex["digits"] = "\d"
    regex["non-digits"] = "\D"
    regex["numeric"] = "isdecimal()"
    
    regex["word"] = "\w"
    regex["non-word"] = "[^a-zA-Z0-9_ \-]"
    regex["white-spc"] = "\s"  
    regex["_"] = "_"                        
    regex["-"] = "-"
    regex["#"] = "#" 
    regex["missing"] = "isna()" 


    stats,nstats,ndates,colsNoDate = dfStringAnal(df)

    header_list = ["Column","digits","non-digits","numeric","word","non-word","white-spc","  _  ","  -  ","  #  ","missing"]
    col_widths = [8]*len(header_list)
    col_widths[0] = 25

    statsVals=[]
    for col in sorted(stats.keys()):
         vals=[]
         vals.append(col)
         for k in header_list[1:]:
            vals.append(stats[col][k.strip()])
         statsVals.append(vals)
    slen= len(statsVals)
    
## Number Stats for Tables
    header_nlist = ["Column","Min","Max","Mean","Std","Missing"]
    nstatsVals=[]
    for col in sorted(nstats.keys()):
         vals=[]
         vals.append(col)
         for k in header_nlist[1:]:
            vals.append(nstats[col][k])
         nstatsVals.append(vals)
    nlen=len(nstatsVals)

## Date Stats for Tables   
    header_dlist = ["Column","Start","End","# Unique Dates"]
    ndateVals=[]
    for col in sorted(ndates.keys()):
         vals=[]
         vals.append(col)
         for k in header_dlist[1:]:
            vals.append(ndates[col][k])
         ndateVals.append(vals)
    
    
    
    
    layout = [ 
             [sg.Text(f"File: {file}")],
             [sg.Button('Quit')],
             [sg.Multiline(default_text="Summary\n",key="-PINFO-",size=[70,5])],
             [sg.Table(values=statsVals, background_color='#b3f0ff', text_color="black", auto_size_columns=False,enable_events=True,num_rows=slen+2,col_widths=col_widths,font="CENTAUR 15",
                   justification='center',alternating_row_color='#33d6ff',pad=(5,5),vertical_scroll_only=False,
                   key='-TABLE-', headings = header_list)],
             [sg.Table(values=nstatsVals, 
                   background_color='#b3f0ff',text_color="black",
                   auto_size_columns=False,enable_events=True,num_rows=nlen+2,col_widths=col_widths,font="CENTAUR 15",justification='center',alternating_row_color='#33d6ff',pad=(5,5),vertical_scroll_only=False,
                   key='-TABLEN-', headings = header_nlist)],
             [sg.Text("Convert Column to Date",font="CENTAUR 15"),sg.Combo(colsNoDate,s=[25,4],font="CENTAUR 15 bold",expand_y=True,key="-CONVDATE-",enable_events=True),sg.Text("Format: "),sg.Multiline("",s=(10,1),key="-DATEFORM-"),sg.Button("Convert to Date")],
             [sg.Table(values=ndateVals, 
                   background_color='#b3f0ff',text_color="black",
                   auto_size_columns=False,enable_events=True,num_rows=nlen+2,col_widths=[25,12,12,10],font="CENTAUR 15",justification='center',alternating_row_color='#33d6ff',pad=(5,5),vertical_scroll_only=False,
                   key='-TABLED-', headings = header_dlist)]
       ]
    # Create the Window
    sg.theme('Lightblue')
    window = sg.Window('Output', layout,finalize=True,resizable=True)
    window.TKroot.focus_set()

    #window2.move(window.current_location()[0]+600, window.current_location()[1])
    table = window['-TABLE-']
    table.bind('<Button-1>', "Click")
    tablen = window['-TABLEN-']
    tablen.bind('<Button-1>', "Click")
    tabled = window['-TABLED-']
    tabled.bind('<Button-1>', "Click")

    while True:
        try:
            event, values = window.read()
            print(event)
            print("V ",values)
            print("D ",values["-DATEFORM-"])
            
        #    window, event, values = sg.read_all_windows()
            if event == sg.WIN_CLOSED or event == 'Quit':
                window.close()
        #        sys.exit(1)
                what = "QUIT"
                break
            elif event == '-TABLE-':
                pass
            elif event == '-TABLE-Click':
                e = table.user_bind_event
                region = table.Widget.identify('region', e.x, e.y)
                if region == 'heading':
                    row = 0
                elif region == 'cell':
                    row = int(table.Widget.identify_row(e.y))
                elif region == 'separator':
                    continue
                else:
                    continue
                colClicked = int(table.Widget.identify_column(e.x)[1:])
                statClicked = header_list[colClicked-1].strip()
                columnClicked = statsVals[row-1][0]
                print("COL ",columnClicked,colClicked)
                print("STT ",statClicked,)
                

                tmp = dfStringShow(df,columnClicked,statClicked)
                un = df[columnClicked].value_counts()
                showDF(tmp,columnClicked,statClicked,un,regex,idcol,window)
            elif event == '-TABLEN-Click':
                e = tablen.user_bind_event
                region = tablen.Widget.identify('region', e.x, e.y)
                if region == 'heading':
                    pass
                elif region == 'cell':
                    row = int(tablen.Widget.identify_row(e.y))
                elif region == 'separator':
                    continue
                else:
                    continue
            #    colClicked = int(tablen.Widget.identify_column(e.x)[1:])
            #    statClicked = header_list[colClicked-1].strip()
                colClicked = nstatsVals[row-1][0]
                print("TN ",colClicked)
                # tmp = dfStringShow(septicOrig,columnClicked,statClicked)
                un = df[colClicked].value_counts()
                showDFN(colClicked,un,window)
                
                
            elif event == '-TABLED-Click':
                e = tabled.user_bind_event
                region = tabled.Widget.identify('region', e.x, e.y)
                if region == 'heading':
                    pass
                elif region == 'cell':
                    row = int(tabled.Widget.identify_row(e.y))
                elif region == 'separator':
                    continue
                else:
                    continue
                colClicked = ndateVals[row-1][0]
                print("TD ",colClicked)
                # tmp = dfStringShow(septicOrig,columnClicked,statClicked)
                showDates(df,colClicked,window)
            elif event == 'Convert to Date':  
                print("Chnage Date")
                print(values["-CONVDATE-"])
                dcol = values["-CONVDATE-"]
                dform = values["-DATEFORM-"]
                if len(dform) > 0:
                    form=dform.strip()
                else:
                    form= "%m/%d/%Y"
                df[dcol]=pd.to_datetime(df[dcol], format=form)
                ndates[dcol]={}
                ndates[dcol]["Start"] = df[dcol].min()
                ndates[dcol]["End"] = df[dcol].max()
                ndates[dcol]["# Unique Dates"] = df[dcol].nunique()
                ndateVals=[]
                for col in sorted(ndates.keys()):
                     vals=[]
                     vals.append(col)
                     for k in header_dlist[1:]:
                        vals.append(ndates[col][k])
                     ndateVals.append(vals)
                window['-TABLED-'].update(values=ndateVals)
        except Exception as e:
            print(e)
            print("bad bad ")

In [40]:
def fileBrowser():
    threads = []
    layout = [ 
             [sg.FilesBrowse(initial_folder="/home/joe",font="CENTAUR 15",file_types=[("CSV Files","*.csv")],enable_events=True,key='-FILES-')],
             [sg.Text("Column String Analysis")],
             [sg.Button('Quit')],
             [sg.Multiline(default_text="Summary\n",key="-PINFO-",font="CENTAUR 10",size=[70,5])],
            ]
    # Create the Window
    sg.theme('Lightblue')
    window = sg.Window('Output', layout,finalize=True,resizable=True)
    window.TKroot.focus_set()

    #window2.move(window.current_location()[0]+600, window.current_location()[1])
 
    while True:
        try:
            event, values = window.read()
            print(event)
            print("V ",values)
            print("D ",values["-FILES-"])
            
        #    window, event, values = sg.read_all_windows()
            if event == sg.WIN_CLOSED or event == 'Quit':
                window.close()
                break
            elif event == "-FILES-":
                file=values["-FILES-"]
                string=f"Processed File: {file}"
                df=pd.read_csv(file)
                window["-PINFO-"].update(string)
                threads.append(threading.Thread(target=analyzeDfGui, 
                           args=(df,"",window,file)))
                ntrds = len(threads)
                threads[ntrds-1].start()
                threads[ntrds-1].join()
#                analyzeDfGui(df,"",window,file)
        except Exception as e:
            print(e)
            
fileBrowser()

-FILES-
V  {'-FILES-': '/home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv', '-PINFO-': 'Summary'}
D  /home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv
C  Zip
5676.0 815269529.0 4038147.9563106797 56796882.696899645

Exception in thread Thread-7 (analyzeDfGui):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_1336/2470374957.py", line 437, in analyzeDfGui
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9618, in __init__
    self.Finalize()
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10304, in finalize
    self.Read(timeout=1)
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10079, in read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10150, in _read
    self._Show()
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9890, in _Show
    StartupTK(self)
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16824, in StartupTK
    root = tk.Toplevel(class_=window.Title)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2650, in __init__
    BaseWidget.__init__(self, master, 'toplevel', cnf, {}, extra)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2601, in __init__
    self.tk.call(
RuntimeError: main thread is not in main loop

Quit
V  {'-FILES-': '/home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv', '-PINFO-': 'Processed File: /home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv'}
D  /home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv

In [17]:
! ls /home

joe

In [45]:

threads = []
layout = [ 
     [sg.FilesBrowse(initial_folder="/home/joe",font="CENTAUR 15",file_types=[("CSV Files","*.csv")],enable_events=True,key='-FILES-')],
     [sg.Text("Column String Analysis")],
     [sg.Button('Quit')],
     [sg.Multiline(default_text="Summary\n",key="-PINFO-",font="CENTAUR 10",size=[70,5])],
    ]
# Create the Window
sg.theme('Lightblue')
window = sg.Window('Output', layout,finalize=True,resizable=True)
window.TKroot.focus_set()

#window2.move(window.current_location()[0]+600, window.current_location()[1])

while True:
    try:
        event, values = window.read()
        print(event)
        print("V ",values)
        print("D ",values["-FILES-"])

    #    window, event, values = sg.read_all_windows()
        if event == sg.WIN_CLOSED or event == 'Quit':
            window.close()
            break
        elif event == "-FILES-":
            file=values["-FILES-"]
            string=f"Processed File: {file}"
            df=pd.read_csv(file)
            window["-PINFO-"].update(string)
            thread  = threading.Thread(target=analyzeDfGui, 
                       args=(df,"",window,file))
            ntrds = len(threads)
            thread.start()
            thread.join()
    #                analyzeDfGui(df,"",window,file)
    except Exception as e:
        print(e)

-FILES-
V  {'-FILES-': '/home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv', '-PINFO-': 'Summary'}
D  /home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv
C  Zip
5676.0 815269529.0 4038147.9563106797 56796882.696899645

Exception in thread Thread-11 (analyzeDfGui):
Traceback (most recent call last):
  File "/usr/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "/tmp/ipykernel_1336/2470374957.py", line 437, in analyzeDfGui
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9618, in __init__
    self.Finalize()
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10304, in finalize
    self.Read(timeout=1)
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10079, in read
    results = self._read(timeout=timeout, timeout_key=timeout_key)
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 10150, in _read
    self._Show()
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 9890, in _Show
    StartupTK(self)
  File "/home/joe/.local/share/virtualenvs/Logs-zCJIqy3m/lib/python3.10/site-packages/PySimpleGUI/PySimpleGUI.py", line 16824, in StartupTK
    root = tk.Toplevel(class_=window.Title)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2650, in __init__
    BaseWidget.__init__(self, master, 'toplevel', cnf, {}, extra)
  File "/usr/lib/python3.10/tkinter/__init__.py", line 2601, in __init__
    self.tk.call(
RuntimeError: main thread is not in main loop

Quit
V  {'-FILES-': '/home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv', '-PINFO-': 'Processed File: /home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv'}
D  /home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv

In [21]:
analyzeDfGui(recRetLicOrig,"")

LOOKIE WHAT I FOUND datetime64[ns]
C  ZIP
10281.0 99354.0 80414.60251046024 6037.131553988345
-FILES-
V  {'-FILES-': '/home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv', '-PINFO-': 'Summary', '-TABLE-': [], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
Quit
V  {'-FILES-': '/home/joe/bic_etl/cdor/regulations_liquor/data_source/recentlyApproved_CIM.csv', '-PINFO-': 'Summary', '-TABLE-': [], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D

In [7]:
analyzeDfGui(recRetLicCIM,"")

C  Zip
10281.0 99354.0 80414.60251046024 6037.131553988345
-TABLE-Click
V  {'-PINFO-': 'Summary', '-TABLE-': [], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
COL  Location 1
STT  Column
Location Column
local variable 'tmp' referenced before assignment
bad bad
-TABLE-
V  {'-PINFO-': 'Summary', '-TABLE-': [6], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
-TABLE-Click
V  {'-PINFO-': 'Summary', '-TABLE-': [6], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
COL  Location 2
STT  digits
Location digits
ID COL
Close {'-TABLE2-': [4], '-TABLE3-': []}
-TABLE-
V  {'-PINFO-': 'Summary', '-TABLE-': [6], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
-TABLE-Click
V  {'-PINFO-': 'Summary', '-TABLE-': [6], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
COL  Street Address 1
STT  Column
Street Address Column
local variable 'tmp' referenced before assignment
bad bad
-TABLE-
V  {'-PINFO-': 'Summary', '-TABLE-': [8], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
-TABLE-Click
V  {'-PINFO-': 'Summary', '-TABLE-': [8], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
COL  Street Address 2
STT  digits
Street Address digits
ID COL
Close {'-TABLE2-': [], '-TABLE3-': []}
-TABLE-
V  {'-PINFO-': 'Summary', '-TABLE-': [8], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D
Quit
V  {'-PINFO-': 'Summary', '-TABLE-': [8], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D

In [10]:
analyzeDfGui(recRetLicConv,"")

C  Zip
10281.0 99354.0 80414.60251046024 6037.131553988345
Quit
V  {'-PINFO-': 'Summary', '-TABLE-': [], '-TABLEN-': [], '-CONVDATE-': '', '-DATEFORM-': '', '-TABLED-': []}
D

In [ ]:
recRetLicCIM.dtypes

In [ ]:
x = recRetLicCIM.copy()
x["Issue Date"]=pd.to_datetime(recRetLicCIM["Issue Date"], format="%m/%d/%Y")

In [ ]:
inventoryYrMoDy(x,"Issue Date")

In [ ]:
head_YrMo

## Recently Expired or Surrendered Liquor Licenses

In [23]:
df = pd.read_csv("/home/joe/bic_etl/cdor/regulations_liquor/data_transformed/recentlyExpired.csv")

In [28]:
dfC = pd.read_csv("https://data.colorado.gov/api/views/pwjb-9dd5/rows.csv?date=20231113&accessType=DOWNLOAD")

In [24]:
df.columns

Index(['companyName', 'doingBusinessAs', 'licenseType', 'licenseNumber',
       'licenseStatus', 'expirationDate', 'street', 'city', 'state', 'zip'],
      dtype='object')

In [25]:
df.isna().sum()

companyName        11
doingBusinessAs     0
licenseType         0
licenseNumber       0
licenseStatus       0
expirationDate      0
street              0
city                0
state               0
zip                 0
dtype: int64

In [30]:
dfC.loc[dfC["zip"].astype(str).str.len() > 5]

Empty DataFrame
Columns: [companyName, doingBusinessAs, licenseType, licenseNumber, licenseStatus, expirationDate, street, city, state, zip]
Index: []

In [22]:
df.shape

(345, 10)

In [89]:
df9 = pd.read_excel("/home/joe/bic_etl/cdor/regulations_liquor/data_source/Recently_Expired_and_Surrendered _Liquor_Licenses_9.7.2023.xlsx",engine="openpyxl")
df10 = pd.read_excel("/home/joe/bic_etl/cdor/regulations_liquor/data_source/Recently_Expired_and_Surrendered _Liquor_Licenses_10.4.2023.xlsx",engine="openpyxl")
df11 = pd.read_excel("/home/joe/bic_etl/cdor/regulations_liquor/data_source/Recently_Expired_and_Surrendered _Liquor_Licenses_11.3.2023.xlsx",engine="openpyxl")

In [90]:
df11.head()

,Company Name,DBA,License Type,License #,License Status,expiration_date,Street,City,State,Zip
0,GUERECA JOSE LUIS C,LA PASADITA INN MEXICAN RESTAURANT,Hotel & Restaurant (city),23-70031-0000,Expired,2023-10-01,1959 PARK AVE A,Denver,CO,802211059.0
1,CARL'S TAVERN LLC,CARL'S TAVERN,Hotel & Restaurant (city),03-08413,Expired,2023-10-03,700 YAMPA STREET #103A,Steamboat Springs,CO,80487.0
2,SIZZLING WINGS LLC,WINGSTOP #740,Hotel & Restaurant (city),03-08419,Expired,2023-10-02,1057 SOUTH WADSWORTH BOULEVARD #80,Lakewood,CO,80226.0
3,DN/OPTIMAL/TRUGOY DEN LLC,DENVER CENTRAL MARKET,Hotel & Restaurant (city),03-10651,Expired,2023-10-03,8800 FREDERICO PENA BLVD - DIA CONCOURSE A - A...,Denver,CO,80249.0
4,JEFFERY LEE PLUMMER,GRAND VIEW MOUNTAIN LODGE,Hotel & Restaurant (city),03-12215,Expired,2023-10-02,725 GRAND AVENUE,Grand Lake,CO,80447.0

In [91]:
df = pd.concat([df9,df10])

In [92]:
df.head()

,Company Name,DBA,License Type,License #,License Status,expiration_date,Street,City,State,Zip
0,CASTANON ENTERPRISES INC & 7-ELEVEN INC,7-ELEVEN STORE 27620A,Fermented Malt Beverage and Wine (city),42-94661-0000,Expired,2023-08-04,303 NORTH SANTA FE DRIVE,Denver,CO,80223.0
1,ADAMS CITY LIQUOR INC,CORK AND KEG LIQUORS,Liquor Store (city),42-38835-0000,Expired,2023-08-02,6935 LOWELL BOULEVARD,Westminster,CO,800302654.0
2,MALU INC,SINGER'S LIQUOR,Liquor Store (city),03-14799,Expired,2023-08-04,3649 WEST 44TH AVENUE,Denver,CO,80211.0
3,ELLA BLISS BEAUTY BAR LLC,ELLA BLISS BEAUTY BAR,Beer & Wine (city),03-01720,Expired,2023-08-07,8575 EAST ARAPAHOE ROAD SUITE N,Greenwood Village,CO,80112.0
4,JORGE RAMIREZ SANTOS,JESUS MEXICAN TAQUERIA,Beer & Wine (city),03-06333,Expired,2023-08-01,1710 SOUTH BUCKLEY ROAD #4,Aurora,CO,80017.0

In [93]:
df.tail()

,Company Name,DBA,License Type,License #,License Status,expiration_date,Street,City,State,Zip
108,NaN,2023 PALISADE SUNDAY FARMERS MARKET,Festival Permit,03-19313,Expired,2023-09-03,"DOWNTOWN PALISADE, THIRD AND MAIN STREET",Palisade,CO,81526.0
109,NaN,2023 PALISADE SUNDAY FARMERS MARKET,Festival Permit,03-19314,Expired,2023-09-17,"DOWNTOWN PALISADE, THIRD AND MAIN STREET",Palisade,CO,81526.0
110,NaN,BULL & BUSH LTD,Takeout & Delivery Permit,11-57114-0000,Expired,2023-09-03,4700 EAST CHERRY CREEK DRIVE SOUTH,Glendale,CO,80246.0
111,NaN,"GRANITE BUILDING BAR, LLC",Takeout & Delivery Permit,03-12667,Expired,2023-09-03,1460 LARIMER STREET,Denver,CO,80202.0
112,1,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [94]:
df.shape

(264, 10)

In [95]:
df.dropna(axis=0,how="all",subset=["DBA","License Type","License #"],inplace=True)

In [96]:
df.shape

(262, 10)

In [97]:
df.isna().sum()

Company Name       8
DBA                0
License Type       0
License #          0
License Status     0
expiration_date    0
Street             0
City               0
State              0
Zip                0
dtype: int64

In [98]:
import json
file="/home/joe/bic_etl/cdor/regulations_liquor/defs/pwjb-9dd5_src_trns_xrefs.json"
fin = open(file,"r")
a = json.load(fin)
xrefs={}
for k,v in a["data"].items():
    xrefs[k]=v["xref"]

In [99]:
columns = []
for col in df.columns:
    if col in xrefs:
        columns.append(xrefs[col])
    else:
        print("CRAP ",col)
df.columns = columns

In [100]:
df.columns

Index(['companyName', 'doingBusinessAs', 'licenseType', 'licenseNumber',
       'licenseStatus', 'expirationDate', 'street', 'city', 'state', 'zip'],
      dtype='object')

In [101]:
df["zip"] = df["zip"].astype(str).str[0:5]

In [102]:
df.to_csv("expiredLicenses.csv",index=False)

In [ ]:
!more expiredLicenses.csv

companyName,doingBusinessAs,licenseType,licenseNumber,licenseStatus,expirationDa
te,street,city,state,zip
CASTANON ENTERPRISES INC & 7-ELEVEN INC,7-ELEVEN STORE 27620A,Fermented Malt Bev
erage and Wine (city),42-94661-0000,Expired,2023-08-04,303 NORTH SANTA FE DRIVE,
Denver,CO,80223
ADAMS CITY LIQUOR INC,CORK AND KEG LIQUORS,Liquor Store (city),42-38835-0000,Exp
ired,2023-08-02,6935 LOWELL BOULEVARD,Westminster,CO,80030
MALU INC,SINGER'S LIQUOR,Liquor Store (city),03-14799,Expired,2023-08-04,3649 WE
ST 44TH AVENUE,Denver,CO,80211
ELLA BLISS BEAUTY BAR LLC,ELLA BLISS BEAUTY BAR,Beer & Wine (city),03-01720,Expi
red,2023-08-07,8575 EAST ARAPAHOE ROAD SUITE N,Greenwood Village,CO,80112
JORGE RAMIREZ SANTOS,JESUS MEXICAN TAQUERIA,Beer & Wine (city),03-06333,Expired,
2023-08-01,1710 SOUTH BUCKLEY ROAD #4,Aurora,CO,80017
SALSA'S MEXICAN RESTAURANT,SALSA'S MEXICAN RESTAURANT,Hotel & Restaurant (city),
02-55098-0000,Expired,2023-08-03,7630 W 44TH AVE,Wheat Ridge,CO,80033
OLDE TYMERS CAFE INC,OLDE TYMERS CAFE,Hotel & Restaurant (city),13-14092-0000,Ex
pired,2023-08-06,1000 MAIN AVE,Durango,CO,81301
CHIPOTLE MEXICAN GRILL INC,CHIPOTLE MEXICAN GRILL,Hotel & Restaurant (city),24-7
1530-0041,Expired,2023-08-06,649 S COLLEGE AVENUE,Fort Collins,CO,80525
RCM FOOD CONCEPTS LLC,LIL RICCIS,Hotel & Restaurant (city),42-82409-0000,Expired
,2023-08-02,5322 DTC BLVD STE 100,Greenwood Village,CO,80111
YAZOO BARBEQUE INC,YAZOO BBQ COMPANY,Hotel & Restaurant (city),03-01751,Expired,
2023-08-01,2150 BROADWAY,Denver,CO,80205
--More--(4%)

In [54]:
df["zip"].value_counts()

zip
80302.0    8
81526.0    6
80226.0    6
80501.0    6
80442.0    5
          ..
81413.0    1
80808.0    1
80466.0    1
80120.0    1
80524.0    1
Name: count, Length: 147, dtype: int64

In [88]:
df.columns

Index(['Company Name', 'DBA', 'License Type', 'License #', 'License Status',
       'expiration_date', 'Street', 'City', 'State', 'Zip'],
      dtype='object')

In [ ]:
for x in df["zip"].value_counts().to_dict():
    print(x)

In [76]:
min(df["zip"].astype(str).str.len())

5

In [70]:
df11["Zip"]

0     802211059.0
1         80487.0
2         80226.0
3         80249.0
4         80447.0
         ...
79        80015.0
80        80920.0
81        80216.0
82        81435.0
83            NaN
Name: Zip, Length: 84, dtype: float64

In [87]:
df.columns

Index(['Company Name', 'DBA', 'License Type', 'License #', 'License Status',
       'expiration_date', 'Street', 'City', 'State', 'Zip'],
      dtype='object')