In [2]:
import pandas as pd

In [7]:
fin1 = open("/home/joe/bic_etl/cdos/business/business/data_source/business_entities.tsv","rb")

linesOrg = fin1.readlines()
fin1.close()

#fin2 = open("business_entities-new.csv")
fin2 = open("/home/joe/bic_etl/cdos/business/business/data_transformed/business_entities.tsv")
linesTrn = fin2.readlines()
fin2.close()

In [8]:
linesTrn[1]

'"20011001058"\t"DODGETON CREEK INN, LLC"\t"137 CUCHARA AVE EAST"\t\t"Cuchara"\t"CO"\t"81055"\t"US"\t\t\t\t\t\t\t"Good Standing"\t"CO"\t"DLLC"\t"MICHAEL"\t"R."\t"MOORE"\t\t\t"137 CUCHARA AVE EAST"\t""\t"Cuchara"\t"CO"\t"81055"\t"US"\t\t\t\t\t\t\t"01/03/2001"\n'

In [9]:
histOrg={}
histTrn={}

for mm,line in enumerate(linesOrg[1:]):
    line2=linesTrn[mm+1]
  #  print(len(line),len(line2))
    if mm%100000 == 0:
        print("Line ",mm)
    for nn,c in enumerate(line[:-2]):
        c2 = line2[nn:nn+1]
        c2=ord(c2)
        if c2 not in histTrn:
            histTrn[c2]=0
        histTrn[c2]+=1
        
        if c not in histOrg:
            histOrg[c]=0
        histOrg[c]+=1
   #     print(c,ord(line2[nn:nn+1]),line2[nn:nn+1],type(c),type(line2[nn:nn+1]))
        if c != ord(line2[nn:nn+1]):
             print(mm,nn,c,line2[nn:nn+1],ord(line2[nn:nn+1]),c ==ord(line2[nn:nn+1]))

Line  0
Line  100000
Line  200000
Line  300000
Line  400000
Line  500000
Line  600000
Line  700000
Line  800000
Line  900000
Line  1000000
Line  1100000
Line  1200000
Line  1300000
Line  1400000
Line  1500000
Line  1600000
Line  1700000
Line  1800000
Line  1900000
Line  2000000
Line  2100000
Line  2200000
Line  2300000
Line  2400000
Line  2500000
Line  2600000

In [57]:

def getAsciiCodes():
    codesdf = pd.read_excel("/home/joe/Python/ascii-codes.xlsx",engine='openpyxl')
    asciiCodes={}
    for index,row in codesdf.iterrows():
        asciiCodes[row['DEC']] = {}
        asciiCodes[row['DEC']]['symbol'] = row['Symbol']
        asciiCodes[row['DEC']]['desc'] = row['Description']
    return asciiCodes

asciiCodes=getAsciiCodes()
for val,count in sorted(histTrn.items()):
    print(val,count,asciiCodes[val]['desc'])

9 90000927 Horizontal Tab
32 37081950 Space
33 2696 Exclamation mark
34 117617886 Double quotes (or speech marks)
35 317752 Number sign
36 501 Dollar
37 1225 Per cent sign
38 178910 Ampersand
39 93030 Single quote
40 8497 Open parenthesis (or open bracket)
41 8406 Close parenthesis (or close bracket)
42 895 Asterisk
43 3272 Plus
44 4636324 Comma
45 544916 Hyphen-minus
46 2706753 Period, dot or full stop
47 5354481 Slash or divide
48 27813549 Zero
49 22320604 One
50 20764815 Two
51 8771445 Three
52 7231265 Four
53 7339503 Five
54 6310791 Six
55 5813370 Seven
56 11626077 Eight
57 6830678 Nine
58 9643 Colon
59 926 Semicolon
60 49 Less than (or open angled bracket)
61 90 Equals
62 2014 Greater than (or close angled bracket)
63 328 Question mark
64 1283 At sign
65 6437043 Uppercase A
66 3003153 Uppercase B
67 18541312 Uppercase C
68 9685176 Uppercase D
69 5920748 Uppercase E
70 1620798 Uppercase F
71 2910660 Uppercase G
72 1849575 Uppercase H
73 3505809 Uppercase I
74 1298773 Uppercase J
75 871277 Uppercase K
76 11365508 Uppercase L
77 2594811 Uppercase M
78 4271075 Uppercase N
79 12393209 Uppercase O
80 3674923 Uppercase P
81 105452 Uppercase Q
82 5045964 Uppercase R
83 15365251 Uppercase S
84 3780417 Uppercase T
85 7831158 Uppercase U
86 1683198 Uppercase V
87 2096187 Uppercase W
88 237424 Uppercase X
89 725068 Uppercase Y
90 189272 Uppercase Z
91 284 Opening bracket
92 190 Backslash
93 250 Closing bracket
94 81 Caret - circumflex
95 3441 Underscore
96 1029 Grave accent
97 14621945 Lowercase a
98 1525830 Lowercase b
99 3597234 Lowercase c
100 9117205 Lowercase d
101 24996833 Lowercase e
102 765769 Lowercase f
103 4120266 Lowercase g
104 3620605 Lowercase h
105 14860347 Lowercase i
106 110072 Lowercase j
107 1621955 Lowercase k
108 12582238 Lowercase l
109 2743605 Lowercase m
110 19132422 Lowercase n
111 17145034 Lowercase o
112 2525804 Lowercase p
113 1807841 Lowercase q
114 15299319 Lowercase r
115 9126101 Lowercase s
116 15753106 Lowercase t
117 7000986 Lowercase u
118 4888288 Lowercase v
119 1649757 Lowercase w
120 649353 Lowercase x
121 3708571 Lowercase y
122 267960 Lowercase z
123 29 Opening brace
124 829 Vertical bar
125 24 Closing brace
126 221 Equivalency sign - tilde
127 4 Delete
160 4 Non-breaking space
189 2 Fraction one half
197 1 Latin capital letter A with ring above
225 1 Latin small letter a with acute
233 1 Latin small letter e with acute
246 1 Latin small letter o with diaeresis

In [61]:
df=pd.read_csv("Business_Entities_in_Colorado_20240423-CIM.csv")

In [62]:
df.shape

(2644909, 35)

In [3]:
dfN=pd.read_csv("/home/joe/bic_etl/cdos/business/business/data_transformed/business_entities.tsv",delimiter="\t",encoding="latin")

/home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/IPython/core/interactiveshell.py:3072: DtypeWarning: Columns (29) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

In [4]:
dfN.head()

,entityId,entityName,principalAddress1,principalAddress2,principalCity,principalState,principalZipCode,principalCountry,mailingAddress1,mailingAddress2,...,agentPrincipalState,agentPrincipalZipCode,agentPrincipalCountry,agentMailingAddress1,agentMailingAddress2,agentMailingCity,agentMailingState,agentMailingZipCode,agentMailingCountry,entityFormDate
0,20011001058,"DODGETON CREEK INN, LLC",137 CUCHARA AVE EAST,NaN,Cuchara,CO,81055,US,NaN,NaN,...,CO,81055,US,NaN,NaN,NaN,NaN,NaN,NaN,01/03/2001
1,20001243352,"THE MAIN EVENT MARKETING & PROMOTIONS, INC",1455 Manitou Ave,NaN,Steamboat Springs,CO,80487,US,PO Box 771869,NaN,...,CO,80487,US,PO Box 771869,NaN,Steamboat Springs,CO,80477,US,12/13/2000
2,19961076960,"HAL-MAR INVESTMENTS, LLC",601 N. PERRY STREET,NaN,DENVER,CO,80204,US,NaN,NaN,...,CO,80204,US,3127 W. Tanforan Dr,NaN,Englewood,CO,80110,US,06/07/1996
3,20001243280,"NUNET SOLUTIONS, INC.",7847 Jared Way,NaN,Littleton,CO,80125,US,NaN,NaN,...,CO,80125,US,NaN,NaN,NaN,NaN,NaN,NaN,12/13/2000
4,20051121021,"Sundog Creative Carpentry, Delinquent May 1, 2006",0876 Six Lazy K Road,NaN,New Castle,CO,81647,US,NaN,NaN,...,CO,81647,US,NaN,NaN,NaN,NaN,NaN,NaN,03/22/2005

In [67]:
df.head()

,entityid,entityname,principaladdress1,principaladdress2,principalcity,principalstate,principalzipcode,principalcountry,mailingaddress1,mailingaddress2,...,agentprincipalstate,agentprincipalzipcode,agentprincipalcountry,agentmailingaddress1,agentmailingaddress2,agentmailingcity,agentmailingstate,agentmailingzipcode,agentmailingcountry,entityformdate
0,18861217679,"DENVER UNION CORPROATION, Dissolved January 17...",1512 LARIMER STREET #760,NaN,Denver,CO,80202,NaN,NaN,NaN,...,CO,80202,US,NaN,NaN,NaN,NaN,NaN,NaN,03/29/1886
1,19871070272,INVESTORS LIFE INSURANCE COMPANY OF NORTH AMERICA,300 W 11th St,NaN,Kansas City,MO,64105,US,NaN,NaN,...,CO,80112,US,NaN,NaN,NaN,NaN,NaN,NaN,02/03/1970
2,18911012261,"GRADEN MERCANTILE COMPANY (THE), Dissolved May...",777 Main Ave.,NaN,Durango,CO,801302,US,P.O. Box Dr F,NaN,...,CO,81301,US,NaN,NaN,NaN,NaN,NaN,NaN,07/01/1891
3,19871071733,PROTECTIVE LIFE AND ANNUITY INSURANCE COMPANY,2801 Highway 280 South,NaN,Birmingham,AL,35223,US,NaN,NaN,...,CO,80112,US,NaN,NaN,NaN,NaN,NaN,NaN,04/16/1979
4,19031090218,"A. CARBONE AND COMPANY, INC., Dissolved Decemb...",846 East Eighteenth Avenue,NaN,Denver,CO,80218,US,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03/31/1903

In [68]:
df.shape

(2644909, 35)

In [71]:
dfN.columns

Index(['Entity Id', 'Entity Name', 'Principal Address 1',
       'Principal Address 2', 'Principal City', 'Principal State',
       'Principal Zip', 'Principal Country', 'Mailing Address 1',
       'Mailing Address 2', 'Mailing City', 'Mailing State', 'Mailing Zip',
       'Mailing Country', 'Entity Status', 'Jurisdiction of Formation',
       'Entity Type', 'Agent First Name', 'Agent Middle Name',
       'Agent Last Name', 'Agent Suffix', 'Agent Organization Name',
       'Agent Principal Address 1', 'Agent Principal Address 2',
       'Agent Principal City', 'Agent Principal State', 'Agent Principal Zip',
       'Agent Principal Country', 'Agent Mailing Address 1',
       'Agent Mailing Address 2', 'Agent Mailing City', 'Agent Mailing State',
       'Agent Mailing Zip', 'Agent Mailing Country', 'Entity Form Date'],
      dtype='object')

In [87]:
display(dfN.loc[dfN["entityId"] == 19921059174,"entityName"])
display(df.loc[df["entityid"] == 19921059174,"entityname"])

63    VAIL CLUB 50""
Name: entityName, dtype: object

225259    VAIL CLUB 50
Name: entityname, dtype: object

In [81]:
df.columns

Index(['entityid', 'entityname', 'principaladdress1', 'principaladdress2',
       'principalcity', 'principalstate', 'principalzipcode',
       'principalcountry', 'mailingaddress1', 'mailingaddress2', 'mailingcity',
       'mailingstate', 'mailingzipcode', 'mailingcountry', 'entitystatus',
       'jurisdictonofformation', 'entitytype', 'agentfirstname',
       'agentmiddlename', 'agentlastname', 'agentsuffix',
       'agentorganizationname', 'agentprincipaladdress1',
       'agentprincipaladdress2', 'agentprincipalcity', 'agentprincipalstate',
       'agentprincipalzipcode', 'agentprincipalcountry',
       'agentmailingaddress1', 'agentmailingaddress2', 'agentmailingcity',
       'agentmailingstate', 'agentmailingzipcode', 'agentmailingcountry',
       'entityformdate'],
      dtype='object')