In [1]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None

In [2]:
df = pd.read_csv("Site_Analytics__Asset_Access_20240215.csv")

In [3]:
df.head()

,Timestamp,Value,Asset UID,User Segment,Access Type,Asset Name,Asset Type
0,04/08/2020 03:00:00 AM,1,2qdn-4jpz,anonymous,API read,2017 SP,filter
1,04/18/2021 12:00:00 PM,0,ffp9-emr5,anonymous,grid view,chapman well search,filter
2,09/21/2020 09:00:00 PM,1,rkmy-yymq,anonymous,grid view,CDOT Payroll Expenditures,dataset
3,04/18/2021 12:00:00 PM,0,pnnh-f9vq,anonymous,primer page view,CSAP School And District Summary Results 2008,dataset
4,09/21/2020 09:00:00 PM,1,ua3v-vcuh,anonymous,grid view,Fire Districts in Colorado,map

In [4]:
df["Access Type"].value_counts()

API read                     898386
primer page view             843356
grid view                    575042
download                     425019
visualization canvas view     37999
story view                    26565
Name: Access Type, dtype: int64

In [5]:
df.dtypes

Timestamp       object
Value            int64
Asset UID       object
User Segment    object
Access Type     object
Asset Name      object
Asset Type      object
dtype: object

In [6]:
df["Date"] = pd.to_datetime(df["Timestamp"],format="%m/%d/%Y %I:%M:%S %p")

In [7]:
df["Year"] = df["Date"].dt.year
df["Month"] = df["Date"].dt.month

In [8]:
df["Month"].value_counts()

4     280042
5     269008
2     250069
6     239444
3     230280
10    229967
11    227800
12    223797
8     221038
1     220731
9     213522
7     200669
Name: Month, dtype: int64

In [9]:
df.head()

,Timestamp,Value,Asset UID,User Segment,Access Type,Asset Name,Asset Type,Date,Year,Month
0,04/08/2020 03:00:00 AM,1,2qdn-4jpz,anonymous,API read,2017 SP,filter,2020-04-08 03:00:00,2020,4
1,04/18/2021 12:00:00 PM,0,ffp9-emr5,anonymous,grid view,chapman well search,filter,2021-04-18 12:00:00,2021,4
2,09/21/2020 09:00:00 PM,1,rkmy-yymq,anonymous,grid view,CDOT Payroll Expenditures,dataset,2020-09-21 21:00:00,2020,9
3,04/18/2021 12:00:00 PM,0,pnnh-f9vq,anonymous,primer page view,CSAP School And District Summary Results 2008,dataset,2021-04-18 12:00:00,2021,4
4,09/21/2020 09:00:00 PM,1,ua3v-vcuh,anonymous,grid view,Fire Districts in Colorado,map,2020-09-21 21:00:00,2020,9

In [10]:
hist={}
for index,row in df.iterrows():
    w4x4=row["Asset UID"]
    access=row["Access Type"]    
    name=row["Asset Name"]  
    assetType=row["Asset Type"]     
    year=row["Year"]        
    month=row["Month"]   
    
    if w4x4 not in hist:
        hist[w4x4]={}
    if access not in hist[w4x4]:
        hist[w4x4][access]={}
    if year not in hist[w4x4][access]:
        hist[w4x4][access][year]={}
    if month not in hist[w4x4][access][year]:
        hist[w4x4][access][year][month]= 0
        
    hist[w4x4][access][year][month]+=1

In [23]:
pd.DataFrame.from_dict(hist)

,2qdn-4jpz,ffp9-emr5,rkmy-yymq,pnnh-f9vq,ua3v-vcuh,a9rr-k8mu,vz77-kxck,4yw9-a5y6,853a-s2qz,nzmx-8tm6,...,ypms-4d9f,gi42-x3hb,6duj-g9ch,5ir2-ea6r,kn7c-pza7,39g3-ivpe,jgmd-xuyk,fv5d-rvkc,kwih-avzs,imfq-n268
API read,"{2020: {4: 66, 5: 30, 8: 12, 2: 12, 12: 1, 3: ...","{2020: {4: 16, 12: 7, 3: 3, 2: 2, 6: 2, 5: 4, ...","{2021: {4: 43, 3: 39, 2: 31, 5: 40, 1: 36, 10:...","{2020: {4: 50, 7: 31, 6: 31, 5: 35, 9: 36, 12:...","{2020: {4: 12, 5: 1}, 2021: {4: 4, 3: 2, 2: 2,...","{2020: {9: 715, 4: 119, 7: 146, 2: 251, 10: 63...","{2020: {7: 720, 9: 613, 8: 595, 3: 444, 6: 531...","{2020: {9: 1369, 7: 1488, 5: 1427, 4: 1440, 6:...","{2020: {4: 5, 5: 1}, 2021: {4: 4, 3: 2, 2: 2, ...","{2020: {9: 19, 4: 46, 7: 16, 5: 30, 6: 14, 3: ...",...,NaN,NaN,NaN,{2024: {1: 3}},{2024: {1: 3}},{2024: {1: 3}},NaN,NaN,NaN,NaN
primer page view,"{2021: {4: 15, 3: 12, 7: 1, 5: 15, 2: 3, 10: 1...","{2021: {3: 10, 4: 13, 10: 7, 2: 5, 1: 8, 11: 3...","{2021: {4: 43, 3: 48, 10: 11, 2: 26, 7: 12, 5:...","{2021: {4: 18, 7: 6, 3: 12, 10: 6, 2: 11, 1: 1...",NaN,"{2020: {9: 370, 7: 339, 8: 383, 10: 371, 12: 2...","{2021: {3: 79, 4: 101, 6: 73, 7: 37, 2: 67, 10...","{2021: {4: 144, 10: 69, 3: 122, 6: 166, 7: 67,...",NaN,NaN,...,"{2023: {12: 9}, 2024: {1: 12, 2: 3}}","{2023: {12: 8}, 2024: {1: 13, 2: 4}}","{2023: {12: 8}, 2024: {1: 10, 2: 3}}",{2024: {1: 1}},{2024: {1: 1}},{2024: {1: 1}},{2024: {1: 1}},{2024: {1: 4}},{2024: {1: 2}},{2024: {1: 3}}
grid view,"{2020: {6: 4, 3: 10, 4: 7, 2: 5, 5: 9, 8: 1, 1...","{2021: {4: 1, 10: 1, 6: 3, 1: 1}, 2020: {2: 5,...","{2020: {9: 102, 7: 98, 12: 147, 6: 23, 8: 205,...","{2020: {12: 2, 9: 2, 3: 1, 4: 3, 5: 1, 7: 1, 8...","{2020: {9: 139, 12: 124, 5: 100, 7: 135, 8: 16...","{2020: {9: 155, 8: 127, 7: 132, 5: 110, 2: 169...","{2020: {5: 14, 6: 20, 7: 20, 2: 11, 9: 23, 3: ...","{2021: {6: 19, 4: 42, 3: 18, 7: 24, 5: 27, 10:...","{2020: {9: 29, 4: 32, 7: 34, 5: 32, 2: 47, 3: ...","{2020: {7: 12, 6: 21, 12: 5, 3: 12, 4: 9, 2: 1...",...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
download,"{2020: {9: 1, 3: 3, 4: 2, 2: 1, 11: 1, 12: 5, ...","{2020: {7: 1, 6: 3, 4: 1, 3: 1, 5: 1, 8: 2, 9:...","{2021: {4: 15, 6: 19, 10: 17, 3: 5, 7: 19, 2: ...","{2021: {4: 12, 3: 3, 7: 1, 10: 4, 2: 5, 11: 6,...",NaN,"{2020: {9: 280, 4: 347, 7: 243, 5: 329, 6: 280...","{2021: {4: 17, 3: 11, 7: 10, 10: 20, 2: 18, 11...","{2020: {7: 14, 9: 10, 4: 13, 6: 10, 2: 5, 12: ...",NaN,"{2021: {6: 3, 4: 1, 3: 1, 8: 1, 10: 1, 1: 1, 5...",...,{2023: {12: 1}},"{2023: {12: 1}, 2024: {1: 1}}",{2023: {12: 1}},{2024: {1: 1}},NaN,NaN,NaN,NaN,NaN,NaN
visualization canvas view,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
story view,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
#hist[w4x4][access][year][month]+=1    
datasets = []
access= []
years = []
months = []
counts = []

for w4x4,v1 in hist.items():
     for acc,v2 in v1.items():
         for year,v3 in v2.items():
            for month,count in v3.items():
                datasets.append(w4x4)
                access.append(acc)
                years.append(year)
                months.append(month)
                counts.append(count)

In [14]:
stats=pd.DataFrame({
    "4x4":datasets,
    "access":access,
    "year":years,
    "month":months,
    "count":counts
})

In [15]:
stats.head()

         4x4    access  year  month  count
0  2qdn-4jpz  API read  2020      4     66
1  2qdn-4jpz  API read  2020      5     30
2  2qdn-4jpz  API read  2020      8     12
3  2qdn-4jpz  API read  2020      2     12
4  2qdn-4jpz  API read  2020     12      1

In [39]:
stats.loc[(stats['4x4'] == '3qtu-edua') & (stats['year'] > 2022)].head(100)

             4x4            access  year  month  count
87636  3qtu-edua  primer page view  2023      6     63
87637  3qtu-edua  primer page view  2023      1     38
87638  3qtu-edua  primer page view  2023      2     43
87639  3qtu-edua  primer page view  2023      3     54
87640  3qtu-edua  primer page view  2023      4     56
87641  3qtu-edua  primer page view  2023      5     59
87642  3qtu-edua  primer page view  2023      7     52
87643  3qtu-edua  primer page view  2023      8     41
87644  3qtu-edua  primer page view  2023      9     30
87645  3qtu-edua  primer page view  2023     10     42
87646  3qtu-edua  primer page view  2023     11     40
87647  3qtu-edua  primer page view  2023     12     27
87648  3qtu-edua  primer page view  2024      1     36
87649  3qtu-edua  primer page view  2024      2     29
87685  3qtu-edua          API read  2023      6     36
87686  3qtu-edua          API read  2023      1      8
87687  3qtu-edua          API read  2023      2      7
87688  3qtu-edua          API read  2023      3     24
87689  3qtu-edua          API read  2023      4     16
87690  3qtu-edua          API read  2023      5     30
87691  3qtu-edua          API read  2023      7     18
87692  3qtu-edua          API read  2023      8     11
87693  3qtu-edua          API read  2023      9     28
87694  3qtu-edua          API read  2023     10      9
87695  3qtu-edua          API read  2023     11     10
87696  3qtu-edua          API read  2023     12      7
87697  3qtu-edua          API read  2024      1      6
87698  3qtu-edua          API read  2024      2      5
87734  3qtu-edua          download  2023      6     21
87735  3qtu-edua          download  2023      1     23
87736  3qtu-edua          download  2023      2     29
87737  3qtu-edua          download  2023      3     27
87738  3qtu-edua          download  2023      4     21
87739  3qtu-edua          download  2023      5     32
87740  3qtu-edua          download  2023      7     17
87741  3qtu-edua          download  2023      8     24
87742  3qtu-edua          download  2023      9     20
87743  3qtu-edua          download  2023     10     19
87744  3qtu-edua          download  2023     11     21
87745  3qtu-edua          download  2023     12     14
87746  3qtu-edua          download  2024      1      5
87747  3qtu-edua          download  2024      2      7
87783  3qtu-edua         grid view  2023      6     11
87784  3qtu-edua         grid view  2023      1      4
87785  3qtu-edua         grid view  2023      2      3
87786  3qtu-edua         grid view  2023      3     13
87787  3qtu-edua         grid view  2023      4      7
87788  3qtu-edua         grid view  2023      5      8
87789  3qtu-edua         grid view  2023      7     18
87790  3qtu-edua         grid view  2023      8      7
87791  3qtu-edua         grid view  2023      9      8
87792  3qtu-edua         grid view  2023     10      3
87793  3qtu-edua         grid view  2023     11      3
87794  3qtu-edua         grid view  2023     12      1
87795  3qtu-edua         grid view  2024      2      1