In [1]:
import requests
import gspread
from oauth2client.service_account import ServiceAccountCredentials
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)

In [2]:
def getXrefs():
    '''Reads the Inventory google sheet and gets the datasets title and cross-refs it to the Socrata 4x4 id.  Also
    gets the fields by 4x4 dataset id and by the title'''
    scope = ['https://www.googleapis.com/auth/spreadsheets.readonly',
             "https://www.googleapis.com/auth/drive.file",
                  "https://www.googleapis.com/auth/drive"]

    creds = ServiceAccountCredentials.from_json_keyfile_name('../client_secret.json',
     scope)
    client = gspread.authorize(creds)

    gc = gspread.service_account("../client_secret.json")
    # for gg in gc.list_spreadsheet_files():
    #      print("GGGGG ",gg)
    # https://docs.google.com/spreadsheets/d/1WTaOglzbSsYiHhAGguGxHQXmAGmOhfFHkGkMLowxAOA/edit?usp=sharing
#    sheet = client.open('BIC Data Inventory and Metadata').worksheet(
#        'Maintenance_Framework')
    inv_sheet = client.open('BIC Data Inventory and Metadata').worksheet(
        'MetadataRepository')
    
    org_sheet = client.open('Copy of bic_metadata_updater').worksheet(
        'Sheet1')
    

    dfNew = pd.DataFrame(inv_sheet.get_all_records(head=3))
    dfOrg = pd.DataFrame(org_sheet.get_all_records(head=1))
    
    return dfNew,dfOrg
   
dfN,dfO = getXrefs()

In [3]:
o = dfO["id"].values.tolist()
n = set(dfN["Socrata Link"].values.tolist())

In [4]:
print(len(o))
print(len(n))

400
400

In [2]:
#cimInv = pd.read_csv("https://data.colorado.gov/api/views/e7nm-tn2z/rows.csv?date=20231102&accessType=DOWNLOAD")

cimInv = pd.read_csv("https://data.colorado.gov/api/views/pb79-5bvp/rows.csv?date=20231103&accessType=DOWNLOAD")

HTTPError: HTTP Error 403: Forbidden

In [60]:
cimInv.shape

(2346, 119)

In [48]:
cimInv["id"].value_counts()

Series([], Name: count, dtype: int64)

In [6]:
cim = cimInv.loc[cimInv["Owner"] == "Colorado Information Marketplace"]

In [7]:
c = cim["U ID"].values.tolist()

In [8]:
count=0
miss=[]
for id in o:
    if id not in c:
       miss.append(id)

In [9]:
OnotInC = dfO.loc[dfO["id"].isin(miss)]

In [ ]:
for col in dfO.columns:
    print(col)

In [ ]:
display(OnotInC)

In [11]:
count=0
miss=[]
for id in c:
    if id not in o:
       miss.append(id)
CnotInO = cim.loc[cim["U ID"].isin(miss)]

In [12]:
CnotInO.shape

(59, 119)

In [13]:
display(CnotInO)

,URL,U ID,Public,Derived View,Parent UID,Domain,Type,Name,Description,Visits,Creation Date,Last Update Date (data),Category,Keywords,Downloads,Owner,Contact Email,License,Publication Stage,Published Version Name,Published Version UID,Routing & Approval,data_provided_by,Horizontal Coordinate System,Data Quality Certified,File Size at Recent Update,Sub-Agency,Update Method,Technical Contact and Phone,Expected Update Frequency,Horizontal Accuracy,Secondary Content Provider,Total Records at Initial Publish,Technical Documentation,Date of Inital Publish,"Field Names, comma delimited",Granularity,Date of Initial Dataset Creation,Collection Mode,Agency Data Series Page,Agency,Data Dictionary,Publishing Department,Stewardship Plan,Newest Record in Dataset,Bounding Coordinates,Total Columns at Recent Update,High Value Dataset,api_endpoint,Long Description,Agency Program Page,Source,Suggested by Public,Date Released,Last Updated,Data Source,Date Updated,Oldest Record in Dataset,Geographic Coverage,Positional Accuracy,Data Quality Certification,Citation,Unit of Analysis,Data Governance Plan,Total Records at Recent Update,Additional Metadata,Business Contact and Phone,Data Collection Instrument,Time Period,Progress,Local Government Entity,Update Schedule,Frequency of Update,Date of Most Recent Update,Content type,Collection Method,Frequency,Date Created,Status,Applicable Information Quality Guideline Designation,source_link,Purpose,capabilities,Primary Content Provider,canScaleSymbols,supportedQueryFormats,maxScale,hasLabels,htmlPopupType,Privacy and Confidentiality,copyrightText,geometryType,hasAttachments,canModifyLayer,FGDC Compliance (Geospatial Only),allowOthersToQuery,supportsStatistics,maxRecordCount,defaultVisibility,id,Secondary Content Editor,Spatial Reference wkid,displayField,supportsAdvancedQueries,Currentness Reference,minScale,currentVersion,useStandardizedQueries,owner_uid,provenance,Coordinate System Disclaimer,Web Display Coordinate System,Single Row,Related Datasets,API Query URL,Update Frequency,Null Meaning,Update Type,Source Update Schedule
29,https://data.colorado.gov/d/ikpk-kpy4,ikpk-kpy4,False,False,NaN,data.colorado.gov,dataset,Conditions,test,6,09/15/2020 10:55:00 PM +0000,09/15/2020 10:59:00 PM +0000,NaN,NaN,0,Colorado Information Marketplace,NaN,NaN,published,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/ikpk-kpy4.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
31,https://data.colorado.gov/d/a26p-3wtg,a26p-3wtg,True,True,q2zb-n3df,data.colorado.gov,map,Vacant Commercial / Industial Parcels,"<DIV STYLE=""text-align:Left;""><DIV><DIV><P><SP...",4,09/08/2020 08:26:00 PM +0000,11/13/2020 03:21:00 PM +0000,NaN,NaN,0,Colorado Information Marketplace,NaN,NaN,published,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/a26p-3wtg.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
35,https://data.colorado.gov/d/q2zb-n3df,q2zb-n3df,True,False,NaN,data.colorado.gov,dataset,Vacant Commercial / Industial Parcels,"<DIV STYLE=""text-align:Left;""><DIV><DIV><P><SP...",7,09/08/2020 08:26:00 PM +0000,11/13/2020 03:21:00 PM +0000,NaN,NaN,11,Colorado Information Marketplace,NaN,NaN,published,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/q2zb-n3df.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
36,https://data.colorado.gov/d/t9v7-8tcq,t9v7-8tcq,False,False,NaN,data.colorado.gov,dataset,Scenic Byways,NaN,0,09/08/2020 08:00:00 PM +0000,09/08/2020 08:00:00 PM +0000,NaN,NaN,0,Colorado Information Marketplace,NaN,NaN,unpublished,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/t9v7-8tcq.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
37,https://data.colorado.gov/d/gg7c-x3g2,gg7c-x3g2,False,False,NaN,data.colorado.gov,dataset,Scenic Byways,NaN,0,09/08/2020 07:58:00 PM +0000,09/08/2020 07:58:00 PM +0000,NaN,NaN,0,Colorado Information Marketplace,NaN,NaN,unpublished,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/gg7c-x3g2.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
40,https://data.colorado.gov/d/weiy-j54d,weiy-j54d,False,False,NaN,data.colorado.gov,dataset,Scenic Byways,NaN,0,09/08/2020 08:00:00 PM +0000,09/08/2020 08:00:00 PM +0000,NaN,NaN,0,Colorado Information Marketplace,NaN,NaN,unpublished,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/weiy-j54d.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
50,https://data.colorado.gov/d/fd4d-3wz6,fd4d-3wz6,False,False,NaN,data.colorado.gov,dataset,Scenic Byways,NaN,2,09/08/2020 08:00:00 PM +0000,09/08/2020 08:00:00 PM +0000,NaN,NaN,0,Colorado Information Marketplace,NaN,NaN,unpublished,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/fd4d-3wz6.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
62,https://data.colorado.gov/d/cyih-477r,cyih-477r,True,False,NaN,data.colorado.gov,dataset,Boundaries for Denver Public Schools,Boundaries for Denver Public Schools,26,07/24/2020 05:04:00 PM +0000,07/24/2020 05:06:00 PM +0000,Education,"bic,gocodecolorado,education,dps,schools,denve...",6,Colorado Information Marketplace,NaN,Public Domain,published,NaN,NaN,NaN,DPS - Denver Public Schools,NaN,NaN,NaN,NaN,NaN,NaN,Manual - Annual,NaN,NaN,NaN,NaN,NaN,"oid,elem_num,mid_num,high_num,elem_name,mid_na...",NaN,DPS HAS BEEN MAINTAINING SPATIAL BOUNDARY DATA...,MANUAL,https://open-geo.dpsk12.org/geoserver/web/wick...,NaN,NaN,NaN,NaN,2019-2020,NaN,NaN,NaN,https://data.colorado.gov/resource/cyih-477r.json,Means of communication used by a Paid Solicito...,NaN,NaN,NaN,NaN,NaN,DPS GIS,NaN,2019-2020,City and County of Denver,NaN,NaN,DPS - Denver Public Schools,Vector polygon,NaN,NaN,NaN,MATTHEW BAKER,MANUAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPDATED ANNUALLY,NaN,NaN,NaN,NaN,https://www.dpsk12.org/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,Boundaries for Denver Public Schools including...,NaN,NaN,NaN,NaN,NaN,Annually
105,https://data.colorado.gov/d/ctsf-xjv9,ctsf-xjv9,False,False,NaN,data.colorado.gov,dataset,NaN,NaN,51,03/25/2020 10:09:00 PM +0000,07/24/2020 05:10:00 PM +0000,NaN,"bic,gocodecolorado,education,dps,schools,denve...",36,Colorado Information Marketplace,NaN,Public Domain,published,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Automated - annual,NaN,NaN,NaN,NaN,NaN,"oid,elem_num,mid_num,high_num,elem_name,mid_na...",NaN,DPS HAS BEEN MAINTAINING SPATIAL BOUNDARY DATA...,MANUAL,https://open-geo.dpsk12.org/geoserver/web/wick...,NaN,NaN,NaN,NaN,2019-2020,NaN,NaN,NaN,https://data.colorado.gov/resource/ctsf-xjv9.json,Means of communication used by a Paid Solicito...,https://www.dpsk12.org/,NaN,NaN,NaN,NaN,DPS GIS,NaN,2019-2020,City and County of Denver,NaN,NaN,NaN,Vector polygon,NaN,NaN,NaN,MATTHEW BAKER,MANUAL,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UPDATED ANNUALLY,NaN,NaN,NaN,NaN,https://www.dpsk12.org/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,Boundaries for Denver Public Schools including...,NaN,NaN,NaN,NaN,Automated - annual,Annually
111,https://data.colorado.gov/d/7r2u-yuai,7r2u-yuai,True,False,NaN,data.colorado.gov,href,Colorado COVID-19 Landing Page,NaN,178,03/19/2020 04:35:00 PM +0000,03/19/2020 04:35:00 PM +0000,COVID-19,"covid19,colorado,health,pandemic,data,coronavi...",0,Colorado Information Marketplace,NaN,NaN,published,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/7r2u-yuai.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
159,https://data.colorado.gov/d/8isw-835j,8isw-835j,True,False,NaN,data.colorado.gov,dataset,Development Projects in Grand Junction Colorad...,"2019 Development Projects in Grand Junction, C...",48,11/26/2019 06:16:00 PM +0000,11/26/2019 06:39:00 PM +0000,Business,"business,gocodecolorado,grand junction,grand,j...",25,Colorado Information Marketplace,NaN,Creative Commons 1.0 Universal (Public Domain ...,published,NaN,NaN,NaN,City of Grand Junction GIS,NaN,NaN,NaN,NaN,Manual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"objectid, casenumber, plannername, phone, case...",NaN,NaN,NaN,https://arcgis-app.gjcity.org/arcgis/rest/serv...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/8isw-835j.json,Details for 2019 Development projects in Grand...,http://www.gjcity.org/Maps/,NaN,NaN,NaN,NaN,City of Grand Junction GIS,NaN,NaN,Greater Grand Junciton,NaN,NaN,City of Grand Junction GIS,Vector Polygon Data,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Manual - Annual,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://arcgis-app.gjcity.org/Business%20Map%2...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,Development project details for 2019 projects ...,NaN,NaN,NaN,NaN,Manual - Annual,NaN
170,https://data.colorado.gov/d/gwwh-4sfc,gwwh-4sfc,True,True,7s5z-vewr,data.colorado.gov,filter,Professional and Occupational Licenses in Colo...,Professional and occupational license types in...,46,10/24/2019 03:30:00 PM +0000,11/13/2020 10:34:00 AM +0000,Business,"gocodecolorado,colorado,dora,department of reg...",20,Colorado Information Marketplace,NaN,Public Domain,published,NaN,NaN,NaN,DORA,NaN,NaN,NaN,NaN,Automated by Staging Server,NaN,Automated - daily,NaN,NaN,NaN,NaN,NaN,"lastname, firstname, middlename, suffix, entit...",NaN,NaN,License is applied for by the individual or bu...,https://www.colorado.gov/pacific/dora/dpo,NaN,NaN,NaN,Automated update via staging server,NaN,NaN,22.0,NaN,https://data.colorado.gov/resource/gwwh-4sfc.json,This data is updated nightly and is intended f...,https://www.colorado.gov/dora,NaN,NaN,NaN,NaN,eLicense Database Roster Download,NaN,NaN,State,NaN,NaN,DORA - Department of Regulatory Agencies,Tabular,NaN,NaN,NaN,NaN,Collection instruments include internet update...,NaN,NaN,NaN,Every day after midnight,NaN,NaN,NaN,Data is collected through internal system upda...,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,"Professional/occupational license holder name,...",Joinable to: Professional and Occupational Lic...,NaN,NaN,NaN,NaN,NaN
172,https://data.colorado.gov/d/ij88-jh64,ij88-jh64,False,True,7s5z-vewr,data.colorado.gov,filter,blank license first issue,"NOTE: Updates for this dataset and ""Licensed R...",1,10/22/2019 05:45:00 PM +0000,11/13/2020 10:34:00 AM +0000,Business,"gocodecolorado,colorado,dora,department of reg...",0,Colorado Information Marketplace,NaN,Public Domain,unpublished,NaN,NaN,NaN,DORA,NaN,NaN,NaN,NaN,Automated by Staging Server,NaN,Automated - daily,NaN,NaN,NaN,NaN,NaN,"lastname, firstname, middlename, suffix, entit...",NaN,NaN,License is applied for by the individual or bu...,https://www.colorado.gov/pacific/dora/dpo,NaN,NaN,NaN,Automated update via staging server,NaN,NaN,22.0,NaN,https://data.colorado.gov/resource/ij88-jh64.json,This data is updated nightly and is intended f...,https://www.colorado.gov/dora,NaN,NaN,NaN,NaN,eLicense Database Roster Download,NaN,NaN,State,NaN,NaN,DORA - Department of Regulatory Agencies,Tabular,NaN,NaN,NaN,NaN,Collection instruments include internet update...,NaN,NaN,NaN,Every day after midnight,NaN,NaN,NaN,Data is collected through internal system upda...,NaN,NaN,NaN,NaN,https://www.colorado.gov/dora,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,"Professional/occupational license holder name,...",Joinable to: Professional and Occupational Lic...,NaN,NaN,NaN,NaN,NaN
280,https://data.colorado.gov/d/5t88-fa3k,5t88-fa3k,False,False,NaN,data.colorado.gov,dataset,MilepostsTest,NaN,14,04/11/2019 05:59:00 PM +0000,04/11/2019 06:00:00 PM +0000,NaN,NaN,2,Colorado Information Marketplace,NaN,NaN,published,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/5t88-fa3k.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
282,https://data.colorado.gov/d/h43g-tpkm,h43g-tpkm,False,True,2f98-hukf,data.colorado.gov,map,Test Jan 2019,NaN,1,04/11/2019 05:20:00 PM +0000,04/11/2019 05:18:00 PM +0000,NaN,NaN,0,Colorado Information Marketplace,NaN,NaN,unpublished,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/h43g-tpkm.json,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
305,https://data.colorado.gov/d/dms8-ujea,dms8-ujea,True,True,aevh-apr2,data.colorado.gov,map,Census Tracts in Colorado 2017 Map,American Community Survey Census data includes...,45,02/19/2019 04:11:00 PM +0000,02/15/2019 12:39:00 AM +0000,Demographics,NaN,5,Colorado Information Marketplace,NaN,Public Domain,published,NaN,NaN,NaN,DOLA,NAD83/GCS_North_American_1987,NaN,NaN,NaN,NaN,NaN,Static,Census data is reliable as within the constrai...,NaN,1249,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,2017,TIGER line files,https://demography.dola.colorado.gov/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/dms8-ujea.json,Census Data is collected every 10 years by mai...,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,https://www.colorado.gov/pacific/dola,NaN,NaN,State,NaN,NaN,DOLA - Department of Local Affairs,Vector polygon,NaN,NaN,NaN,NaN,Surveys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The 2000 census marked the last year that the ...,NaN,NaN,NaN,NaN,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,"NOTE: To maintain source projection, select “E...",WGS84,Census tract demographics,NaN,NaN,NaN,NaN,NaN,NaN
306,https://data.colorado.gov/d/ssuw-z5kg,ssuw-z5kg,True,True,ty5m-9xub,data.colorado.gov,map,Census Block Groups in Colorado 2017 Map,American Community Survey Census data includes...,118,02/19/2019 04:08:00 PM +0000,02/14/2019 11:07:00 PM +0000,Demographics,NaN,5,Colorado Information Marketplace,NaN,Public Domain,published,NaN,NaN,NaN,DOLA,NAD83/GCS_North_American_1984,NaN,NaN,NaN,NaN,"Rob Kemp, robert.kemp@state.co.us",Static,Census data is reliable as within the constrai...,NaN,3532,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,2017,TIGER line files,https://demography.dola.colorado.gov/,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/resource/ssuw-z5kg.json,Census Data is collected every 10 years by mai...,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,State,NaN,NaN,DOLA - Department of Local Affairs,Vector Polygon,NaN,NaN,NaN,not public,Surveys,NaN,NaN,NaN,NaN,NaN,NaN,NaN,The 2000 census marked the last year that the ...,NaN,NaN,NaN,NaN,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,"NOTE: To maintain source projection, select “E...",WGS84,Census block group demographics,NaN,NaN,NaN,NaN,NaN,NaN
308,https://data.colorado.gov/d/imfq-n268,imfq-n268,False,False,NaN,data.colorado.gov,dataset,Firearm Transactions in Colorado,Monthly firearm sale approval and denails by t...,7,02/19/2019 03:25:00 PM +0000,02/19/2019 03:31:00 PM +0000,Public Safety,"bic,firearm,sale,transactions,colorado,gun,gun...",0,Colorado Information Marketplace,NaN,Public Domain,published,NaN,NaN,NaN,CDPS - Colorado Department of Public Safety,NaN,NaN,NaN,NaN,NaN,NaN,not published,NaN,NaN,732,NaN,NaN,"Month,Year,gunType,total_approvals,total_denia...",NaN,NaN,NaN,https://www.colorado.gov/pacific/cbi/previousy...,NaN,NaN,NaN,NaN,Dec-18,NaN,NaN,NaN,https://data.colorado.gov/resource/imfq-n268.json,Monthly stats on approvals and denials for dif...,https://www.colorado.gov/pacific/cbi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,State,NaN,NaN,CDPS - Colorado Department of Public Safety,Tabular,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://www.colorado.gov/pacific/cbi,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8cet-tw9x,official,NaN,NaN,Monthly stats on approvals and denials for dif...,NaN,NaN,NaN,NaN,not published,NaN

In [14]:
for col in CnotInO.columns:
    print(col)

URL
U ID
Public
Derived View
Parent UID
Domain
Type
Name
Description
Visits
Creation Date
Last Update Date (data)
Category
Keywords
Downloads
Owner
Contact Email
License
Publication Stage
Published Version Name
Published Version UID
Routing & Approval
data_provided_by
Horizontal Coordinate System
Data Quality Certified
File Size at Recent Update
Sub-Agency
Update Method
Technical Contact and Phone
Expected Update Frequency
Horizontal Accuracy
Secondary Content Provider
Total Records at Initial Publish
Technical Documentation
Date of Inital Publish
Field Names, comma delimited
Granularity
Date of Initial Dataset Creation
Collection Mode
Agency Data Series Page
Agency
Data Dictionary
Publishing Department
Stewardship Plan
Newest Record in Dataset
Bounding Coordinates
Total Columns at Recent Update
High Value Dataset
api_endpoint
Long Description
Agency Program Page
Source
Suggested by Public
Date Released
Last Updated
Data Source
Date Updated
Oldest Record in Dataset
Geographic Coverage
Positional Accuracy
Data Quality Certification
Citation
Unit of Analysis
Data Governance Plan
Total Records at Recent Update
Additional Metadata
Business Contact and Phone
Data Collection Instrument
Time Period
Progress
Local Government Entity
Update Schedule
Frequency of Update
Date of Most Recent Update
Content type
Collection Method
Frequency
Date Created
Status
Applicable Information Quality Guideline Designation
source_link
Purpose
capabilities
Primary Content Provider
canScaleSymbols
supportedQueryFormats
maxScale
hasLabels
htmlPopupType
Privacy and Confidentiality
copyrightText
geometryType
hasAttachments
canModifyLayer
FGDC Compliance (Geospatial Only)
allowOthersToQuery
supportsStatistics
maxRecordCount
defaultVisibility
id
Secondary Content Editor
Spatial Reference wkid
displayField
supportsAdvancedQueries
Currentness Reference
minScale
currentVersion
useStandardizedQueries
owner_uid
provenance
Coordinate System Disclaimer
Web Display Coordinate System
Single Row
Related Datasets
API Query URL
Update Frequency
Null Meaning
Update Type
Source Update Schedule

In [ ]:
for col in sorted(CnotInOP.columns):
   display("Column: ",col)
   display(CnotInOP[col].value_counts())
   display("-------------------------------------------")

In [21]:
CnotInOP = CnotInO.loc[CnotInO["Public"]]

In [30]:
display(CnotInOP[["Name","URL"]])

,Name,URL
31,Vacant Commercial / Industial Parcels,https://data.colorado.gov/d/a26p-3wtg
35,Vacant Commercial / Industial Parcels,https://data.colorado.gov/d/q2zb-n3df
62,Boundaries for Denver Public Schools,https://data.colorado.gov/d/cyih-477r
111,Colorado COVID-19 Landing Page,https://data.colorado.gov/d/7r2u-yuai
159,Development Projects in Grand Junction Colorad...,https://data.colorado.gov/d/8isw-835j
170,Professional and Occupational Licenses in Colo...,https://data.colorado.gov/d/gwwh-4sfc
305,Census Tracts in Colorado 2017 Map,https://data.colorado.gov/d/dms8-ujea
306,Census Block Groups in Colorado 2017 Map,https://data.colorado.gov/d/ssuw-z5kg
314,Census Places in Colorado 2017 Map,https://data.colorado.gov/d/ibr3-r5n3
322,Points of Interest in Denver - Map,https://data.colorado.gov/d/dqd2-3hbj
323,Census Counties in Colorado 2017 - Map,https://data.colorado.gov/d/kzrg-3rgm
324,Neighborhood Business Revitalization Corridors...,https://data.colorado.gov/d/yt78-xpzf
325,Tree Canopy Assesment Denver - Map,https://data.colorado.gov/d/mmq3-xrh7
326,General Improvement Districts in Denver,https://data.colorado.gov/d/ws2k-4zj6
327,Food Stores in Denver Map,https://data.colorado.gov/d/fkrf-c7qd
328,Business Improvement Districts in Denver Map,https://data.colorado.gov/d/pkue-zrfg
329,Tree Inventory of Denver - Map,https://data.colorado.gov/d/hzmx-2dfk
330,Body Art Licenses in Denver Map,https://data.colorado.gov/d/cu7f-czv4
333,Enterprise Zones Test Jan 2019,https://data.colorado.gov/d/2f98-hukf
353,Parcels in Denver Map Visualization,https://data.colorado.gov/d/pfi9-k7n2
361,Census in Colorado 2017 Map,https://data.colorado.gov/d/uman-zjh4
417,Highway Traffic Counts in Colorado 2016 Map,https://data.colorado.gov/d/w9zf-5neg
419,Highway Traffic Counts in Colorado 2017 Map,https://data.colorado.gov/d/25ry-d5r8
524,Active Nursing Licenses in Colorado,https://data.colorado.gov/d/gzth-nufs
539,Map of Recently Expired and Surrendered Liquor...,https://data.colorado.gov/d/x4sv-war6
540,Map of Recently Approved Liquor Licenses in Co...,https://data.colorado.gov/d/v328-h7vn
542,Map of Liquor Licenses in Colorado,https://data.colorado.gov/d/92n9-xx4r
576,Map of Sales Rooms in Colorado,https://data.colorado.gov/d/g7tq-rkfe
1369,Electricity Net Metering in Colorado,https://data.colorado.gov/d/y23n-tr7i
1371,Electricity Revenue in Colorado,https://data.colorado.gov/d/q6sk-tjm9
1373,Business Entities Overview,https://data.colorado.gov/view/pzzw-h8hs
1412,Electricity Revenue by Utility in Colorado,https://data.colorado.gov/d/gdh8-8pg4
1695,CDOT Real Time Data Feed (XML),https://data.colorado.gov/d/j3ch-zsvz
1708,County Parcels Land Tax and Land Use in Colora...,https://data.colorado.gov/d/jm2h-ex8p
1729,"Census API in United States 1980, 1990, 2000, ...",https://data.colorado.gov/d/fcij-msvv
1737,Colorado Daily Precipitation Reports,https://data.colorado.gov/view/awsg-mpkj
1761,Colorado Business Entities - duplicates to review,https://data.colorado.gov/d/4t7n-3thy
1970,Traffic Feeds in Colorado,https://data.colorado.gov/d/b9sn-ryu7

In [34]:
CnotInOP["Type"].value_counts()

Type
map         17
filter       6
href         5
dataset      4
map view     4
datalens     2
Name: count, dtype: int64

In [ ]:
display(CnotInOP[['Name','Update Method','Update Schedule','Expected Update Frequency','Visits']])

In [49]:
OnotInC["attribution"].value_counts()

attribution
DOLA                         14
NREL                          9
Denver County                 7
City and county of Denver     6
Adams County                  5
Clear Creek County            4
CDOT                          4
Eagle County                  4
Boulder County                3
Broomfield County             2
Garfield County               2
Jefferson County              2
NASA                          2
USCB                          2
CDA                           1
DPA                           1
DWR                           1
Mesa County                   1
La Plata County               1
Pitkin County                 1
El Paso County                1
Larimer County                1
Lake County                   1
US Census Bureau              1
EPA                           1
EnergizoCO                    1
IRS                           1
                              1
Name: count, dtype: int64

In [44]:
for col in OnotInC.columns:
    print(col)

id
name
description
category
tags
license
attribution
attributionLink
Citation
Agency Program Page
Agency Data Series Page
Data Source
Unit of Analysis
Granularity
Geographic Coverage
Collection Mode
Collection Methodology
Data Collection Instrument
Date of Initial Dataset Creation
Field Names, comma delimited
Oldest Record in Dataset
Newest Record in Dataset
Long Description
Single Row
Data Dictionary
Additional Metadata
Technical Documentation
Data Quality Certification
Applicable Information Quality Guideline Designation
Stewardship Plan
Collection Method
Horizontal Accuracy
Horizontal Coordinate System
Web Display Coordinate System
Coordinate System Disclaimer
Content Type
Update Schedule
Update Method
Update Type
Source Update Schedule
Total Records at Initial Publish

In [52]:
OnotInC.shape

(80, 41)

In [51]:
display(OnotInC[["id","name"]])

            id                                               name
0    rifs-n6ib  Transparency Online Project (TOPS) - State Gov...
4    ms6b-y4xc                   Farmers Markets in Colorado 2017
45   6ntv-x37b  Businesses Issued Outdoor Expansion Permits in...
155  bjhg-77mf                  Census Zip Codes in Colorado 2019
156  ucnv-vw74                  Census Zip Codes in Colorado 2020
158  tbmm-ubn9    Census Congressional Districts in Colorado 2019
159  q56w-zzzm    Census Congressional Districts in Colorado 2020
161  smjm-6h6g                            Census in Colorado 2019
162  ekih-pydt                            Census in Colorado 2020
164  spwe-6ca7               Census Block Groups in Colorado 2019
165  jwbw-xb7i               Census Block Groups in Colorado 2020
167  cj4m-96y8                     Census Tracts in Colorado 2019
168  7t53-5gfx                     Census Tracts in Colorado 2020
170  8j3i-rjn4                   Census Counties in Colorado 2019
171  rt7b-823p                   Census Counties in Colorado 2020
173  xpi4-stak                     Census Places in Colorado 2019
174  33q3-djk8                     Census Places in Colorado 2020
325  4yw9-a5y6       Current Surface Water Conditions in Colorado
338  mev7-qffb  Residence Characteristics in Clear Creek Count...
339  qifa-4jur  Commercial Locations Characteristics in Clear ...
340  sacq-tw7c   Condo Characteristics in Clear Creek County 2020
341  7tmk-3ibe    Land Characteristics in Clear Creek County 2020
342  9fte-yff6                  Fire Stations in Mesa County 2019
343  3ka2-m6zm         Open Space Trails in Jefferson County 2020
344  ceje-t3ek                 Fire Stations in Eagle County 2019
345  afm6-vyyp               Police Stations in Eagle County 2019
346  24hn-nv39                Fire Stations in Denver County 2019
347  y2yv-a2wp               Fire Stations in Boulder County 2019
348  b7zn-sry4                     Libraries in Adams County 2019
349  kr2r-j5ik                 Fire Stations in Adams County 2019
350  3j7e-ezpr               Police Stations in Adams County 2019
351  u9u9-cq2s                 Subdivisions in Pitkin County 2019
352  abdb-jtwc                Subdivisions in Larimer County 2019
353  mdbi-p4c8                         Zoning in Lake County 2020
354  t3k6-vndx               Subdivisions in La Plata County 2019
355  rcw7-6npp                    Zoning in Jefferson County 2019
356  nwd2-s3kd               Subdivisions in Garfield County 2019
357  d2cu-rhft                     Zoning in Garfield County 2019
358  42wt-sxkv                      Zoning in El Paso County 2019
359  6exr-8xkn                  Subdivisions in Eagle County 2019
360  wyy2-wvrc                        Zoning in Eagle County 2019
361  w2w7-ggyk             Subdivisions in Broomfield County 2019
362  8pmi-n437                   Zoning in Broomfield County 2019
363  t5eg-ziay                Subdivisions in Boulder County 2019
364  yvwz-kj9z                      Zoning in Boulder County 2019
365  eeb6-6s76                  Subdivisions in Adams County 2019
366  72dx-vrxk                        Zoning in Adams County 2019
367  ccz9-ggrb                   Road Attributes in Colorado 2021
368  an2q-gwrx                    Highway Curves in Colorado 2021
369  jr8i-33tp                    Highway Grades in Colorado 2021
370  cr6z-hn4e      Road HOV, Curves, and Grades in Colorado 2021
371  2sn7-naei              Colorado Toxic Release Inventory 2020
372  sshp-3kyq                   Denver Active Standalone Lodging
373  q7ri-3nsu  City of Denver Security Guard Licenses by Busi...
374  f3vc-vat3          City of Denver Short Term Rental Licenses
375  mpff-jbkx          City of Denver Pending Short Term Rentals
376  wnau-xrqi                           City of Denver Checkbook
377  66zf-qjdd            City of Denver Procurement Transactions
378  23sa-se52          Colorado Business Patterns 2019 US Census
379  74qa-79bk                           City of Denver Dog Parks
380  dsw3-mrn4  City of Denver Department of Motor Vehicle Off...
381  sys8-yyuf                         City of Denver Skate Parks
382  npnz-8mvz  City of Denver Business License Inspector Dist...
383  sxfp-qxs6     City of Denver Revolving Loan Fund Target Area
384  v4jc-jbmt                   Snow Depths in Northern Colorado
385  be63-q8yz             Northern Colorado Snow Characteristics
386  u56p-777a            Solar Photovoltaic Resource in Colorado
387  j3me-5ifv                        Biomass Residue in Colorado
388  bxgy-dnjp                     Contaminated Lands in Colorado
389  xz8z-8s8e            Geothermal Energy Resources in Colorado
390  x88m-3a2j               Concentrated Solar Power in Colorado
391  u6xi-qwn3                Identified Hydrothermal in Colorado
392  mxfq-jecf     Feasible Small Hydro Project Sites in Colorado
393  ujgg-3rdh                          Federal Lands in Colorado
394  ytai-hin3       Existing Hydro Non-powered Damms in Colorado
395  sn8z-q44h  EnergizeCO Small Business Resiliency Index (SBRI)
396  druy-a38s  Colorado County Business Patterns by Industry,...
397   2mk-94p9  North American Industry Classification System ...
398   35y-dxds  Colorado Art, Culture and Humanitites Non-Profits
399  xi5f-mkzt

In [53]:
ca = cimInv["U ID"].values.tolist()

In [55]:
len(ca)

2346

In [56]:
count=0
miss=[]
for id in o:
    if id not in ca:
       miss.append(id)

In [57]:
len(miss)

77

In [58]:
miss

['6ntv-x37b',
 'bjhg-77mf',
 'ucnv-vw74',
 'tbmm-ubn9',
 'q56w-zzzm',
 'smjm-6h6g',
 'ekih-pydt',
 'spwe-6ca7',
 'jwbw-xb7i',
 'cj4m-96y8',
 '7t53-5gfx',
 '8j3i-rjn4',
 'rt7b-823p',
 'xpi4-stak',
 '33q3-djk8',
 'mev7-qffb',
 'qifa-4jur',
 'sacq-tw7c',
 '7tmk-3ibe',
 '9fte-yff6',
 '3ka2-m6zm',
 'ceje-t3ek',
 'afm6-vyyp',
 '24hn-nv39',
 'y2yv-a2wp',
 'b7zn-sry4',
 'kr2r-j5ik',
 '3j7e-ezpr',
 'u9u9-cq2s',
 'abdb-jtwc',
 'mdbi-p4c8',
 't3k6-vndx',
 'rcw7-6npp',
 'nwd2-s3kd',
 'd2cu-rhft',
 '42wt-sxkv',
 '6exr-8xkn',
 'wyy2-wvrc',
 'w2w7-ggyk',
 '8pmi-n437',
 't5eg-ziay',
 'yvwz-kj9z',
 'eeb6-6s76',
 '72dx-vrxk',
 'ccz9-ggrb',
 'an2q-gwrx',
 'jr8i-33tp',
 'cr6z-hn4e',
 '2sn7-naei',
 'sshp-3kyq',
 'q7ri-3nsu',
 'f3vc-vat3',
 'mpff-jbkx',
 'wnau-xrqi',
 '66zf-qjdd',
 '23sa-se52',
 '74qa-79bk',
 'dsw3-mrn4',
 'sys8-yyuf',
 'npnz-8mvz',
 'sxfp-qxs6',
 'v4jc-jbmt',
 'be63-q8yz',
 'u56p-777a',
 'j3me-5ifv',
 'bxgy-dnjp',
 'xz8z-8s8e',
 'x88m-3a2j',
 'u6xi-qwn3',
 'mxfq-jecf',
 'ujgg-3rdh',
 'ytai-hin3',
 'sn8z-q44h',
 'druy-a38s',
 '2mk-94p9',
 '35y-dxds',
 'xi5f-mkzt']

In [5]:
import requests,os,json,sys
from bs4 import BeautifulSoup
bic_etl_home = os.getenv('bic_etl_home')
sys.path.insert(0, os.path.join(bic_etl_home, 'general', 'scripts'))

with open(os.path.join(bic_etl_home, 'general', 'datasync', 'config.json')) as f:
    config = json.load(f)

socrata_password = config["password"]


base_url = 'https://data.colorado.gov/api/views/metadata/v1/'
username = "oit_datacoloradogov@state.co.us"
password = socrata_password
print(password)
# URL to the login page
login_url = 'https://data.colorado.gov/login'

# Start a session to persist cookies
session = requests.Session()

# Get the login page to retrieve any necessary hidden form fields
login_page = session.get(login_url)
soup = BeautifulSoup(login_page.content, 'html.parser')

# Find hidden form fields (if any)
hidden_inputs = soup.find_all('input', type='hidden')
form_data = {input.get('name'): input.get('value') for input in hidden_inputs}

# Add login credentials to the form data
form_data['username'] = username
form_data['password'] = password

# Submit the login form
response = session.post(login_url, data=form_data)

# Check if login was successful
if response.url == 'https://data.yoursocrataportal.com/dashboard':
    print('Login successful')
    # Now you can access other pages that require login
    activity_log_url = 'https://data.yoursocrataportal.com/resource/xxxx-xxxx'
    activity_log_page = session.get(activity_log_url)
    
    # Process the activity log page as needed
    soup = BeautifulSoup(activity_log_page.content, 'html.parser')
    print(soup.prettify())
else:
    print('Login failed')

Denver2023!
Login failed