In [2]:
import pandas as pd
import sqlite3

## Daily Data

In [1]:

import sqlite3, pandas as pd
from pathlib import Path
TARGET_VAR = 'td'
sqlite_path = Path(f"/home/joe/work/Fire/ML/Data/DB/era5_daily_2982_{TARGET_VAR}.sqlite")
table_name = "daily_data"
with sqlite3.connect(sqlite_path) as conn:
    sample = pd.read_sql_query(f"SELECT datetime FROM {table_name}", conn)

# with sqlite3.connect(sqlite_path) as conn:
    
#     for i, row in latlons.iterrows():
        
#         pid = row['point']
#         sample = pd.read_sql_query(f"SELECT * FROM {table_name} where point_id = {pid}", conn)

DatabaseError: Execution failed on sql 'SELECT datetime FROM daily_data': database is locked

In [5]:
sample['yrmo'] = sample['datetime'].str.slice(0, 6).astype(int)
a=sample.groupby('yrmo',as_index=False).size()

hist={}
for _, row in a.iterrows():
    yr = row['yrmo'] // 100
    mo = row['yrmo'] % 100
    if yr not in hist:
        hist[yr] = {}
    hist[yr][mo] = row['size']

    
for yr in range(1990,2027):
    print(f"{yr} ",end='')
    if yr not in hist:
        hist[yr] = {mo: 0 for mo in range(1, 13)}
    for mo in range(1, 13):
        if mo in hist[yr]:
            cnt=hist[yr][mo]
        else:
            cnt=0
        print(f" {cnt:06d}", end='')
    print()

1990  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1991  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1992  000031 000029 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1993  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1994  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1995  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1996  000031 000029 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1997  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1998  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
1999  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2000  000031 000029 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2001  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2002  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2003  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2004  000031 000029 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2005  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2006  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2007  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2008  000031 000029 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2009  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2010  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2011  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2012  000031 000029 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2013  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2014  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2015  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2016  000031 000029 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2017  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2018  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2019  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2020  000031 000029 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2021  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2022  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2023  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2024  000031 000029 000031 000000 000000 000000 000000 000000 000000 000000 000000 000000
2025  000031 000028 000031 000030 000031 000030 000031 000031 000030 000031 000030 000031
2026  000031 000028 000031 000000 000000 000000 000000 000000 000000 000000 000000 000000

## Monthly Means

In [13]:
import sqlite3, pandas as pd
from pathlib import Path

TARGET_VAR = 'tp'
sqlite_path = Path(f"/home/joe/work/Fire/ML/Data/DB/era5_means_2982_{TARGET_VAR}.sqlite")
table_name = "monthly_means"

if sqlite_path.exists():
    with sqlite3.connect(sqlite_path) as conn:
        sample = pd.read_sql_query(f"SELECT * FROM {table_name}", conn)

In [16]:
sample['inches'] = sample['value'] * 39.3701

In [17]:
sample.head()

   point_id  latitude  longitude var    yrmo     value    inches
0         0      41.1     -109.0  tp  199001  0.000369  0.014540
1         0      41.1     -109.0  tp  199002  0.000816  0.032116
2         0      41.1     -109.0  tp  199003  0.000569  0.022399
3         0      41.1     -109.0  tp  199004  0.000669  0.026334
4         0      41.1     -109.0  tp  199005  0.000536  0.021120

In [10]:
a=sample.groupby('yrmo',as_index=False).size()

hist={}
for _, row in a.iterrows():
    yr = int(row['yrmo']) // 100
    mo = int(row['yrmo']) % 100
    if yr not in hist:
        hist[yr] = {}
    hist[yr][mo] = row['size']

    
for yr in range(1990,2027):
    print(f"{yr} ",end='')
    if yr not in hist:
        hist[yr] = {mo: 0 for mo in range(1, 13)}
    for mo in range(1, 13):
        if mo in hist[yr]:
            cnt=hist[yr][mo]
        else:
            cnt=0
        print(f" {cnt:06d}", end='')
    print()

1990  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1991  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1992  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1993  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1994  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1995  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1996  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1997  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1998  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
1999  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2000  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2001  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2002  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2003  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2004  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2005  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2006  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2007  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2008  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2009  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2010  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2011  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2012  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2013  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2014  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2015  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2016  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2017  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2018  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2019  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2020  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2021  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2022  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2023  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2024  002982 002982 002982 000000 000000 000000 000000 000000 000000 000000 000000 000000
2025  002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982 002982
2026  002982 002982 002982 000000 000000 000000 000000 000000 000000 000000 000000 000000

In [11]:
sample.loc[sample['point_id'] == 500]

           yrmo       value  point_id  latitude  longitude var
211500   199001  264.917539     500.0      40.4     -108.7  2t
211501   199002  263.858209     500.0      40.4     -108.7  2t
211502   199003  271.779905     500.0      40.4     -108.7  2t
211503   199004  280.677391     500.0      40.4     -108.7  2t
211504   199005  284.150492     500.0      40.4     -108.7  2t
...         ...         ...       ...       ...        ...  ..
211921   202511  277.682554     500.0      40.4     -108.7  2t
211922   202512  272.710962     500.0      40.4     -108.7  2t
1262886  202601  270.168623     500.0      40.4     -108.7  2t
1262887  202602  273.798528     500.0      40.4     -108.7  2t
1262888  202603  281.750067     500.0      40.4     -108.7  2t

[426 rows x 6 columns]

In [12]:
a=max(yms)
a=a*100+31
a

np.int64(20251231)

## Grib

In [10]:
files = ['b60a5564de59c1b8fea3beb193b71d8d.grib',
'3ee748aaf30c86c255fff03e3b9d6f8f.grib','9990857963a50a6dfe6190318c60285e.grib']
#files = ['2279a9269609be7eef4f960a90f5bdd4.grib']

files = ['b60a5564de59c1b8fea3beb193b71d8d.grib','368f88589ed7aeaa139824a4cc0121ca.grib','ea350c6b841a0759715b15ff0cce68e6.grib', '1a48edbeb3d7b177196fb17c7d710a5c.grib', '77a97b67319f589579dd9d5f890eedfb.grib']

In [11]:

import pygrib
# ...existing code...
from collections import defaultdict
import pygrib

invt = {}
for file in files:
    print(file)
    invt[file] = {}
    # invt[file]["var"] = {}
    # invt[file]["date"] = []
    grbs = pygrib.open(f"/home/joe/work/Fire/ERA5/{file}")
    for grb in grbs:
        date = str(grb.validityDate) + str(grb.validityTime)

        var = grb.shortName
        if var not in invt[file]:
            invt[file][var] = []
        
        invt[file][var].append(date)
# ...existing code...

b60a5564de59c1b8fea3beb193b71d8d.grib
368f88589ed7aeaa139824a4cc0121ca.grib
ea350c6b841a0759715b15ff0cce68e6.grib
1a48edbeb3d7b177196fb17c7d710a5c.grib
77a97b67319f589579dd9d5f890eedfb.grib

In [12]:
for f in invt:
    for var in invt[f]:    
       print(f"{f:40s} {var} {min(invt[f][var])} {max(invt[f][var])}")

b60a5564de59c1b8fea3beb193b71d8d.grib    tp 202601010 20260401900
368f88589ed7aeaa139824a4cc0121ca.grib    2t 202601010 20260402900
ea350c6b841a0759715b15ff0cce68e6.grib    2d 202601010 20260402900
1a48edbeb3d7b177196fb17c7d710a5c.grib    10u 202601010 20260402900
77a97b67319f589579dd9d5f890eedfb.grib    10v 202601010 20260402900

In [48]:
365*8

2920

In [49]:
dir(grb)

['GRIBEXSection1Problem',
 'GRIBEditionNumber',
 'Ni',
 'Nj',
 'P1',
 'P2',
 'PLPresent',
 'PVPresent',
 'WMO',
 '__class__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__getstate__',
 '__gt__',
 '__hash__',
 '__init__',
 '__init_subclass__',
 '__le__',
 '__lt__',
 '__ne__',
 '__new__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__setattr__',
 '__setitem__',
 '__setstate__',
 '__sizeof__',
 '__str__',
 '__subclasshook__',
 '_all_keys',
 '_get_key',
 '_read_only_keys',
 '_reshape_mask',
 '_ro_keys',
 '_set_projparams',
 '_unshape_mask',
 'additionalFlagPresent',
 'alternativeRowScanning',
 'analDate',
 'analDate',
 'angleSubdivisions',
 'average',
 'binaryScaleFactor',
 'bitMapIndicator',
 'bitmapPresent',
 'bitsPerValue',
 'bitsPerValueAndRepack',
 'boustrophedonic',
 'centre',
 'centreDescription',
 'centuryOfReferenceTimeOfData',
 'cfName',
 'cfNameECMF',
 'cfVarName',
 'cfVarNameECMF',
 'changeDecimalPrecision',
 'complexPacking',
 'constantFieldHalfByte',
 'data',
 'dataDate',
 'dataFlag',
 'dataLength',
 'dataRepresentationType',
 'dataTime',
 'day',
 'decimalPrecision',
 'decimalScaleFactor',
 'deleteLocalDefinition',
 'deletePV',
 'distinctLatitudes',
 'distinctLongitudes',
 'earthIsOblate',
 'editionNumber',
 'endStep',
 'eps',
 'expand_grid',
 'expand_reduced',
 'experimentVersionNumber',
 'fcstimeunits',
 'generatingProcessIdentifier',
 'getNumberOfValues',
 'globalDomain',
 'grib2LocalSectionNumber',
 'gridDefinition',
 'gridDefinitionDescription',
 'gridDefinitionTemplateNumber',
 'gridDescriptionSectionPresent',
 'gridType',
 'halfByte',
 'has_key',
 'hideThis',
 'hour',
 'iDirectionIncrement',
 'iDirectionIncrementInDegrees',
 'iScansNegatively',
 'iScansPositively',
 'ifsParam',
 'ijDirectionIncrementGiven',
 'indicatorOfParameter',
 'indicatorOfTypeOfLevel',
 'integerPointValues',
 'isConstant',
 'isGridded',
 'isSpectral',
 'is_missing',
 'jDirectionIncrement',
 'jDirectionIncrementInDegrees',
 'jPointsAreConsecutive',
 'jScansNegatively',
 'jScansPositively',
 'julianDay',
 'keys',
 'kurtosis',
 'latLonValues',
 'latitudeOfFirstGridPoint',
 'latitudeOfFirstGridPointInDegrees',
 'latitudeOfLastGridPoint',
 'latitudeOfLastGridPointInDegrees',
 'latitudes',
 'latlons',
 'lengthOfHeaders',
 'level',
 'localDefinitionNumber',
 'localUsePresent',
 'longitudeOfFirstGridPoint',
 'longitudeOfFirstGridPointInDegrees',
 'longitudeOfLastGridPoint',
 'longitudeOfLastGridPointInDegrees',
 'longitudes',
 'marsClass',
 'marsParam',
 'marsStream',
 'marsType',
 'maximum',
 'md5Headers',
 'md5Product',
 'md5Section1',
 'md5Section2',
 'md5Section4',
 'messagenumber',
 'minimum',
 'minute',
 'missingValue',
 'month',
 'name',
 'nameECMF',
 'neitherPresent',
 'numberIncludedInAverage',
 'numberMissingFromAveragesOrAccumulations',
 'numberOfCodedValues',
 'numberOfDataPoints',
 'numberOfForecastsInEnsemble',
 'numberOfMissing',
 'numberOfValues',
 'numberOfVerticalCoordinateValues',
 'offsetSection0',
 'offsetValuesBy',
 'optimizeScaleFactor',
 'orderOfSPD',
 'packingError',
 'packingType',
 'paramId',
 'paramIdECMF',
 'paramIdForConversion',
 'parameterName',
 'parameterUnits',
 'perturbationNumber',
 'pressureUnits',
 'productionStatusOfProcessedData',
 'projparams',
 'pvlLocation',
 'radius',
 'referenceValue',
 'referenceValueError',
 'resolutionAndComponentFlags',
 'resolutionAndComponentFlags3',
 'resolutionAndComponentFlags4',
 'resolutionAndComponentFlags6',
 'resolutionAndComponentFlags7',
 'resolutionAndComponentFlags8',
 'scaleValuesBy',
 'scanningMode',
 'scanningMode4',
 'scanningMode5',
 'scanningMode6',
 'scanningMode7',
 'scanningMode8',
 'second',
 'section0Length',
 'section1Length',
 'section2Length',
 'section4Length',
 'section5Length',
 'setLocalDefinition',
 'setPackingType',
 'shortName',
 'shortNameECMF',
 'skewness',
 'sphericalHarmonics',
 'standardDeviation',
 'startStep',
 'stepRange',
 'stepType',
 'stepTypeForConversion',
 'stepUnits',
 'subCentre',
 'swapScanningAlternativeRows',
 'table2Version',
 'tableReference',
 'timeRangeIndicator',
 'tostring',
 'totalLength',
 'typeOfLevel',
 'typeOfLevelECMF',
 'unitOfTimeRange',
 'units',
 'unitsECMF',
 'unpackedError',
 'uvRelativeToGrid',
 'validDate',
 'validDate',
 'valid_key',
 'validityDate',
 'validityDateTime',
 'validityTime',
 'values',
 'wrongPadding',
 'year',
 'yearOfCentury',
 'zeros']

In [57]:
str(grb.validityDate) + str(grb.validityTime)

'202604011500'

In [21]:
import sqlite3, pandas as pd
from pathlib import Path
TARGET_VAR = 'tp'
sqlite_path = Path(f"/home/joe/work/Fire/ML/Data/DB/era5_daily_2982_{TARGET_VAR}.sqlite")
table_name = "daily_data"
with sqlite3.connect(sqlite_path) as conn:
    sample = pd.read_sql_query(f"SELECT * FROM {table_name} where point_id = 500", conn)

In [22]:
sample.shape

(13239, 11)

In [23]:
sample.head()

,datetime,point_id,variable,0,3,6,9,12,15,18,21
0,19980101,500,pcp,0.000043,0.000000,0.000000,8.553266e-07,0.000001,0.000001,1.406670e-06,0.000001
1,19980102,500,pcp,0.000001,0.000000,0.000000,0.000000e+00,0.000000,0.000000,4.172325e-07,0.000002
2,19980103,500,pcp,0.000002,0.000000,0.000836,1.033354e-03,0.001051,0.001063,1.076835e-03,0.001104
3,19980104,500,pcp,0.001111,0.000012,0.000027,1.825020e-04,0.000436,0.000542,6.920874e-04,0.000992
4,19980105,500,pcp,0.001069,0.000049,0.000291,1.630664e-03,0.003727,0.004062,5.542785e-03,0.007107

In [24]:
0.001033353805439674*39.3701

0.04068324265554051

In [27]:
b=sample[["0","3","6","9","12","15","18","21"]].sum(axis=1)

In [28]:
b.head()

0    0.000050
1    0.000004
2    0.006166
3    0.003994
4    0.023478
dtype: float64

In [30]:
import numpy as np
import pandas as pd
from sklearn.mixture import GaussianMixture
from scipy.optimize import brentq
from scipy.stats import norm

# precip: 1D array-like of daily precip values (>=0)
x = np.asarray(b.values, dtype=float)
x = x[np.isfinite(x)]
x = x[x >= 0]

# keep strictly positive values for fitting
xp = x[x > 0]

# optional: trim extreme storms so they don't dominate fit
hi = np.quantile(xp, 0.995)
xp_fit = xp[xp <= hi]

# log transform
y = np.log10(xp_fit).reshape(-1, 1)

gmm = GaussianMixture(n_components=2, random_state=0)
gmm.fit(y)

w = gmm.weights_
m = gmm.means_.ravel()
s = np.sqrt(gmm.covariances_.ravel())

# identify lower-mean component as "dry/noise", higher as "wet"
i_dry, i_wet = np.argsort(m)

def f(z):
    dry = w[i_dry] * norm.pdf(z, m[i_dry], s[i_dry])
    wet = w[i_wet] * norm.pdf(z, m[i_wet], s[i_wet])
    return dry - wet

# solve in log space between the two means
z_cut = brentq(f, m[i_dry], m[i_wet])
cutoff = 10 ** z_cut

print("Estimated cutoff:", cutoff)

# apply cutoff
x_clean = np.where(x < cutoff, 0.0, x)

Estimated cutoff: 0.00013336215519250914

In [32]:
.00013336215519250914*39.3701

0.0052504813861446046

In [33]:
.01/39370.1

2.539998628400741e-07