In [2]:
import sqlite3,pandas as pd

In [3]:

def readWxData(db):
    connr = sqlite3.connect(db)
    df=pd.read_sql('select * from MEANS_TTdRHVPD', connr)
    return df


df=readWxData('/home/joe/work/Fire/Data/DB/era5DataMeans.db')

In [4]:
df.head()

   index  Point    Yrmo  Length         T         Td         RH       VPD
0      0      0  199001     248 -8.463992 -12.366048  74.223548  0.092007
1      1      0  199002     224 -9.227723 -12.758839  76.263616  0.079737
2      2      0  199003     248 -3.466290  -7.204153  76.585927  0.127759
3      3      0  199004     240  4.388708  -3.163000  60.712417  0.380563
4      4      0  199005     248  7.292621  -4.213629  48.368589  0.628547

In [59]:
df['Point'].value_counts().sort_index(ascending=True)

Point
0       420
1       420
2       420
3       420
4       420
       ...
2977    420
2978    420
2979    420
2980    420
2981    420
Name: count, Length: 2982, dtype: int64

In [31]:
dfz = pd.read_csv('New/Data/latlon_elevation.csv')

In [32]:
dfz

      latitude  longitude  elevation_m  point
0         41.1      251.0  2431.132808      1
1         41.1      251.1  2410.339385      2
2         41.1      251.2  2285.373990      3
3         41.1      251.3  2188.474594      4
4         41.1      251.4  2127.528356      5
...        ...        ...          ...    ...
2977      37.0      257.6  1192.643800   2978
2978      37.0      257.7  1165.294816   2979
2979      37.0      257.8  1142.657642   2980
2980      37.0      257.9  1121.249636   2981
2981      37.0      258.0  1105.270454   2982

[2982 rows x 4 columns]

In [33]:
dfz['longitude'] = (dfz['longitude']-360).round(1)

In [34]:
dfz.head()

   latitude  longitude  elevation_m  point
0      41.1     -109.0  2431.132808      1
1      41.1     -108.9  2410.339385      2
2      41.1     -108.8  2285.373990      3
3      41.1     -108.7  2188.474594      4
4      41.1     -108.6  2127.528356      5

In [35]:
dfz.shape,df.shape

((2982, 4), (1252440, 8))

In [36]:
dfll = pd.read_csv('latlons_42x71.csv')

In [37]:
dfll.shape

(2982, 3)

In [48]:
cnt=0
for _,row in dfz.iterrows():
    lat=row['latitude']
    lon=row['longitude']
    point=row['point']
    tmp=dfll[(dfll['lat']==lat)]
    
    if tmp.shape[0] == 0:
        print(tmp.shape[0],point,lat,lon)
        cnt+=1
print(cnt)

0 427.0 40.5 -109.0
0 428.0 40.5 -108.9
0 429.0 40.5 -108.8
0 430.0 40.5 -108.7
0 431.0 40.5 -108.6
0 432.0 40.5 -108.5
0 433.0 40.5 -108.4
0 434.0 40.5 -108.3
0 435.0 40.5 -108.2
0 436.0 40.5 -108.1
0 437.0 40.5 -108.0
0 438.0 40.5 -107.9
0 439.0 40.5 -107.8
0 440.0 40.5 -107.7
0 441.0 40.5 -107.6
0 442.0 40.5 -107.5
0 443.0 40.5 -107.4
0 444.0 40.5 -107.3
0 445.0 40.5 -107.2
0 446.0 40.5 -107.1
0 447.0 40.5 -107.0
0 448.0 40.5 -106.9
0 449.0 40.5 -106.8
0 450.0 40.5 -106.7
0 451.0 40.5 -106.6
0 452.0 40.5 -106.5
0 453.0 40.5 -106.4
0 454.0 40.5 -106.3
0 455.0 40.5 -106.2
0 456.0 40.5 -106.1
0 457.0 40.5 -106.0
0 458.0 40.5 -105.9
0 459.0 40.5 -105.8
0 460.0 40.5 -105.7
0 461.0 40.5 -105.6
0 462.0 40.5 -105.5
0 463.0 40.5 -105.4
0 464.0 40.5 -105.3
0 465.0 40.5 -105.2
0 466.0 40.5 -105.1
0 467.0 40.5 -105.0
0 468.0 40.5 -104.9
0 469.0 40.5 -104.8
0 470.0 40.5 -104.7
0 471.0 40.5 -104.6
0 472.0 40.5 -104.5
0 473.0 40.5 -104.4
0 474.0 40.5 -104.3
0 475.0 40.5 -104.2
0 476.0 40.5 -104.1
0 477.0 40.5 -104.0
0 478.0 40.5 -103.9
0 479.0 40.5 -103.8
0 480.0 40.5 -103.7
0 481.0 40.5 -103.6
0 482.0 40.5 -103.5
0 483.0 40.5 -103.4
0 484.0 40.5 -103.3
0 485.0 40.5 -103.2
0 486.0 40.5 -103.1
0 487.0 40.5 -103.0
0 488.0 40.5 -102.9
0 489.0 40.5 -102.8
0 490.0 40.5 -102.7
0 491.0 40.5 -102.6
0 492.0 40.5 -102.5
0 493.0 40.5 -102.4
0 494.0 40.5 -102.3
0 495.0 40.5 -102.2
0 496.0 40.5 -102.1
0 497.0 40.5 -102.0
0 498.0 40.4 -109.0
0 499.0 40.4 -108.9
0 500.0 40.4 -108.8
0 501.0 40.4 -108.7
0 502.0 40.4 -108.6
0 503.0 40.4 -108.5
0 504.0 40.4 -108.4
0 505.0 40.4 -108.3
0 506.0 40.4 -108.2
0 507.0 40.4 -108.1
0 508.0 40.4 -108.0
0 509.0 40.4 -107.9
0 510.0 40.4 -107.8
0 511.0 40.4 -107.7
0 512.0 40.4 -107.6
0 513.0 40.4 -107.5
0 514.0 40.4 -107.4
0 515.0 40.4 -107.3
0 516.0 40.4 -107.2
0 517.0 40.4 -107.1
0 518.0 40.4 -107.0
0 519.0 40.4 -106.9
0 520.0 40.4 -106.8
0 521.0 40.4 -106.7
0 522.0 40.4 -106.6
0 523.0 40.4 -106.5
0 524.0 40.4 -106.4
0 525.0 40.4 -106.3
0 526.0 40.4 -106.2
0 527.0 40.4 -106.1
0 528.0 40.4 -106.0
0 529.0 40.4 -105.9
0 530.0 40.4 -105.8
0 531.0 40.4 -105.7
0 532.0 40.4 -105.6
0 533.0 40.4 -105.5
0 534.0 40.4 -105.4
0 535.0 40.4 -105.3
0 536.0 40.4 -105.2
0 537.0 40.4 -105.1
0 538.0 40.4 -105.0
0 539.0 40.4 -104.9
0 540.0 40.4 -104.8
0 541.0 40.4 -104.7
0 542.0 40.4 -104.6
0 543.0 40.4 -104.5
0 544.0 40.4 -104.4
0 545.0 40.4 -104.3
0 546.0 40.4 -104.2
0 547.0 40.4 -104.1
0 548.0 40.4 -104.0
0 549.0 40.4 -103.9
0 550.0 40.4 -103.8
0 551.0 40.4 -103.7
0 552.0 40.4 -103.6
0 553.0 40.4 -103.5
0 554.0 40.4 -103.4
0 555.0 40.4 -103.3
0 556.0 40.4 -103.2
0 557.0 40.4 -103.1
0 558.0 40.4 -103.0
0 559.0 40.4 -102.9
0 560.0 40.4 -102.8
0 561.0 40.4 -102.7
0 562.0 40.4 -102.6
0 563.0 40.4 -102.5
0 564.0 40.4 -102.4
0 565.0 40.4 -102.3
0 566.0 40.4 -102.2
0 567.0 40.4 -102.1
0 568.0 40.4 -102.0
0 569.0 40.3 -109.0
0 570.0 40.3 -108.9
0 571.0 40.3 -108.8
0 572.0 40.3 -108.7
0 573.0 40.3 -108.6
0 574.0 40.3 -108.5
0 575.0 40.3 -108.4
0 576.0 40.3 -108.3
0 577.0 40.3 -108.2
0 578.0 40.3 -108.1
0 579.0 40.3 -108.0
0 580.0 40.3 -107.9
0 581.0 40.3 -107.8
0 582.0 40.3 -107.7
0 583.0 40.3 -107.6
0 584.0 40.3 -107.5
0 585.0 40.3 -107.4
0 586.0 40.3 -107.3
0 587.0 40.3 -107.2
0 588.0 40.3 -107.1
0 589.0 40.3 -107.0
0 590.0 40.3 -106.9
0 591.0 40.3 -106.8
0 592.0 40.3 -106.7
0 593.0 40.3 -106.6
0 594.0 40.3 -106.5
0 595.0 40.3 -106.4
0 596.0 40.3 -106.3
0 597.0 40.3 -106.2
0 598.0 40.3 -106.1
0 599.0 40.3 -106.0
0 600.0 40.3 -105.9
0 601.0 40.3 -105.8
0 602.0 40.3 -105.7
0 603.0 40.3 -105.6
0 604.0 40.3 -105.5
0 605.0 40.3 -105.4
0 606.0 40.3 -105.3
0 607.0 40.3 -105.2
0 608.0 40.3 -105.1
0 609.0 40.3 -105.0
0 610.0 40.3 -104.9
0 611.0 40.3 -104.8
0 612.0 40.3 -104.7
0 613.0 40.3 -104.6
0 614.0 40.3 -104.5
0 615.0 40.3 -104.4
0 616.0 40.3 -104.3
0 617.0 40.3 -104.2
0 618.0 40.3 -104.1
0 619.0 40.3 -104.0
0 620.0 40.3 -103.9
0 621.0 40.3 -103.8
0 622.0 40.3 -103.7
0 623.0 40.3 -103.6
0 624.0 40.3 -103.5
0 625.0 40.3 -103.4
0 626.0 40.3 -103.3
0 627.0 40.3 -103.2
0 628.0 40.3 -103.1
0 629.0 40.3 -103.0
0 630.0 40.3 -102.9
0 631.0 40.3 -102.8
0 632.0 40.3 -102.7
0 633.0 40.3 -102.6
0 634.0 40.3 -102.5
0 635.0 40.3 -102.4
0 636.0 40.3 -102.3
0 637.0 40.3 -102.2
0 638.0 40.3 -102.1
0 639.0 40.3 -102.0
0 640.0 40.2 -109.0
0 641.0 40.2 -108.9
0 642.0 40.2 -108.8
0 643.0 40.2 -108.7
0 644.0 40.2 -108.6
0 645.0 40.2 -108.5
0 646.0 40.2 -108.4
0 647.0 40.2 -108.3
0 648.0 40.2 -108.2
0 649.0 40.2 -108.1
0 650.0 40.2 -108.0
0 651.0 40.2 -107.9
0 652.0 40.2 -107.8
0 653.0 40.2 -107.7
0 654.0 40.2 -107.6
0 655.0 40.2 -107.5
0 656.0 40.2 -107.4
0 657.0 40.2 -107.3
0 658.0 40.2 -107.2
0 659.0 40.2 -107.1
0 660.0 40.2 -107.0
0 661.0 40.2 -106.9
0 662.0 40.2 -106.8
0 663.0 40.2 -106.7
0 664.0 40.2 -106.6
0 665.0 40.2 -106.5
0 666.0 40.2 -106.4
0 667.0 40.2 -106.3
0 668.0 40.2 -106.2
0 669.0 40.2 -106.1
0 670.0 40.2 -106.0
0 671.0 40.2 -105.9
0 672.0 40.2 -105.8
0 673.0 40.2 -105.7
0 674.0 40.2 -105.6
0 675.0 40.2 -105.5
0 676.0 40.2 -105.4
0 677.0 40.2 -105.3
0 678.0 40.2 -105.2
0 679.0 40.2 -105.1
0 680.0 40.2 -105.0
0 681.0 40.2 -104.9
0 682.0 40.2 -104.8
0 683.0 40.2 -104.7
0 684.0 40.2 -104.6
0 685.0 40.2 -104.5
0 686.0 40.2 -104.4
0 687.0 40.2 -104.3
0 688.0 40.2 -104.2
0 689.0 40.2 -104.1
0 690.0 40.2 -104.0
0 691.0 40.2 -103.9
0 692.0 40.2 -103.8
0 693.0 40.2 -103.7
0 694.0 40.2 -103.6
0 695.0 40.2 -103.5
0 696.0 40.2 -103.4
0 697.0 40.2 -103.3
0 698.0 40.2 -103.2
0 699.0 40.2 -103.1
0 700.0 40.2 -103.0
0 701.0 40.2 -102.9
0 702.0 40.2 -102.8
0 703.0 40.2 -102.7
0 704.0 40.2 -102.6
0 705.0 40.2 -102.5
0 706.0 40.2 -102.4
0 707.0 40.2 -102.3
0 708.0 40.2 -102.2
0 709.0 40.2 -102.1
0 710.0 40.2 -102.0
0 711.0 40.1 -109.0
0 712.0 40.1 -108.9
0 713.0 40.1 -108.8
0 714.0 40.1 -108.7
0 715.0 40.1 -108.6
0 716.0 40.1 -108.5
0 717.0 40.1 -108.4
0 718.0 40.1 -108.3
0 719.0 40.1 -108.2
0 720.0 40.1 -108.1
0 721.0 40.1 -108.0
0 722.0 40.1 -107.9
0 723.0 40.1 -107.8
0 724.0 40.1 -107.7
0 725.0 40.1 -107.6
0 726.0 40.1 -107.5
0 727.0 40.1 -107.4
0 728.0 40.1 -107.3
0 729.0 40.1 -107.2
0 730.0 40.1 -107.1
0 731.0 40.1 -107.0
0 732.0 40.1 -106.9
0 733.0 40.1 -106.8
0 734.0 40.1 -106.7
0 735.0 40.1 -106.6
0 736.0 40.1 -106.5
0 737.0 40.1 -106.4
0 738.0 40.1 -106.3
0 739.0 40.1 -106.2
0 740.0 40.1 -106.1
0 741.0 40.1 -106.0
0 742.0 40.1 -105.9
0 743.0 40.1 -105.8
0 744.0 40.1 -105.7
0 745.0 40.1 -105.6
0 746.0 40.1 -105.5
0 747.0 40.1 -105.4
0 748.0 40.1 -105.3
0 749.0 40.1 -105.2
0 750.0 40.1 -105.1
0 751.0 40.1 -105.0
0 752.0 40.1 -104.9
0 753.0 40.1 -104.8
0 754.0 40.1 -104.7
0 755.0 40.1 -104.6
0 756.0 40.1 -104.5
0 757.0 40.1 -104.4
0 758.0 40.1 -104.3
0 759.0 40.1 -104.2
0 760.0 40.1 -104.1
0 761.0 40.1 -104.0
0 762.0 40.1 -103.9
0 763.0 40.1 -103.8
0 764.0 40.1 -103.7
0 765.0 40.1 -103.6
0 766.0 40.1 -103.5
0 767.0 40.1 -103.4
0 768.0 40.1 -103.3
0 769.0 40.1 -103.2
0 770.0 40.1 -103.1
0 771.0 40.1 -103.0
0 772.0 40.1 -102.9
0 773.0 40.1 -102.8
0 774.0 40.1 -102.7
0 775.0 40.1 -102.6
0 776.0 40.1 -102.5
0 777.0 40.1 -102.4
0 778.0 40.1 -102.3
0 779.0 40.1 -102.2
0 780.0 40.1 -102.1
0 781.0 40.1 -102.0
0 782.0 40.0 -109.0
0 783.0 40.0 -108.9
0 784.0 40.0 -108.8
0 785.0 40.0 -108.7
0 786.0 40.0 -108.6
0 787.0 40.0 -108.5
0 788.0 40.0 -108.4
0 789.0 40.0 -108.3
0 790.0 40.0 -108.2
0 791.0 40.0 -108.1
0 792.0 40.0 -108.0
0 793.0 40.0 -107.9
0 794.0 40.0 -107.8
0 795.0 40.0 -107.7
0 796.0 40.0 -107.6
0 797.0 40.0 -107.5
0 798.0 40.0 -107.4
0 799.0 40.0 -107.3
0 800.0 40.0 -107.2
0 801.0 40.0 -107.1
0 802.0 40.0 -107.0
0 803.0 40.0 -106.9
0 804.0 40.0 -106.8
0 805.0 40.0 -106.7
0 806.0 40.0 -106.6
0 807.0 40.0 -106.5
0 808.0 40.0 -106.4
0 809.0 40.0 -106.3
0 810.0 40.0 -106.2
0 811.0 40.0 -106.1
0 812.0 40.0 -106.0
0 813.0 40.0 -105.9
0 814.0 40.0 -105.8
0 815.0 40.0 -105.7
0 816.0 40.0 -105.6
0 817.0 40.0 -105.5
0 818.0 40.0 -105.4
0 819.0 40.0 -105.3
0 820.0 40.0 -105.2
0 821.0 40.0 -105.1
0 822.0 40.0 -105.0
0 823.0 40.0 -104.9
0 824.0 40.0 -104.8
0 825.0 40.0 -104.7
0 826.0 40.0 -104.6
0 827.0 40.0 -104.5
0 828.0 40.0 -104.4
0 829.0 40.0 -104.3
0 830.0 40.0 -104.2
0 831.0 40.0 -104.1
0 832.0 40.0 -104.0
0 833.0 40.0 -103.9
0 834.0 40.0 -103.8
0 835.0 40.0 -103.7
0 836.0 40.0 -103.6
0 837.0 40.0 -103.5
0 838.0 40.0 -103.4
0 839.0 40.0 -103.3
0 840.0 40.0 -103.2
0 841.0 40.0 -103.1
0 842.0 40.0 -103.0
0 843.0 40.0 -102.9
0 844.0 40.0 -102.8
0 845.0 40.0 -102.7
0 846.0 40.0 -102.6
0 847.0 40.0 -102.5
0 848.0 40.0 -102.4
0 849.0 40.0 -102.3
0 850.0 40.0 -102.2
0 851.0 40.0 -102.1
0 852.0 40.0 -102.0
0 853.0 39.9 -109.0
0 854.0 39.9 -108.9
0 855.0 39.9 -108.8
0 856.0 39.9 -108.7
0 857.0 39.9 -108.6
0 858.0 39.9 -108.5
0 859.0 39.9 -108.4
0 860.0 39.9 -108.3
0 861.0 39.9 -108.2
0 862.0 39.9 -108.1
0 863.0 39.9 -108.0
0 864.0 39.9 -107.9
0 865.0 39.9 -107.8
0 866.0 39.9 -107.7
0 867.0 39.9 -107.6
0 868.0 39.9 -107.5
0 869.0 39.9 -107.4
0 870.0 39.9 -107.3
0 871.0 39.9 -107.2
0 872.0 39.9 -107.1
0 873.0 39.9 -107.0
0 874.0 39.9 -106.9
0 875.0 39.9 -106.8
0 876.0 39.9 -106.7
0 877.0 39.9 -106.6
0 878.0 39.9 -106.5
0 879.0 39.9 -106.4
0 880.0 39.9 -106.3
0 881.0 39.9 -106.2
0 882.0 39.9 -106.1
0 883.0 39.9 -106.0
0 884.0 39.9 -105.9
0 885.0 39.9 -105.8
0 886.0 39.9 -105.7
0 887.0 39.9 -105.6
0 888.0 39.9 -105.5
0 889.0 39.9 -105.4
0 890.0 39.9 -105.3
0 891.0 39.9 -105.2
0 892.0 39.9 -105.1
0 893.0 39.9 -105.0
0 894.0 39.9 -104.9
0 895.0 39.9 -104.8
0 896.0 39.9 -104.7
0 897.0 39.9 -104.6
0 898.0 39.9 -104.5
0 899.0 39.9 -104.4
0 900.0 39.9 -104.3
0 901.0 39.9 -104.2
0 902.0 39.9 -104.1
0 903.0 39.9 -104.0
0 904.0 39.9 -103.9
0 905.0 39.9 -103.8
0 906.0 39.9 -103.7
0 907.0 39.9 -103.6
0 908.0 39.9 -103.5
0 909.0 39.9 -103.4
0 910.0 39.9 -103.3
0 911.0 39.9 -103.2
0 912.0 39.9 -103.1
0 913.0 39.9 -103.0
0 914.0 39.9 -102.9
0 915.0 39.9 -102.8
0 916.0 39.9 -102.7
0 917.0 39.9 -102.6
0 918.0 39.9 -102.5
0 919.0 39.9 -102.4
0 920.0 39.9 -102.3
0 921.0 39.9 -102.2
0 922.0 39.9 -102.1
0 923.0 39.9 -102.0
0 924.0 39.8 -109.0
0 925.0 39.8 -108.9
0 926.0 39.8 -108.8
0 927.0 39.8 -108.7
0 928.0 39.8 -108.6
0 929.0 39.8 -108.5
0 930.0 39.8 -108.4
0 931.0 39.8 -108.3
0 932.0 39.8 -108.2
0 933.0 39.8 -108.1
0 934.0 39.8 -108.0
0 935.0 39.8 -107.9
0 936.0 39.8 -107.8
0 937.0 39.8 -107.7
0 938.0 39.8 -107.6
0 939.0 39.8 -107.5
0 940.0 39.8 -107.4
0 941.0 39.8 -107.3
0 942.0 39.8 -107.2
0 943.0 39.8 -107.1
0 944.0 39.8 -107.0
0 945.0 39.8 -106.9
0 946.0 39.8 -106.8
0 947.0 39.8 -106.7
0 948.0 39.8 -106.6
0 949.0 39.8 -106.5
0 950.0 39.8 -106.4
0 951.0 39.8 -106.3
0 952.0 39.8 -106.2
0 953.0 39.8 -106.1
0 954.0 39.8 -106.0
0 955.0 39.8 -105.9
0 956.0 39.8 -105.8
0 957.0 39.8 -105.7
0 958.0 39.8 -105.6
0 959.0 39.8 -105.5
0 960.0 39.8 -105.4
0 961.0 39.8 -105.3
0 962.0 39.8 -105.2
0 963.0 39.8 -105.1
0 964.0 39.8 -105.0
0 965.0 39.8 -104.9
0 966.0 39.8 -104.8
0 967.0 39.8 -104.7
0 968.0 39.8 -104.6
0 969.0 39.8 -104.5
0 970.0 39.8 -104.4
0 971.0 39.8 -104.3
0 972.0 39.8 -104.2
0 973.0 39.8 -104.1
0 974.0 39.8 -104.0
0 975.0 39.8 -103.9
0 976.0 39.8 -103.8
0 977.0 39.8 -103.7
0 978.0 39.8 -103.6
0 979.0 39.8 -103.5
0 980.0 39.8 -103.4
0 981.0 39.8 -103.3
0 982.0 39.8 -103.2
0 983.0 39.8 -103.1
0 984.0 39.8 -103.0
0 985.0 39.8 -102.9
0 986.0 39.8 -102.8
0 987.0 39.8 -102.7
0 988.0 39.8 -102.6
0 989.0 39.8 -102.5
0 990.0 39.8 -102.4
0 991.0 39.8 -102.3
0 992.0 39.8 -102.2
0 993.0 39.8 -102.1
0 994.0 39.8 -102.0
0 995.0 39.7 -109.0
0 996.0 39.7 -108.9
0 997.0 39.7 -108.8
0 998.0 39.7 -108.7
0 999.0 39.7 -108.6
0 1000.0 39.7 -108.5
0 1001.0 39.7 -108.4
0 1002.0 39.7 -108.3
0 1003.0 39.7 -108.2
0 1004.0 39.7 -108.1
0 1005.0 39.7 -108.0
0 1006.0 39.7 -107.9
0 1007.0 39.7 -107.8
0 1008.0 39.7 -107.7
0 1009.0 39.7 -107.6
0 1010.0 39.7 -107.5
0 1011.0 39.7 -107.4
0 1012.0 39.7 -107.3
0 1013.0 39.7 -107.2
0 1014.0 39.7 -107.1
0 1015.0 39.7 -107.0
0 1016.0 39.7 -106.9
0 1017.0 39.7 -106.8
0 1018.0 39.7 -106.7
0 1019.0 39.7 -106.6
0 1020.0 39.7 -106.5
0 1021.0 39.7 -106.4
0 1022.0 39.7 -106.3
0 1023.0 39.7 -106.2
0 1024.0 39.7 -106.1
0 1025.0 39.7 -106.0
0 1026.0 39.7 -105.9
0 1027.0 39.7 -105.8
0 1028.0 39.7 -105.7
0 1029.0 39.7 -105.6
0 1030.0 39.7 -105.5
0 1031.0 39.7 -105.4
0 1032.0 39.7 -105.3
0 1033.0 39.7 -105.2
0 1034.0 39.7 -105.1
0 1035.0 39.7 -105.0
0 1036.0 39.7 -104.9
0 1037.0 39.7 -104.8
0 1038.0 39.7 -104.7
0 1039.0 39.7 -104.6
0 1040.0 39.7 -104.5
0 1041.0 39.7 -104.4
0 1042.0 39.7 -104.3
0 1043.0 39.7 -104.2
0 1044.0 39.7 -104.1
0 1045.0 39.7 -104.0
0 1046.0 39.7 -103.9
0 1047.0 39.7 -103.8
0 1048.0 39.7 -103.7
0 1049.0 39.7 -103.6
0 1050.0 39.7 -103.5
0 1051.0 39.7 -103.4
0 1052.0 39.7 -103.3
0 1053.0 39.7 -103.2
0 1054.0 39.7 -103.1
0 1055.0 39.7 -103.0
0 1056.0 39.7 -102.9
0 1057.0 39.7 -102.8
0 1058.0 39.7 -102.7
0 1059.0 39.7 -102.6
0 1060.0 39.7 -102.5
0 1061.0 39.7 -102.4
0 1062.0 39.7 -102.3
0 1063.0 39.7 -102.2
0 1064.0 39.7 -102.1
0 1065.0 39.7 -102.0
0 1066.0 39.6 -109.0
0 1067.0 39.6 -108.9
0 1068.0 39.6 -108.8
0 1069.0 39.6 -108.7
0 1070.0 39.6 -108.6
0 1071.0 39.6 -108.5
0 1072.0 39.6 -108.4
0 1073.0 39.6 -108.3
0 1074.0 39.6 -108.2
0 1075.0 39.6 -108.1
0 1076.0 39.6 -108.0
0 1077.0 39.6 -107.9
0 1078.0 39.6 -107.8
0 1079.0 39.6 -107.7
0 1080.0 39.6 -107.6
0 1081.0 39.6 -107.5
0 1082.0 39.6 -107.4
0 1083.0 39.6 -107.3
0 1084.0 39.6 -107.2
0 1085.0 39.6 -107.1
0 1086.0 39.6 -107.0
0 1087.0 39.6 -106.9
0 1088.0 39.6 -106.8
0 1089.0 39.6 -106.7
0 1090.0 39.6 -106.6
0 1091.0 39.6 -106.5
0 1092.0 39.6 -106.4
0 1093.0 39.6 -106.3
0 1094.0 39.6 -106.2
0 1095.0 39.6 -106.1
0 1096.0 39.6 -106.0
0 1097.0 39.6 -105.9
0 1098.0 39.6 -105.8
0 1099.0 39.6 -105.7
0 1100.0 39.6 -105.6
0 1101.0 39.6 -105.5
0 1102.0 39.6 -105.4
0 1103.0 39.6 -105.3
0 1104.0 39.6 -105.2
0 1105.0 39.6 -105.1
0 1106.0 39.6 -105.0
0 1107.0 39.6 -104.9
0 1108.0 39.6 -104.8
0 1109.0 39.6 -104.7
0 1110.0 39.6 -104.6
0 1111.0 39.6 -104.5
0 1112.0 39.6 -104.4
0 1113.0 39.6 -104.3
0 1114.0 39.6 -104.2
0 1115.0 39.6 -104.1
0 1116.0 39.6 -104.0
0 1117.0 39.6 -103.9
0 1118.0 39.6 -103.8
0 1119.0 39.6 -103.7
0 1120.0 39.6 -103.6
0 1121.0 39.6 -103.5
0 1122.0 39.6 -103.4
0 1123.0 39.6 -103.3
0 1124.0 39.6 -103.2
0 1125.0 39.6 -103.1
0 1126.0 39.6 -103.0
0 1127.0 39.6 -102.9
0 1128.0 39.6 -102.8
0 1129.0 39.6 -102.7
0 1130.0 39.6 -102.6
0 1131.0 39.6 -102.5
0 1132.0 39.6 -102.4
0 1133.0 39.6 -102.3
0 1134.0 39.6 -102.2
0 1135.0 39.6 -102.1
0 1136.0 39.6 -102.0
0 1137.0 39.5 -109.0
0 1138.0 39.5 -108.9
0 1139.0 39.5 -108.8
0 1140.0 39.5 -108.7
0 1141.0 39.5 -108.6
0 1142.0 39.5 -108.5
0 1143.0 39.5 -108.4
0 1144.0 39.5 -108.3
0 1145.0 39.5 -108.2
0 1146.0 39.5 -108.1
0 1147.0 39.5 -108.0
0 1148.0 39.5 -107.9
0 1149.0 39.5 -107.8
0 1150.0 39.5 -107.7
0 1151.0 39.5 -107.6
0 1152.0 39.5 -107.5
0 1153.0 39.5 -107.4
0 1154.0 39.5 -107.3
0 1155.0 39.5 -107.2
0 1156.0 39.5 -107.1
0 1157.0 39.5 -107.0
0 1158.0 39.5 -106.9
0 1159.0 39.5 -106.8
0 1160.0 39.5 -106.7
0 1161.0 39.5 -106.6
0 1162.0 39.5 -106.5
0 1163.0 39.5 -106.4
0 1164.0 39.5 -106.3
0 1165.0 39.5 -106.2
0 1166.0 39.5 -106.1
0 1167.0 39.5 -106.0
0 1168.0 39.5 -105.9
0 1169.0 39.5 -105.8
0 1170.0 39.5 -105.7
0 1171.0 39.5 -105.6
0 1172.0 39.5 -105.5
0 1173.0 39.5 -105.4
0 1174.0 39.5 -105.3
0 1175.0 39.5 -105.2
0 1176.0 39.5 -105.1
0 1177.0 39.5 -105.0
0 1178.0 39.5 -104.9
0 1179.0 39.5 -104.8
0 1180.0 39.5 -104.7
0 1181.0 39.5 -104.6
0 1182.0 39.5 -104.5
0 1183.0 39.5 -104.4
0 1184.0 39.5 -104.3
0 1185.0 39.5 -104.2
0 1186.0 39.5 -104.1
0 1187.0 39.5 -104.0
0 1188.0 39.5 -103.9
0 1189.0 39.5 -103.8
0 1190.0 39.5 -103.7
0 1191.0 39.5 -103.6
0 1192.0 39.5 -103.5
0 1193.0 39.5 -103.4
0 1194.0 39.5 -103.3
0 1195.0 39.5 -103.2
0 1196.0 39.5 -103.1
0 1197.0 39.5 -103.0
0 1198.0 39.5 -102.9
0 1199.0 39.5 -102.8
0 1200.0 39.5 -102.7
0 1201.0 39.5 -102.6
0 1202.0 39.5 -102.5
0 1203.0 39.5 -102.4
0 1204.0 39.5 -102.3
0 1205.0 39.5 -102.2
0 1206.0 39.5 -102.1
0 1207.0 39.5 -102.0
0 1208.0 39.4 -109.0
0 1209.0 39.4 -108.9
0 1210.0 39.4 -108.8
0 1211.0 39.4 -108.7
0 1212.0 39.4 -108.6
0 1213.0 39.4 -108.5
0 1214.0 39.4 -108.4
0 1215.0 39.4 -108.3
0 1216.0 39.4 -108.2
0 1217.0 39.4 -108.1
0 1218.0 39.4 -108.0
0 1219.0 39.4 -107.9
0 1220.0 39.4 -107.8
0 1221.0 39.4 -107.7
0 1222.0 39.4 -107.6
0 1223.0 39.4 -107.5
0 1224.0 39.4 -107.4
0 1225.0 39.4 -107.3
0 1226.0 39.4 -107.2
0 1227.0 39.4 -107.1
0 1228.0 39.4 -107.0
0 1229.0 39.4 -106.9
0 1230.0 39.4 -106.8
0 1231.0 39.4 -106.7
0 1232.0 39.4 -106.6
0 1233.0 39.4 -106.5
0 1234.0 39.4 -106.4
0 1235.0 39.4 -106.3
0 1236.0 39.4 -106.2
0 1237.0 39.4 -106.1
0 1238.0 39.4 -106.0
0 1239.0 39.4 -105.9
0 1240.0 39.4 -105.8
0 1241.0 39.4 -105.7
0 1242.0 39.4 -105.6
0 1243.0 39.4 -105.5
0 1244.0 39.4 -105.4
0 1245.0 39.4 -105.3
0 1246.0 39.4 -105.2
0 1247.0 39.4 -105.1
0 1248.0 39.4 -105.0
0 1249.0 39.4 -104.9
0 1250.0 39.4 -104.8
0 1251.0 39.4 -104.7
0 1252.0 39.4 -104.6
0 1253.0 39.4 -104.5
0 1254.0 39.4 -104.4
0 1255.0 39.4 -104.3
0 1256.0 39.4 -104.2
0 1257.0 39.4 -104.1
0 1258.0 39.4 -104.0
0 1259.0 39.4 -103.9
0 1260.0 39.4 -103.8
0 1261.0 39.4 -103.7
0 1262.0 39.4 -103.6
0 1263.0 39.4 -103.5
0 1264.0 39.4 -103.4
0 1265.0 39.4 -103.3
0 1266.0 39.4 -103.2
0 1267.0 39.4 -103.1
0 1268.0 39.4 -103.0
0 1269.0 39.4 -102.9
0 1270.0 39.4 -102.8
0 1271.0 39.4 -102.7
0 1272.0 39.4 -102.6
0 1273.0 39.4 -102.5
0 1274.0 39.4 -102.4
0 1275.0 39.4 -102.3
0 1276.0 39.4 -102.2
0 1277.0 39.4 -102.1
0 1278.0 39.4 -102.0
0 1279.0 39.3 -109.0
0 1280.0 39.3 -108.9
0 1281.0 39.3 -108.8
0 1282.0 39.3 -108.7
0 1283.0 39.3 -108.6
0 1284.0 39.3 -108.5
0 1285.0 39.3 -108.4
0 1286.0 39.3 -108.3
0 1287.0 39.3 -108.2
0 1288.0 39.3 -108.1
0 1289.0 39.3 -108.0
0 1290.0 39.3 -107.9
0 1291.0 39.3 -107.8
0 1292.0 39.3 -107.7
0 1293.0 39.3 -107.6
0 1294.0 39.3 -107.5
0 1295.0 39.3 -107.4
0 1296.0 39.3 -107.3
0 1297.0 39.3 -107.2
0 1298.0 39.3 -107.1
0 1299.0 39.3 -107.0
0 1300.0 39.3 -106.9
0 1301.0 39.3 -106.8
0 1302.0 39.3 -106.7
0 1303.0 39.3 -106.6
0 1304.0 39.3 -106.5
0 1305.0 39.3 -106.4
0 1306.0 39.3 -106.3
0 1307.0 39.3 -106.2
0 1308.0 39.3 -106.1
0 1309.0 39.3 -106.0
0 1310.0 39.3 -105.9
0 1311.0 39.3 -105.8
0 1312.0 39.3 -105.7
0 1313.0 39.3 -105.6
0 1314.0 39.3 -105.5
0 1315.0 39.3 -105.4
0 1316.0 39.3 -105.3
0 1317.0 39.3 -105.2
0 1318.0 39.3 -105.1
0 1319.0 39.3 -105.0
0 1320.0 39.3 -104.9
0 1321.0 39.3 -104.8
0 1322.0 39.3 -104.7
0 1323.0 39.3 -104.6
0 1324.0 39.3 -104.5
0 1325.0 39.3 -104.4
0 1326.0 39.3 -104.3
0 1327.0 39.3 -104.2
0 1328.0 39.3 -104.1
0 1329.0 39.3 -104.0
0 1330.0 39.3 -103.9
0 1331.0 39.3 -103.8
0 1332.0 39.3 -103.7
0 1333.0 39.3 -103.6
0 1334.0 39.3 -103.5
0 1335.0 39.3 -103.4
0 1336.0 39.3 -103.3
0 1337.0 39.3 -103.2
0 1338.0 39.3 -103.1
0 1339.0 39.3 -103.0
0 1340.0 39.3 -102.9
0 1341.0 39.3 -102.8
0 1342.0 39.3 -102.7
0 1343.0 39.3 -102.6
0 1344.0 39.3 -102.5
0 1345.0 39.3 -102.4
0 1346.0 39.3 -102.3
0 1347.0 39.3 -102.2
0 1348.0 39.3 -102.1
0 1349.0 39.3 -102.0
0 1350.0 39.2 -109.0
0 1351.0 39.2 -108.9
0 1352.0 39.2 -108.8
0 1353.0 39.2 -108.7
0 1354.0 39.2 -108.6
0 1355.0 39.2 -108.5
0 1356.0 39.2 -108.4
0 1357.0 39.2 -108.3
0 1358.0 39.2 -108.2
0 1359.0 39.2 -108.1
0 1360.0 39.2 -108.0
0 1361.0 39.2 -107.9
0 1362.0 39.2 -107.8
0 1363.0 39.2 -107.7
0 1364.0 39.2 -107.6
0 1365.0 39.2 -107.5
0 1366.0 39.2 -107.4
0 1367.0 39.2 -107.3
0 1368.0 39.2 -107.2
0 1369.0 39.2 -107.1
0 1370.0 39.2 -107.0
0 1371.0 39.2 -106.9
0 1372.0 39.2 -106.8
0 1373.0 39.2 -106.7
0 1374.0 39.2 -106.6
0 1375.0 39.2 -106.5
0 1376.0 39.2 -106.4
0 1377.0 39.2 -106.3
0 1378.0 39.2 -106.2
0 1379.0 39.2 -106.1
0 1380.0 39.2 -106.0
0 1381.0 39.2 -105.9
0 1382.0 39.2 -105.8
0 1383.0 39.2 -105.7
0 1384.0 39.2 -105.6
0 1385.0 39.2 -105.5
0 1386.0 39.2 -105.4
0 1387.0 39.2 -105.3
0 1388.0 39.2 -105.2
0 1389.0 39.2 -105.1
0 1390.0 39.2 -105.0
0 1391.0 39.2 -104.9
0 1392.0 39.2 -104.8
0 1393.0 39.2 -104.7
0 1394.0 39.2 -104.6
0 1395.0 39.2 -104.5
0 1396.0 39.2 -104.4
0 1397.0 39.2 -104.3
0 1398.0 39.2 -104.2
0 1399.0 39.2 -104.1
0 1400.0 39.2 -104.0
0 1401.0 39.2 -103.9
0 1402.0 39.2 -103.8
0 1403.0 39.2 -103.7
0 1404.0 39.2 -103.6
0 1405.0 39.2 -103.5

In [51]:
dfll.loc[dfll['point']==447]

     point   lat    lon
447    447  40.5 -106.9

In [57]:
dfz["point"].value_counts().sort_index(ascending=True)

point
1       1
2       1
3       1
4       1
5       1
       ..
2978    1
2979    1
2980    1
2981    1
2982    1
Name: count, Length: 2982, dtype: int64

In [39]:
print(dfll['lat'].min(),dfll['lat'].max(),dfll['lon'].min(),dfll['lon'].max()   )
print(dfz['latitude'].min(),dfz['latitude'].max(),dfz['longitude'].min(),dfz['longitude'].max()   )

37.0 41.1 -109.0 -102.0
37.0 41.1 -109.0 -102.0

In [27]:
dfz.dtypes

latitude       float64
longitude      float64
elevation_m    float64
point            int64
dtype: object

In [58]:
print(dfz['point'].min(),dfz['point'].max())
print(dfll['point'].min(),dfll['point'].max())

1 2982
0 2981