In [3]:
import sqlite3
import pandas as pd
DST_DB = "/home/joe/work/Fire/ML/Data/DB/wx_daily_2982.sqlite"
conn = sqlite3.connect(DST_DB)

df = pd.read_sql_query("SELECT * FROM daily_data WHERE point_id = 500", conn)
print(df.head())

              datetime  point_id variable     value
0  2001-12-31 00:00:00       500        v -0.512909
1  2002-01-01 00:00:00       500        v -0.688873
2  2002-01-02 00:00:00       500        v -1.082031
3  2002-01-03 00:00:00       500        v  0.179352
4  2002-01-04 00:00:00       500        v -0.218304

In [4]:
df.shape

(61745, 4)

In [8]:
df['variable'].value_counts()

variable
v      12879
Td     12879
u      12879
T      12879
pcp    10229
Name: count, dtype: int64

In [10]:
(2024-1990+1)*365+31+28+31+30

12895

In [5]:
import pandas as pd
df=pd.read_csv("https://data.colorado.gov/resource/xmxb-7wfn.csv")

In [6]:
df.head()

,year,naics_code,industry,number_of_returns_aggregate,number_of_taxpayers_aggregate,federal_taxable_income,colorado_taxable_income,colorado_gross_tax_aggregate,colorado_net_tax_aggregate,number_of_returns_average,number_of_taxpayers_average,federal_taxable_income_average,colorado_taxable_income_1,colorado_gross_tax_average,colorado_net_tax_average
0,2022,11,"Agriculture, Forestry, Fishing and Hunting",988.0,988.0,4.151800e+08,2.278920e+07,3602566.0,3293842.0,988.0,988.0,420223.0,23066.0,3646.0,3334.0
1,2022,21,"Mining, Quarrying, and Oil and Gas Extraction",748.0,742.0,4.536545e+10,2.754260e+08,21782509.0,20848813.0,748.0,742.0,60649000.0,368217.0,29121.0,27873.0
2,2022,22,Utilities,222.0,221.0,-2.209532e+09,-2.478924e+08,2263005.0,2240669.0,222.0,221.0,-9952846.0,-1116633.0,10194.0,10093.0
3,2022,23,Construction,2261.0,2258.0,1.910170e+10,7.421296e+08,41317396.0,40300240.0,2261.0,2258.0,8448342.0,328231.0,18274.0,17824.0
4,2022,31-33,Manufacturing,4433.0,4418.0,5.668387e+11,3.935548e+09,220991031.0,212950424.0,4433.0,4418.0,127867962.0,887784.0,49851.0,48038.0

In [7]:
df['year'].value_counts()

year
2021    31
2019    31
2020    31
2023    29
2022    28
Name: count, dtype: int64

In [8]:
df.head()

,year,naics_code,industry,number_of_returns_aggregate,number_of_taxpayers_aggregate,federal_taxable_income,colorado_taxable_income,colorado_gross_tax_aggregate,colorado_net_tax_aggregate,number_of_returns_average,number_of_taxpayers_average,federal_taxable_income_average,colorado_taxable_income_1,colorado_gross_tax_average,colorado_net_tax_average
0,2022,11,"Agriculture, Forestry, Fishing and Hunting",988.0,988.0,4.151800e+08,2.278920e+07,3602566.0,3293842.0,988.0,988.0,420223.0,23066.0,3646.0,3334.0
1,2022,21,"Mining, Quarrying, and Oil and Gas Extraction",748.0,742.0,4.536545e+10,2.754260e+08,21782509.0,20848813.0,748.0,742.0,60649000.0,368217.0,29121.0,27873.0
2,2022,22,Utilities,222.0,221.0,-2.209532e+09,-2.478924e+08,2263005.0,2240669.0,222.0,221.0,-9952846.0,-1116633.0,10194.0,10093.0
3,2022,23,Construction,2261.0,2258.0,1.910170e+10,7.421296e+08,41317396.0,40300240.0,2261.0,2258.0,8448342.0,328231.0,18274.0,17824.0
4,2022,31-33,Manufacturing,4433.0,4418.0,5.668387e+11,3.935548e+09,220991031.0,212950424.0,4433.0,4418.0,127867962.0,887784.0,49851.0,48038.0

In [11]:
print(df['industry'].value_counts().sort_index())

industry
Accommodation                                                                               5
Administrative and Support and Waste Management and Remediation Services                    5
Agriculture, Forestry, Fishing and Hunting                                                  5
Arts, Entertainment, and Recreation                                                         5
Building Material and Garden Equipment and Supplies Dealers                                 5
Clothing and Clothing Accessories Stores                                                    3
Clothing, Clothing Accessories, Shoe, and Jewelry Retailers                                 2
Construction                                                                                5
Educational Services                                                                        5
Electronics and Appliance Stores                                                            3
Finance and Insurance                                                                       5
Food Services and Drinking Places                                                           5
Food and Beverage Retailers                                                                 2
Food and Beverage Stores                                                                    3
Furniture and Home Furnishings Stores                                                       3
Furniture, Home Furnishings, Electronics, and Appliance Retailers                           2
Gasoline Stations                                                                           3
Gasoline Stations and Fuel Dealers                                                          2
General Merchandise Retailers                                                               2
General Merchandise Stores                                                                  3
Health Care and Social Assistance                                                           5
Health and Personal Care Retailers                                                          2
Health and Personal Care Stores                                                             3
Information                                                                                 5
Management of Companies and Enterprises; \nOther Services (except Public Administration)    1
Management of Companies and Enterprises; Other Services (except Public Administration)      4
Manufacturing                                                                               5
Mining, Quarrying, and Oil and Gas Extraction                                               5
Miscellaneous Store Retailers                                                               3
Motor Vehicle and Parts Dealers                                                             5
Nonstore Retailers                                                                          3
Not Applicable                                                                              1
Professional, Scientific, and Technical Services                                            5
Public Administration                                                                       5
Real Estate and Rental and Leasing                                                          5
Sporting Goods, Hobby, Musical Instrument, Book, and Miscellaneous Retailers                2
Sporting Goods, Hobby, Musical Instrument, and Book Stores                                  3
Transportation and Warehousing                                                              5
Utilities                                                                                   5
Wholesale Trade                                                                             5
Name: count, dtype: int64