In [1]:
import pandas as pd

In [8]:
df= pd.read_csv("/home/joe/bic_etl/cdor/revenue_marijuana/data_source/State Retail Marijuana Sales Tax Revenue by County in Colorado County Report.csv",header=2)

In [9]:
df.head()

,Revenue Month,Revenue Year,County,Medical Marijuana \nState Sales Tax,Retail Marijuana \nState Sales Tax ²,State Share of Retail Marijuana Sales Tax ³
0,4,2025.0,Total,"$230,638",NaN,"$15,119,875"
1,4,2025.0,Adams,"$4,995",NaN,"$1,465,678"
2,4,2025.0,Alamosa,NR,NaN,NaN
3,4,2025.0,Arapahoe,"$8,447",NaN,"$1,964,953"
4,4,2025.0,Archuleta,NaN,NaN,"$89,483"

In [10]:
df.columns

Index(['Revenue Month', 'Revenue Year', 'County',
       'Medical Marijuana \nState Sales Tax',
       'Retail Marijuana \nState Sales Tax ²',
       'State Share of Retail Marijuana Sales Tax ³'],
      dtype='object')

In [ ]:
df.columns = df.columns.str.replace(' ', '_')

In [16]:
df.columns=df.columns.str.replace('\n', '')

In [17]:
df.columns

Index(['Revenue Month', 'Revenue Year', 'County',
       'Medical Marijuana State Sales Tax',
       'Retail Marijuana State Sales Tax ²',
       'State Share of Retail Marijuana Sales Tax ³'],
      dtype='object')

In [ ]:
df.replace(
    '

In [11]:
dfCim=pd.read_csv("https://data.colorado.gov/resource/v9m8-x8dh.csv?$limit=1000000")

In [12]:
dfCim.shape

(5599, 9)

In [13]:
dfCim.head()

,month,year,county,med_sales_tax,med_code,retail_sales_tax,retail_code,state_share_retail_tax,state_share_blank_code
0,5,2023,Bent,NaN,NR,NaN,NaN,41784.0,NaN
1,5,2023,Mesa,NaN,NR,NaN,NaN,355473.0,NaN
2,5,2023,Adams,10424.0,NaN,NaN,NaN,1413261.0,NaN
3,5,2023,Pitkin,NaN,NR,NaN,NaN,103985.0,NaN
4,5,2023,Huerfano,NaN,NaN,NaN,NaN,58264.0,NaN

In [14]:
dfCim.columns

Index(['month', 'year', 'county', 'med_sales_tax', 'med_code',
       'retail_sales_tax', 'retail_code', 'state_share_retail_tax',
       'state_share_blank_code'],
      dtype='object')