In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("Port_Data_20251112.csv")

## Top 5 Farm/Food Analsysis

In [3]:
df.head()

,Cargo Type,Port ID,Port_Name,Region,Reporting Year,State,Trade Type,Units,Port Ranking,Percent Change,Volume
0,CONTAINER,"4,820","Alaska, AK Port of",Pacific Coast,2016,Alaska,EMPTY,Container TEUs,18.0,42.91847184,"58,059.2"
1,CONTAINER,"4,820","Alaska, AK Port of",Pacific Coast,2016,Alaska,EXPORTS,Container TEUs,18.0,-5.893463975,"71,169.95"
2,CONTAINER,"4,820","Alaska, AK Port of",Pacific Coast,2016,Alaska,IMPORTS,Container TEUs,18.0,-16.02295603,"205,662.3"
3,CONTAINER,"4,820","Alaska, AK Port of",Pacific Coast,2016,Alaska,TOTAL,Container TEUs,18.0,-7.271842483,"334,891.45"
4,DRY BULK,"4,820","Alaska, AK Port of",Pacific Coast,2016,Alaska,DOMESTIC,Short Tons,161.0,-10.15539526,"96,901"

In [5]:
df['Cargo Type'].unique()

array(['CONTAINER', 'DRY BULK', 'TOTAL TONNAGE', 'TOP 5 COMMODITIES',
       'TOP 5 FOOD/FARM COMMODITIES', 'VESSEL CALLS'], dtype=object)

In [6]:
farm=df[df['Cargo Type']=='TOP 5 FOOD/FARM COMMODITIES']

In [7]:
farm.head()

,Cargo Type,Port ID,Port_Name,Region,Reporting Year,State,Trade Type,Units,Port Ranking,Percent Change,Volume
85,TOP 5 FOOD/FARM COMMODITIES,"4,820","Alaska, AK Port of",Pacific Coast,2021,Alaska,Alcoholic Beverages,Short Tons,NaN,-4.044411462,"33,619"
86,TOP 5 FOOD/FARM COMMODITIES,"4,820","Alaska, AK Port of",Pacific Coast,2021,Alaska,Bananas & Plantains,Short Tons,NaN,15.146206711,"8,545"
87,TOP 5 FOOD/FARM COMMODITIES,"4,820","Alaska, AK Port of",Pacific Coast,2021,Alaska,Fish (Not Shellfish),Short Tons,NaN,877.975739196,"25,799"
88,TOP 5 FOOD/FARM COMMODITIES,"4,820","Alaska, AK Port of",Pacific Coast,2021,Alaska,Food Products NEC,Short Tons,NaN,11.430780475,"184,477"
89,TOP 5 FOOD/FARM COMMODITIES,"4,820","Alaska, AK Port of",Pacific Coast,2021,Alaska,Groceries,Short Tons,NaN,8.055564315,"68,531"

In [12]:
farmCom = list(farm['Trade Type'].unique())

In [13]:
farmCom

['Alcoholic Beverages',
 'Bananas & Plantains',
 'Fish (Not Shellfish)',
 'Food Products NEC',
 'Groceries',
 'TOTAL',
 'Animal Feed, Prep.',
 'Soybeans',
 'Sugar',
 'Meat, Fresh, Frozen',
 'Vegetable Oils',
 'Vegetables & Prod.',
 'Grain Mill Products',
 'Shellfish',
 'Sorghum Grains',
 'Wheat Flour',
 'Oats',
 'Wheat',
 'Corn',
 'Oilseeds NEC',
 'Rice',
 'Coffee',
 'Cotton',
 'Hay & Fodder',
 'Fruit Juices',
 'Fruit & Nuts NEC',
 'Cocoa Beans',
 'Water & Ice',
 'Dairy Products',
 'Farm Products NEC',
 'Molasses',
 'Peanuts',
 'Fish, Prepared']

In [17]:
df2023Com = pd.read_excel("PortPerformance2023.xlsx",sheet_name= 'Ports by Commodity')

In [15]:
df2023.head()

,RANK,TYPE,PORT NAME,GRAND TOTAL,FOREIGN TOTAL,IMPORTS,EXPORTS,DOMESTIC
0,1,Coastal,"Houston Port Authority, TX",309531236,229019431,61307109,167712322,80511805
1,2,Coastal,"South Louisiana, LA, Port of",217531611,108400804,32432311,75968493,109130807
2,3,Coastal,"Corpus Christi, TX",189775751,163695289,15768907,147926382,26080462
3,4,Coastal,"New York, NY & NJ",132289509,89870204,74145286,15724918,42419305
4,5,Coastal,"Beaumont, TX",87879130,60943610,15995662,44947948,26935520

In [18]:
df2023Com.shape

(8510, 10)

In [19]:
df2023Com.head()

,TYPE,PORT,Port Name,Commodity Group,Commodity Name,DOMESTIC,FOREIGN,IMPORTS,EXPORTS,TOTAL
0,Internal,2359,"Aberdeen, MS",2211,Gasoline,137352,0,0,0,137352
1,Internal,2359,"Aberdeen, MS",2330,Distillate Fuel Oil,110527,0,0,0,110527
2,Internal,2359,"Aberdeen, MS",3220,Alcohols,17198,0,0,0,17198
3,Great Lakes,3612,"Alabaster Township, MI",4323,Gypsum,212416,0,0,0,212416
4,Coastal,505,"Albany Port District, NY",2211,Gasoline,2068708,0,0,0,2068708

In [20]:
df2023Com['Port Name'].value_counts()

Port Name
Houston Port Authority, TX    140
New York, NY & NJ             139
Virginia, VA, Port of         138
Port of Long Beach, CA        138
Port of Los Angeles, CA       137
                             ...
Fajardo, PR                     1
Gloucester, MA                  1
St. Ignace, MI                  1
Alabaster Township, MI          1
Yazoo County Port, MS           1
Name: count, Length: 300, dtype: int64

In [22]:
farmX23=df2023Com.loc[df2023Com['Commodity Name'].isin(farmCom)]

In [30]:
farmX23Grps=farmX23['Commodity Group'].value_counts().to_dict()

In [ ]:
farmX23.loc[farmX23['Commodity Group'] == farmX23['Commodity Group'].unique()]

In [39]:
for grp in sorted(farmX23Grps.keys()):
    print("GROUP ",grp,end='')
    tmp=farmX23.loc[farmX23['Commodity Group'] == grp]
    for k,v in tmp['Commodity Name'].value_counts().to_dict().items():
        print("   ",k,v)

GROUP  6134    Fish (Not Shellfish) 65
GROUP  6136    Shellfish 47
GROUP  6241    Wheat 81
GROUP  6344    Corn 90
GROUP  6442    Rice 69
GROUP  6445    Oats 21
GROUP  6447    Sorghum Grains 21
GROUP  6521    Peanuts 19
GROUP  6522    Soybeans 95
GROUP  6590    Oilseeds NEC 55
GROUP  6653    Vegetable Oils 72
GROUP  6654    Vegetables & Prod. 78
GROUP  6746    Wheat Flour 32
GROUP  6747    Grain Mill Products 69
GROUP  6781    Hay & Fodder 39
GROUP  6782    Animal Feed, Prep. 105
GROUP  6811    Meat, Fresh, Frozen 48
GROUP  6822    Dairy Products 45
GROUP  6835    Fish, Prepared 47
GROUP  6856    Bananas & Plantains 34
GROUP  6857    Fruit & Nuts NEC 43
GROUP  6858    Fruit Juices 45
GROUP  6861    Sugar 45
GROUP  6865    Molasses 35
GROUP  6871    Coffee 38
GROUP  6872    Cocoa Beans 27
GROUP  6885    Alcoholic Beverages 71
GROUP  6887    Groceries 37
GROUP  6888    Water & Ice 42
GROUP  6889    Food Products NEC 78
GROUP  6893    Cotton 31
GROUP  6899    Farm Products NEC 51

In [32]:
farmX23.head()

,TYPE,PORT,Port Name,Commodity Group,Commodity Name,DOMESTIC,FOREIGN,IMPORTS,EXPORTS,TOTAL
22,Coastal,505,"Albany Port District, NY",6241,Wheat,0,157364,157364,0,157364
30,Internal,2308,"Alexandria-Cairo Port, IL",6241,Wheat,36134,0,0,0,36134
31,Internal,2308,"Alexandria-Cairo Port, IL",6344,Corn,36055,0,0,0,36055
32,Internal,2308,"Alexandria-Cairo Port, IL",6522,Soybeans,66934,0,0,0,66934
33,Internal,2308,"Alexandria-Cairo Port, IL",6590,Oilseeds NEC,501436,0,0,0,501436

## Rank Analysis

In [40]:
df.columns

Index(['Cargo Type', 'Port ID', 'Port_Name', 'Region', 'Reporting Year',
       'State', 'Trade Type', 'Units', 'Port Ranking', 'Percent Change',
       'Volume'],
      dtype='object')

In [42]:
df['Port Ranking'].value_counts().sort_index()

Port Ranking
1.0      84
2.0      84
3.0      84
4.0      84
5.0      84
         ..
229.0     5
231.0     5
238.0     5
242.0     5
248.0     5
Name: count, Length: 133, dtype: int64

In [44]:
df['Port_Name'].value_counts().sort_index()

Port_Name
Alaska, AK Port of                                                 118
Baltimore, MD                                                      118
Beaumont, TX                                                        94
Boston, MA                                                         118
Cincinnati-Northern KY, Ports of                                    67
Cleveland-Cuyahoga Port, OH                                         68
Corpus Christi, TX                                                  98
Duluth-Superior, MN and WI                                          98
Greater Baton Rouge, LA Port of                                     94
Gulfport, MS                                                        82
Honolulu, O'ahu, HI                                                118
Houston Port Authority, TX                                         118
Huntington-Tristate, KY, OH, WV                                     61
Illinois Waterway Ports and Terminals Port Statistical Area, IL     27
Jacksonville, FL                                                   118
Kalama, WA Port of                                                  93
Lake Charles Harbor District, LA                                    96
Long Beach, CA Port of                                             118
Longview, WA Port of                                                97
Los Angeles, CA Port of                                            118
Mid-America Port Commission                                         64
Mid-Ohio Valley Port, OH and WV                                     26
Mobile, AL                                                         118
New Bourbon Port, MO                                                50
New Orleans, LA                                                    118
New York, NY & NJ                                                  118
Northern Indiana, IN                                                86
Oakland, CA Port of                                                118
Philadelphia Regional Port, PA                                     118
Pittsburgh, PA Port of                                              84
Plaquemines Port District, LA                                       98
Port Arthur, TX                                                     97
Port Everglades, FL                                                118
Port Freeport, TX                                                  118
Port of Charleston, SC                                             118
Port of Palm Beach District, FL                                     82
Port of Portland, OR                                               102
PortMiami, FL                                                      103
San Juan, PR                                                       118
Savannah, GA Port of                                               118
Seattle, WA                                                        118
South Jersey Port, NJ                                               62
South Louisiana, LA, Port of                                        98
Southern Indiana Maritime District, IN                              27
St. Louis, MO and IL                                                67
Tacoma, WA                                                         118
Tampa Port Authority, FL                                           118
Texas City, TX                                                      98
Toledo-Lucas County Port, OH                                        67
Two Harbors, MN                                                     77
Valdez, AK                                                          94
Virginia, VA, Port of                                              118
Wilmington, DE                                                     118
Wilmington, NC                                                     118
Name: count, dtype: int64

In [46]:
hstn=df.loc[df['Port_Name']=='Houston Port Authority, TX']

In [50]:
hstn

,Cargo Type,Port ID,Port_Name,Region,Reporting Year,State,Trade Type,Units,Port Ranking,Percent Change,Volume
907,CONTAINER,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2016,Texas,EMPTY,Container TEUs,8.0,-100,0
908,CONTAINER,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2016,Texas,EXPORTS,Container TEUs,8.0,1.326110508,"920,322.77"
909,CONTAINER,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2016,Texas,IMPORTS,Container TEUs,8.0,6.356019641,"898,461.62"
910,CONTAINER,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2016,Texas,TOTAL,Container TEUs,8.0,3.74640153,"1,818,784.39"
911,DRY BULK,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2016,Texas,DOMESTIC,Short Tons,11.0,-9.690925299,"4,044,109"
...,...,...,...,...,...,...,...,...,...,...,...
5009,VESSEL CALLS,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2020,Texas,Container,Vessel Calls,NaN,4.360902256,"1,041"
5010,VESSEL CALLS,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2020,Texas,Dry Bulk,Vessel Calls,NaN,-15.45454546,511.5
5011,VESSEL CALLS,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2020,Texas,Dry Bulk Barge,Vessel Calls,NaN,-9.278106509,"1,916.5"
5012,VESSEL CALLS,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2020,Texas,Other Freight,Vessel Calls,NaN,-4.432605221,"4,484.5"
5013,VESSEL CALLS,"2,031","Houston Port Authority, TX",Gulf Coast & Mississippi River,2020,Texas,Other Freight Barge,Vessel Calls,NaN,-15.94168069,"20,986"

In [49]:
hstn['Port Ranking']

907      8.0
908      8.0
909      8.0
910      8.0
911     11.0
        ...
5009     NaN
5010     NaN
5011     NaN
5012     NaN
5013     NaN
Name: Port Ranking, Length: 118, dtype: float64

## 2021

In [53]:
df2021 = df.loc[df['Reporting Year'] == 2021]

In [54]:
df2021.shape

(1421, 11)