In [2]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)
pd.options.mode.chained_assignment = None

In [8]:
df = pd.read_csv("portCatalogUpdateFinal2.csv")
dfO = pd.read_csv("portCatalogUpdate.csv")

In [4]:
df.head()

,Cargo Type,Port ID,Port_Name,Region,Reporting Year,State,Trade Type,Units,Port Ranking,Percent Change,Volume
0,CONTAINER,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,EMPTY,Container TEUs,18.0,42.91847184,58059.2
1,CONTAINER,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,EXPORTS,Container TEUs,18.0,-5.893463975,71169.95
2,CONTAINER,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,IMPORTS,Container TEUs,18.0,-16.02295603,205662.3
3,CONTAINER,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,TOTAL,Container TEUs,18.0,-7.2718424829999995,334891.45
4,DRY BULK,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,DOMESTIC,Short Tons,161.0,-10.15539526,96901.0

In [5]:
df.isna().sum()

Cargo Type           0
Port ID              0
Port_Name            0
Region              93
Reporting Year       0
State                0
Trade Type           0
Units                0
Port Ranking      1604
Percent Change       0
Volume             145
dtype: int64

In [9]:
print(df["Reporting Year"].value_counts())
print(dfO["Reporting Year"].value_counts())

2020    1465
2021    1421
2019     588
2018     583
2017     583
2016     549
Name: Reporting Year, dtype: int64
2021    1421
2020     646
2019     588
2018     583
2017     583
2016     549
Name: Reporting Year, dtype: int64

In [7]:
df["Cargo Type"].value_counts()

TOTAL TONNAGE                  1445
DRY BULK                       1440
CONTAINER                       700
TOP 5 COMMODITIES               583
TOP 5 FOOD/FARM COMMODITIES     531
VESSEL CALLS                    490
Name: Cargo Type, dtype: int64

In [11]:
ports=[]
for port in df["Port_Name"].unique():
    tmp = df.loc[df["Port_Name"] == port]
    np=tmp["Port ID"].nunique()
    if np > 1:
       print(port)
       ports.append(port)
       print(tmp["Port ID"].unique())
       print("------------------------")
       print("")

Corpus Christi, TX
[2423 2436]
------------------------

Honolulu, O'ahu, HI
[4420 4421]
------------------------

Mobile, AL
[2005 2032]
------------------------

PortMiami, FL
[2164 1992]
------------------------

Tacoma, WA
[4720 4719]
------------------------

Wilmington, DE
[554 555]
------------------------

In [12]:
ports

['Corpus Christi, TX',
 "Honolulu, O'ahu, HI",
 'Mobile, AL',
 'PortMiami, FL',
 'Tacoma, WA',
 'Wilmington, DE']

In [17]:
for port in ports:
    print(port)
    print(df.loc[(df["Port_Name"] == port) & (df["Reporting Year"] == 2020),"Port ID"].unique())

Corpus Christi, TX
[2436]
Honolulu, O'ahu, HI
[4421]
Mobile, AL
[2032]
PortMiami, FL
[1992]
Tacoma, WA
[4719]
Wilmington, DE
[555]

In [24]:
print(df.loc[df["Port_Name"] == "Corpus Christi, TX",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "Honolulu, O'ahu, HI",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "Mobile, AL",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "PortMiami, FL",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "Tacoma, WA",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "Wilmington, DE",'Port ID'].unique())

[2436]
[4420 4421]
[2005 2032]
[2164 1992]
[4720 4719]
[554 555]

In [25]:

df.loc[df["Port_Name"] == "Corpus Christi, TX",'Port ID'] = 2436
df.loc[df["Port_Name"] == "Honolulu, O'ahu, HI",'Port ID'] = 4431
df.loc[df["Port_Name"] == "Mobile, AL",'Port ID'] = 2032
df.loc[df["Port_Name"] == "PortMiami, FL",'Port ID'] = 1992
df.loc[df["Port_Name"] == "Tacoma, WA",'Port ID'] = 4719
df.loc[df["Port_Name"] == "Wilmington, DE",'Port ID'] = 555

In [21]:
df.loc[df["Port_Name"] == "Corpus Christi, TX",'Port ID'].unique()

array([2436])

In [26]:
print(df.loc[df["Port_Name"] == "Corpus Christi, TX",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "Honolulu, O'ahu, HI",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "Mobile, AL",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "PortMiami, FL",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "Tacoma, WA",'Port ID'].unique())
print(df.loc[df["Port_Name"] == "Wilmington, DE",'Port ID'].unique())

[2436]
[4431]
[2032]
[1992]
[4719]
[555]

In [28]:
ports=[]
for port in df["Port_Name"].unique():
    tmp = df.loc[df["Port_Name"] == port]
    np=tmp["Port ID"].nunique()
    if np > 1:
       print(port)
       ports.append(port)
       print(tmp["Port ID"].unique())
       print("------------------------")
       print("")

In [30]:
df.shape

(4370, 11)

In [36]:
df.to_csv("portCatalogUpdateFinal.csv",index=False)

In [37]:
dfO = pd.read_csv("portCatalogUpdate.csv")
dfN= pd.read_csv("portCatalogUpdateFinal.csv")

In [38]:
print(dfO.shape)
print(dfN.shape)

(4370, 11)
(4370, 11)

In [39]:
dfN.head()

,Cargo Type,Port ID,Port_Name,Region,Reporting Year,State,Trade Type,Units,Port Ranking,Percent Change,Volume
0,CONTAINER,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,EMPTY,Container TEUs,18.0,42.91847184,58059.2
1,CONTAINER,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,EXPORTS,Container TEUs,18.0,-5.893463975,71169.95
2,CONTAINER,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,IMPORTS,Container TEUs,18.0,-16.02295603,205662.3
3,CONTAINER,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,TOTAL,Container TEUs,18.0,-7.2718424829999995,334891.45
4,DRY BULK,4820,"Alaska, AK Port of",Pacific Coast,2016,Alaska,DOMESTIC,Short Tons,161.0,-10.15539526,96901.0

In [43]:
print(dfO.compare(dfN))

     Port ID
        self   other
500   2423.0  2436.0
501   2423.0  2436.0
502   2423.0  2436.0
503   2423.0  2436.0
504   2423.0  2436.0
505   2423.0  2436.0
506   2423.0  2436.0
507   2423.0  2436.0
508   2423.0  2436.0
509   2423.0  2436.0
804   4420.0  4431.0
805   4420.0  4431.0
806   4420.0  4431.0
807   4420.0  4431.0
808   4420.0  4431.0
809   4420.0  4431.0
810   4420.0  4431.0
811   4420.0  4431.0
812   4420.0  4431.0
813   4420.0  4431.0
814   4420.0  4431.0
815   4420.0  4431.0
816   4420.0  4431.0
817   4420.0  4431.0
818   4421.0  4431.0
819   4421.0  4431.0
820   4421.0  4431.0
821   4421.0  4431.0
822   4421.0  4431.0
823   4421.0  4431.0
824   4421.0  4431.0
825   4421.0  4431.0
826   4421.0  4431.0
827   4421.0  4431.0
828   4421.0  4431.0
829   4421.0  4431.0
830   4421.0  4431.0
831   4421.0  4431.0
832   4421.0  4431.0
833   4421.0  4431.0
834   4421.0  4431.0
835   4421.0  4431.0
836   4421.0  4431.0
837   4421.0  4431.0
838   4421.0  4431.0
839   4421.0  4431.0
840   4421.0  4431.0
841   4421.0  4431.0
842   4421.0  4431.0
843   4421.0  4431.0
844   4421.0  4431.0
845   4421.0  4431.0
846   4421.0  4431.0
847   4421.0  4431.0
848   4421.0  4431.0
849   4421.0  4431.0
850   4421.0  4431.0
851   4421.0  4431.0
852   4421.0  4431.0
853   4421.0  4431.0
854   4421.0  4431.0
855   4421.0  4431.0
856   4421.0  4431.0
857   4421.0  4431.0
858   4421.0  4431.0
859   4421.0  4431.0
860   4421.0  4431.0
861   4421.0  4431.0
862   4421.0  4431.0
863   4421.0  4431.0
864   4421.0  4431.0
865   4421.0  4431.0
866   4421.0  4431.0
867   4421.0  4431.0
868   4421.0  4431.0
869   4421.0  4431.0
870   4421.0  4431.0
871   4421.0  4431.0
872   4421.0  4431.0
873   4421.0  4431.0
874   4421.0  4431.0
875   4421.0  4431.0
876   4421.0  4431.0
877   4421.0  4431.0
878   4421.0  4431.0
879   4421.0  4431.0
880   4421.0  4431.0
881   4421.0  4431.0
882   4421.0  4431.0
883   4421.0  4431.0
884   4421.0  4431.0
885   4421.0  4431.0
886   4421.0  4431.0
887   4421.0  4431.0
888   4421.0  4431.0
889   4421.0  4431.0
890   4421.0  4431.0
891   4421.0  4431.0
892   4421.0  4431.0
893   4421.0  4431.0
894   4421.0  4431.0
895   4421.0  4431.0
896   4421.0  4431.0
897   4421.0  4431.0
898   4421.0  4431.0
899   4421.0  4431.0
900   4421.0  4431.0
901   4421.0  4431.0
902   4421.0  4431.0
903   4421.0  4431.0
904   4421.0  4431.0
1661  2005.0  2032.0
1662  2005.0  2032.0
1663  2005.0  2032.0
1664  2005.0  2032.0
1665  2005.0  2032.0
1666  2005.0  2032.0
1667  2005.0  2032.0
1668  2005.0  2032.0
1669  2005.0  2032.0
1670  2005.0  2032.0
1671  2005.0  2032.0
1672  2005.0  2032.0
1673  2005.0  2032.0
1674  2005.0  2032.0
2967  2164.0  1992.0
2968  2164.0  1992.0
2969  2164.0  1992.0
2970  2164.0  1992.0
2971  2164.0  1992.0
2972  2164.0  1992.0
2973  2164.0  1992.0
2974  2164.0  1992.0
2975  2164.0  1992.0
3569  4720.0  4719.0
3570  4720.0  4719.0
3571  4720.0  4719.0
3572  4720.0  4719.0
3573  4720.0  4719.0
3574  4720.0  4719.0
3575  4720.0  4719.0
3576  4720.0  4719.0
3577  4720.0  4719.0
3578  4720.0  4719.0
3579  4720.0  4719.0
3580  4720.0  4719.0
3581  4720.0  4719.0
3582  4720.0  4719.0
4168   554.0   555.0
4169   554.0   555.0
4170   554.0   555.0
4171   554.0   555.0
4172   554.0   555.0
4173   554.0   555.0
4174   554.0   555.0
4175   554.0   555.0
4176   554.0   555.0
4177   554.0   555.0
4178   554.0   555.0
4179   554.0   555.0
4180   554.0   555.0
4181   554.0   555.0

In [44]:
dfN["Port_Name"].nunique()

55

In [45]:
dfN["Reporting Year"].value_counts()

2021    1421
2020     646
2019     588
2018     583
2017     583
2016     549
Name: Reporting Year, dtype: int64

In [46]:
dfN.shape

(4370, 11)