In [10]:
import pymongo
import pandas as pd
import statistics

In [2]:

def toMongo(collection,what): 
    db = client.Fire
    
    # use a collection named "recipes"
    my_collection = db[collection]
    
    try: 
     result = my_collection.insert_many(what)
    
    # return a friendly error if the operation fails
    except pymongo.errors.OperationFailure:
      print("An authentication error was received. Are you sure your database user is authorized to perform write operations?")
      sys.exit(1)
    else:
      inserted_count = len(result.inserted_ids)
      print("I inserted %x documents." %(inserted_count))
    
      print("\n")

def mongoConnect():    
    try:
      client = pymongo.MongoClient("mongodb+srv://jcomeaux:444Jayla.@cluster0.qjm0b.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0")
      
    # return a friendly error if a URI error is thrown 
    except pymongo.errors.ConfigurationError:
      print("An Invalid URI host error was received. Is your Atlas host name correct in your connection string?")
      sys.exit(1)
        
    return client

In [3]:
client=mongoConnect()
db = client.Fire
my_collection = db["VPD"]
result = my_collection.find()

# if result:    
#   for doc in result:
#     print(doc.keys())

cursor = my_collection.find()
list_cur = list(cursor)
df = pd.DataFrame(list_cur)

In [4]:
df[["testError","trainError","date","shuffle",'changeWeights',"statefule",'timesteps','batch_size',"epochBest"]].groupby(["date"]).mean()

,testError,trainError,shuffle,changeWeights,statefule,timesteps,batch_size,epochBest
date,,,,,,,,
2025-03-01 22:28:35.329,0.399214,0.076647,0.0,1.0,0.0,24.0,48.0,100.0
2025-03-01 22:39:16.267,0.383569,0.067069,1.0,1.0,0.0,24.0,48.0,100.0
2025-03-01 23:56:32.819,0.561570,0.130226,0.0,1.0,1.0,24.0,48.0,100.0
2025-03-02 00:06:18.922,0.414916,0.195531,1.0,1.0,1.0,24.0,48.0,100.0
2025-03-02 17:28:34.848,0.337342,0.073320,1.0,1.0,0.0,24.0,48.0,100.0
2025-03-02 19:52:04.810,0.344964,0.073510,1.0,1.0,0.0,24.0,48.0,100.0
2025-03-07 06:22:23.926,0.339176,0.077904,1.0,1.0,0.0,24.0,48.0,100.0
2025-03-07 06:43:29.912,0.442269,0.072244,1.0,1.0,0.0,24.0,48.0,100.0
2025-03-07 06:54:36.079,0.403008,0.083674,1.0,1.0,0.0,24.0,48.0,100.0
2025-03-07 06:59:56.363,0.336473,0.053912,1.0,1.0,0.0,24.0,48.0,200.0
2025-03-07 10:20:05.043,0.391399,0.109646,1.0,0.0,0.0,24.0,48.0,150.0
2025-03-15 11:10:56.177,0.402145,0.095394,1.0,0.0,0.0,24.0,48.0,150.0
2025-03-15 11:16:51.305,0.516161,0.089671,1.0,0.0,0.0,24.0,24.0,150.0
2025-03-15 11:25:38.045,0.532844,0.155134,0.0,0.0,0.0,24.0,24.0,150.0
2025-03-15 12:02:12.469,0.528034,0.147044,0.0,0.0,0.0,24.0,64.0,150.0
2025-03-15 12:08:21.327,0.565591,0.283127,0.0,0.0,0.0,12.0,48.0,150.0
2025-03-15 12:15:07.509,0.411421,0.265692,0.0,0.0,0.0,36.0,48.0,150.0
2025-03-15 12:33:11.002,0.520464,0.167129,0.0,0.0,1.0,24.0,48.0,150.0
2025-03-15 13:13:24.506,0.366937,0.149884,1.0,0.0,1.0,24.0,48.0,150.0
2025-03-15 13:24:41.203,0.388507,0.164288,1.0,1.0,1.0,24.0,48.0,150.0
2025-03-15 13:48:22.138,0.445933,0.156797,1.0,1.0,1.0,24.0,64.0,150.0
2025-03-15 13:58:39.002,0.352796,0.163105,1.0,1.0,1.0,24.0,56.0,150.0
2025-03-15 14:34:43.258,0.452933,0.192572,1.0,1.0,1.0,24.0,72.0,150.0
2025-03-15 19:20:38.876,0.333683,0.164334,1.0,1.0,1.0,24.0,60.0,150.0
2025-03-15 21:25:19.626,0.397991,0.165374,1.0,0.0,1.0,24.0,60.0,150.0
2025-03-15 21:50:12.836,0.409816,0.193522,0.0,0.0,1.0,24.0,56.0,150.0

In [6]:
df.head(100)

,_id,statefule,batch_size,forecast_period,features,timesteps,shuffle,TotalLength,learningRate,history,earlyStoppingLength,epochBest,changeWeights,date,testError,trainError,y_test,y_hat,neurons
0,67c3ec8f9f8c93b67411ab93,False,48,8,6,24,False,420,0.002,"{'loss': [0.0891372486948967, 0.07234407961368...",100,100,True,2025-03-01 22:28:35.329,0.406009,0.224982,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.6490093469619751, 0.4962880313396454, 0.330...",NaN
1,67c3ec9b9f8c93b67411ab94,False,48,8,6,24,False,420,0.002,"{'loss': [0.017181525006890297, 0.023382451385...",100,100,True,2025-03-01 22:28:35.329,0.364325,0.104216,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.5390886664390564, 0.44875937700271606, 0.27...",NaN
2,67c3eca89f8c93b67411ab95,False,48,8,6,24,False,420,0.002,"{'loss': [0.009490793570876122, 0.015723206102...",100,100,True,2025-03-01 22:28:35.329,0.383692,0.115948,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.44792526960372925, 0.3475313186645508, 0.22...",NaN
3,67c3ecb49f8c93b67411ab96,False,48,8,6,24,False,420,0.002,"{'loss': [0.011466928757727146, 0.010548892430...",100,100,True,2025-03-01 22:28:35.329,0.410618,0.070342,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.5522405505180359, 0.41050687432289124, 0.22...",NaN
4,67c3ecc19f8c93b67411ab97,False,48,8,6,24,False,420,0.002,"{'loss': [0.00421214010566473, 0.0083453562110...",100,100,True,2025-03-01 22:28:35.329,0.399200,0.071963,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.45166653394699097, 0.32198846340179443, 0.1...",NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,67cafc860eeb12a4eda25a37,False,48,8,6,24,True,420,0.002,"{'loss': [0.005865031853318214, 0.004401889629...",200,200,True,2025-03-07 06:59:56.363,0.337173,0.047012,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.4170529544353485, 0.2845374643802643, 0.150...",200.0
96,67cafca20eeb12a4eda25a38,False,48,8,6,24,True,420,0.002,"{'loss': [0.004515048116445541, 0.004864218644...",200,200,True,2025-03-07 06:59:56.363,0.337916,0.042767,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.44383105635643005, 0.28295499086380005, 0.1...",200.0
97,67cafcbf0eeb12a4eda25a39,False,48,8,6,24,True,420,0.002,"{'loss': [0.004425407387316227, 0.004526462405...",200,200,True,2025-03-07 06:59:56.363,0.347359,0.040141,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.43518325686454773, 0.2504746913909912, 0.09...",200.0
98,67cafcdc0eeb12a4eda25a3a,False,48,8,6,24,True,420,0.002,"{'loss': [0.00414975406602025, 0.0033692324068...",200,200,True,2025-03-07 06:59:56.363,0.346877,0.036488,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.4688717722892761, 0.25048303604125977, 0.07...",200.0
99,67cafcf80eeb12a4eda25a3b,False,48,8,6,24,True,420,0.002,"{'loss': [0.003184973495081067, 0.003212015144...",200,200,True,2025-03-07 06:59:56.363,0.344606,0.033941,"[0.41543625000000034, 0.25733643724696353, 0.1...","[0.5152192711830139, 0.2885827422142029, 0.101...",200.0

In [5]:
df["y_test"]

0      [0.41543625000000034, 0.25733643724696353, 0.1...
1      [0.41543625000000034, 0.25733643724696353, 0.1...
2      [0.41543625000000034, 0.25733643724696353, 0.1...
3      [0.41543625000000034, 0.25733643724696353, 0.1...
4      [0.41543625000000034, 0.25733643724696353, 0.1...
                             ...
255    [0.41543625000000034, 0.25733643724696353, 0.1...
256    [0.41543625000000034, 0.25733643724696353, 0.1...
257    [0.41543625000000034, 0.25733643724696353, 0.1...
258    [0.41543625000000034, 0.25733643724696353, 0.1...
259    [0.41543625000000034, 0.25733643724696353, 0.1...
Name: y_test, Length: 260, dtype: object

In [ ]:
df["y_test"].std()

In [13]:
def computeStats(row):
    test=row["y_test"]
    hat=row["y_hat"]
    testStd= statistics.stdev(test)
    hatStd= statistics.stdev(hat)
    dif = [abs(test[nn]-hat[nn]) for nn in range(len(test))]
    difStd=statistics.stdev(dif)
    row["y_test_std"],row["y_hat_std"],row["y_diff_std"] = testStd,hatStd,difStd
    return row

dfNew = df.apply(computeStats,axis=1)

In [19]:
dfNew[["testError","trainError","date","shuffle",'changeWeights',"statefule",'timesteps','batch_size',"epochBest", 'earlyStoppingLength',"neurons","y_test_std","y_hat_std","y_diff_std"]].groupby(["date"]).mean()

,testError,trainError,shuffle,changeWeights,statefule,timesteps,batch_size,epochBest,earlyStoppingLength,neurons,y_test_std,y_hat_std,y_diff_std
date,,,,,,,,,,,,,
2025-03-01 22:28:35.329,0.399214,0.076647,0.0,1.0,0.0,24.0,48.0,100.0,100.0,NaN,0.904374,0.656098,0.360454
2025-03-01 22:39:16.267,0.383569,0.067069,1.0,1.0,0.0,24.0,48.0,100.0,100.0,NaN,0.904374,0.751925,0.398999
2025-03-01 23:56:32.819,0.561570,0.130226,0.0,1.0,1.0,24.0,48.0,100.0,10.0,NaN,0.904374,0.438520,0.461256
2025-03-02 00:06:18.922,0.414916,0.195531,1.0,1.0,1.0,24.0,48.0,100.0,10.0,NaN,0.904374,0.663210,0.356666
2025-03-02 17:28:34.848,0.337342,0.073320,1.0,1.0,0.0,24.0,48.0,100.0,100.0,NaN,0.904374,0.664033,0.305860
2025-03-02 19:52:04.810,0.344964,0.073510,1.0,1.0,0.0,24.0,48.0,100.0,100.0,NaN,0.904374,0.660839,0.374999
2025-03-07 06:22:23.926,0.339176,0.077904,1.0,1.0,0.0,24.0,48.0,100.0,100.0,NaN,0.904374,0.742265,0.266928
2025-03-07 06:43:29.912,0.442269,0.072244,1.0,1.0,0.0,24.0,48.0,100.0,100.0,100.0,0.904374,0.762583,0.377323
2025-03-07 06:54:36.079,0.403008,0.083674,1.0,1.0,0.0,24.0,48.0,100.0,100.0,200.0,0.904374,0.723175,0.361352
2025-03-07 06:59:56.363,0.336473,0.053912,1.0,1.0,0.0,24.0,48.0,200.0,200.0,200.0,0.904374,0.691722,0.375401
2025-03-07 10:20:05.043,0.391399,0.109646,1.0,0.0,0.0,24.0,48.0,150.0,150.0,200.0,0.904374,0.746650,0.329078
2025-03-15 11:10:56.177,0.402145,0.095394,1.0,0.0,0.0,24.0,48.0,150.0,150.0,200.0,0.904374,0.713561,0.302410
2025-03-15 11:16:51.305,0.516161,0.089671,1.0,0.0,0.0,24.0,24.0,150.0,150.0,200.0,0.869538,0.669564,0.404869
2025-03-15 11:25:38.045,0.532844,0.155134,0.0,0.0,0.0,24.0,24.0,150.0,150.0,200.0,0.869538,0.707227,0.399895
2025-03-15 12:02:12.469,0.528034,0.147044,0.0,0.0,0.0,24.0,64.0,150.0,150.0,200.0,0.881886,0.680107,0.459402
2025-03-15 12:08:21.327,0.565591,0.283127,0.0,0.0,0.0,12.0,48.0,150.0,150.0,200.0,0.898099,0.841692,0.470564
2025-03-15 12:15:07.509,0.411421,0.265692,0.0,0.0,0.0,36.0,48.0,150.0,150.0,200.0,0.907219,0.549002,0.301825
2025-03-15 12:33:11.002,0.520464,0.167129,0.0,0.0,1.0,24.0,48.0,150.0,15.0,200.0,0.904374,0.537441,0.483711
2025-03-15 13:13:24.506,0.366937,0.149884,1.0,0.0,1.0,24.0,48.0,150.0,15.0,200.0,0.904374,0.714160,0.313184
2025-03-15 13:24:41.203,0.388507,0.164288,1.0,1.0,1.0,24.0,48.0,150.0,15.0,200.0,0.904374,0.702846,0.324736
2025-03-15 13:48:22.138,0.445933,0.156797,1.0,1.0,1.0,24.0,64.0,150.0,15.0,200.0,0.881886,0.615050,0.333443
2025-03-15 13:58:39.002,0.352796,0.163105,1.0,1.0,1.0,24.0,56.0,150.0,15.0,200.0,0.877946,0.582668,0.260671
2025-03-15 14:34:43.258,0.452933,0.192572,1.0,1.0,1.0,24.0,72.0,150.0,15.0,200.0,0.869538,0.773124,0.404312
2025-03-15 19:20:38.876,0.333683,0.164334,1.0,1.0,1.0,24.0,60.0,150.0,15.0,200.0,0.885350,0.644344,0.264535
2025-03-15 21:25:19.626,0.397991,0.165374,1.0,0.0,1.0,24.0,60.0,150.0,15.0,200.0,0.885350,0.710736,0.351827
2025-03-15 21:50:12.836,0.409816,0.193522,0.0,0.0,1.0,24.0,56.0,150.0,15.0,200.0,0.877946,0.753250,0.388080

In [18]:
dfNew.columns

Index(['_id', 'statefule', 'batch_size', 'forecast_period', 'features',
       'timesteps', 'shuffle', 'TotalLength', 'learningRate', 'history',
       'earlyStoppingLength', 'epochBest', 'changeWeights', 'date',
       'testError', 'trainError', 'y_test', 'y_hat', 'neurons', 'y_test_std',
       'y_hat_std', 'y_diff_std'],
      dtype='object')