In [3]:
import sqlite3
import pandas as pd
connr = sqlite3.connect('Data/DB/era5DataMeans.db')
tmp = pd.read_sql("select * from MEANS_TTdRHVPD",connr)

dates = tmp["Yrmo"].values.tolist()
invt={}
for yrmo in dates:
    yr=int(yrmo[:4])
    mo=int(yrmo[4:6])
    if yr not in invt:
        invt[yr]={}
    if mo not in invt[yr]:
       invt[yr][mo]=0

    invt[yr][mo]+=1
 

for year in sorted(invt.keys()):
    print(f"{int(year):4d}",end="")
    for month in range(1,13):
        if month in invt[year]:
            cnt=invt[year][month]
        else:
            cnt=0
        print(f"{cnt:5d}",end="")
    print("")

1990 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1991 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1992 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1993 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1994 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1995 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1996 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1997 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1998 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
1999 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2000 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2001 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2002 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2003 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2004 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2005 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2006 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2007 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2008 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2009 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2010 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2011 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2012 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2013 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2014 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2015 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2016 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2017 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2018 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2019 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2020 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2021 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2022 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2023 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982
2024 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982 2982

In [4]:
tmp.shape

(1252440, 8)

In [5]:
2982*12*34

1216656

In [6]:
tmp.head()

   index  Point    Yrmo  Length         T         Td         RH       VPD
0      0      0  199001     248 -8.463992 -12.366048  74.223548  0.092007
1      1      0  199002     224 -9.227723 -12.758839  76.263616  0.079737
2      2      0  199003     248 -3.466290  -7.204153  76.585927  0.127759
3      3      0  199004     240  4.388708  -3.163000  60.712417  0.380563
4      4      0  199005     248  7.292621  -4.213629  48.368589  0.628547

In [9]:
tmp.drop(columns="index",inplace=True)

In [11]:
tmp.to_csv("TTdRHVPD.csv",index=False)

In [10]:
tmp.head()

   Point    Yrmo  Length         T         Td         RH       VPD
0      0  199001     248 -8.463992 -12.366048  74.223548  0.092007
1      0  199002     224 -9.227723 -12.758839  76.263616  0.079737
2      0  199003     248 -3.466290  -7.204153  76.585927  0.127759
3      0  199004     240  4.388708  -3.163000  60.712417  0.380563
4      0  199005     248  7.292621  -4.213629  48.368589  0.628547