In [47]:
import pandas as pd
import sys
import platform
if platform.system() == 'Linux':
  sys.path.insert(0, '/mnt/c/Users/CoJoe/Python-Stuff')
else:
  sys.path.insert(0, 'c:/Users/CoJoe/Python-Stuff')

import JCLib

# adding Folder_2 to the system path

In [48]:
platform.system()

'Linux'

In [49]:
! pwd

/home/joe/work/NAASA

In [50]:
df = pd.read_csv("data/eoCoArts.csv")

In [51]:
h = JCLib.invYrMo(df.loc[df["ruling"] > 0],"ruling","%Y%m",2)
display(h)

TYpe  2
Starting

    year  Jan  Feb  Mar  Apr   May   Jun   Jul   Aug   Sep   Oct   Dec
0   1922    0    0    0    0   0.0   0.0   1.0   0.0   0.0   0.0   0.0
0   1923    0    0    0    0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
0   1924    0    0    0    0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
0   1925    0    0    1    0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
0   1926    0    0    0    0   0.0   0.0   0.0   0.0   0.0   0.0   0.0
..   ...  ...  ...  ...  ...   ...   ...   ...   ...   ...   ...   ...
0   2019    2    6   21   14  19.0   9.0  11.0  13.0  12.0  10.0   6.0
0   2020    7    9    8    8  14.0  11.0  12.0   8.0  11.0   2.0   5.0
0   2021    5    3   10    9   6.0   5.0   9.0  10.0  11.0   6.0  12.0
0   2022   15   22   17   10  13.0  13.0  17.0   8.0  16.0  16.0  14.0
0   2023    8   10   19    5   NaN   NaN   NaN   NaN   NaN   NaN   NaN

[102 rows x 12 columns]

In [52]:
df.shape

(2384, 28)

In [53]:
df.columns

Index(['ein', 'name', 'ico', 'street', 'city', 'state', 'zip', 'group',
       'subsection', 'affiliation', 'classification', 'ruling',
       'deductibility', 'foundation', 'activity', 'organization', 'status',
       'taxPeriod', 'assetCd', 'incomeCd', 'filingReqCd', 'pfFilingReqCd',
       'acctPd', 'assetAmt', 'incomeAmt', 'revenueAmt', 'nteeCd', 'sortName'],
      dtype='object')

In [54]:
df["nteeCd"].value_counts()

A20     242
A80     158
A68     155
A23     125
A25     102
       ...
A45M      1
A036      1
A125      1
A126      1
A202      1
Name: nteeCd, Length: 148, dtype: int64

In [55]:
df.isna().sum()

ein                  0
name                 0
ico                768
street               0
city                 0
state                0
zip                  0
group                0
subsection           0
affiliation          0
classification       0
ruling               0
deductibility        0
foundation           0
activity             0
organization         0
status               0
taxPeriod          184
assetCd              0
incomeCd             0
filingReqCd          0
pfFilingReqCd        0
acctPd               0
assetAmt           187
incomeAmt          187
revenueAmt         243
nteeCd             213
sortName          2114
dtype: int64

In [56]:
df["ein"].nunique()

2384

In [57]:
df.columns

Index(['ein', 'name', 'ico', 'street', 'city', 'state', 'zip', 'group',
       'subsection', 'affiliation', 'classification', 'ruling',
       'deductibility', 'foundation', 'activity', 'organization', 'status',
       'taxPeriod', 'assetCd', 'incomeCd', 'filingReqCd', 'pfFilingReqCd',
       'acctPd', 'assetAmt', 'incomeAmt', 'revenueAmt', 'nteeCd', 'sortName'],
      dtype='object')

In [58]:
print(df.loc[df["ruling"] > 0,"ruling"].min())
print(df["ruling"].max())

192207
202304

In [59]:
df.head()

,ein,name,ico,street,city,state,zip,group,subsection,affiliation,...,assetCd,incomeCd,filingReqCd,pfFilingReqCd,acctPd,assetAmt,incomeAmt,revenueAmt,nteeCd,sortName
0,10563501,THE E-PROJECT,RICHARD YACONIS,2373 S JAMAICA ST,AURORA,CO,80014-1715,0,3,3,...,3,3,1,0,12,48115.0,53688.0,47743.0,A65,NaN
1,10631470,GUNNISON VALLEY OBSERVATORY INC,BOOKIE LOUISE,PO BOX 762,GUNNISON,CO,81230-0762,0,3,3,...,3,2,2,0,3,59522.0,18779.0,18431.0,A50,NaN
2,10663760,ROCKY MOUNTAIN SYNCHRONIZED SWIMMING,PAM ANTELL,770 MOORHEAD CIRECLE STE UNIT B,BOULDER,CO,80305-0000,0,3,3,...,0,0,2,0,9,0.0,0.0,0.0,A20,NaN
3,10690594,EGBA-YEWA DESCENDANTS UNION IN COLORADO INC,VICTOR OGUNMODEDE,22759 E PRENTICE PL,AURORA,CO,80015-6545,0,3,3,...,0,0,2,0,12,0.0,0.0,0.0,A23,NaN
4,10690878,REDSTONE ART FOUNDATION,JIMMIE BENEDICT,303 REDSTONE BLVD,REDSTONE,CO,81623-8940,0,3,3,...,0,0,2,0,12,0.0,0.0,0.0,A40,NaN

In [62]:
df.loc[df["ico"].isna()]

,ein,name,ico,street,city,state,zip,group,subsection,affiliation,...,assetCd,incomeCd,filingReqCd,pfFilingReqCd,acctPd,assetAmt,incomeAmt,revenueAmt,nteeCd,sortName
8,20373379,HEARTWOOD COLLEGE OF ART INC,NaN,1340 US HIGHWAY 287 STE 100,BROOMFIELD,CO,80020-2224,0,3,3,...,0,0,2,0,6,0.0,0.0,0.0,A250,NaN
9,20491137,BRIAH DANSE,NaN,10305 W ILIFF AVE,LAKEWOOD,CO,80227-2022,0,3,3,...,0,0,2,0,12,0.0,0.0,0.0,A62,BRIAH DANSE COMPANY
10,30390058,BALLET RENAISSANCE,NaN,PO BOX 3768,ESTES PARK,CO,80517-3768,0,3,3,...,2,3,2,0,12,23874.0,46457.0,46457.0,A26,NaN
17,43841683,THE DENVER INDEPENDENT CHOREOGRAPHERS PROJECT,NaN,1213 S HOLLAND CT,LAKEWOOD,CO,80232-5133,0,3,3,...,0,0,2,0,12,0.0,0.0,0.0,A63,DICP
28,132931071,SOCIETY OF ANIMAL ARTISTS INC,NaN,5451 SEDONA HILLS DR,BERTHOUD,CO,80513-8987,0,3,3,...,5,4,1,0,12,527242.0,144031.0,57572.0,A20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2372,846046821,FRIENDS OF THE PUEBLO LIBRARY DISTRICT,NaN,622 S UNION AVE,PUEBLO,CO,81004-2244,0,3,3,...,4,4,1,0,4,108180.0,109789.0,109789.0,NaN,NaN
2376,846077998,COLORADO CHORALE,NaN,PO BOX 150544,DENVER,CO,80215-0544,0,3,3,...,4,3,1,0,6,236948.0,59512.0,54772.0,NaN,NaN
2379,850593597,CONVENTION ARTISTS GUILD,NaN,7310 W 52ND AVE,ARVADA,CO,80002-3725,0,6,3,...,0,0,2,0,12,0.0,0.0,0.0,NaN,NaN
2380,851836137,HIGH PRAIRIE STORYTELLERS,NaN,17710 E EMILIA DR,PARKER,CO,80134-7805,0,3,3,...,0,0,2,0,6,0.0,0.0,0.0,NaN,NaN
2381,852243054,MUSIC INCLUSION COALITION,NaN,435 ROYAL OAK DR,COLORADO SPGS,CO,80906-4853,0,3,3,...,0,0,2,0,6,0.0,0.0,0.0,NaN,NaN