In [19]:
import pandas as pd
import sys
# sys.path.insert(0, 'Z:\\mnt\\c\\users\\cojoe\\Python-Stuff')
# import JCLib
import logging
from re import sub
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)

## Septic Systems

### Original Data

In [20]:
                                     
septicConv = pd.read_csv("~/bic_etl/boulder/data_transformed/Septic_Export_from_Accela_cleaned.csv")

In [21]:
septicConv.shape

(29047, 20)

In [23]:
for col in septicConv.columns:
    print(col)

b1ApplStatus
b1AppTypeAlias
b1AltId
typeOfSystem
dwellingType
areaOfLot
bedrooms
limitingLayer
treatmentDepth
installerName
installingFirm
engineerName
engineeringFirm
addressNumber
streetDirection
streetName
streetSuffix
b1UnitStart
city
zipCode

In [34]:
septicConv.columns

Index(['b1ApplStatus', 'b1AppTypeAlias', 'b1AltId', 'typeOfSystem',
       'dwellingType', 'areaOfLot', 'bedrooms', 'limitingLayer',
       'treatmentDepth', 'installerName', 'installingFirm', 'engineerName',
       'engineeringFirm', 'addressNumber', 'streetDirection', 'streetName',
       'streetSuffix', 'b1UnitStart', 'city', 'zipCode'],
      dtype='object')

In [42]:
septicConv["typeOfSystem"].value_counts()

SEPTIC TANK                                                                                                                                                                                                                                                                   192
BUILDING SEWER                                                                                                                                                                                                                                                                100
BUILDING SEWER;SEPTIC TANK                                                                                                                                                                                                                                                     25
SEPTIC TANK;LIFT STATION PUMP                                                                                                                                                                                                                                                  20
BUILDING SEWER;VAULT                                                                                                                                                                                                                                                           18
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;ROCK AND PIPE                                                                                                                                                       14
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;CHAMBERS                                                                                                                                                            13
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;CHAMBERS;SAND FILTER;SECONDARY SAND                                                                                                                                                                           11
SEPTIC TANK;GRAVITY DISTRIBUTION                                                                                                                                                                                                                                               10
HOUSE CONNECT;BUILDING SEWER                                                                                                                                                                                                                                                   10
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;ROCK AND PIPE;SAND FILTER;SECONDARY SAND                                                                                                                                                                       9
VAULT                                                                                                                                                                                                                                                                           9
SEPTIC TANK;MANIFOLD;GRAVITY DISTRIBUTION;BED;ROCK AND PIPE;IN-SITU SOIL                                                                                                                                                                                                        8
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;CHAMBERS                                                                                                                                                                            8
BUILDING SEWER;SEPTIC TANK;GRAVITY DISTRIBUTION;DISTRIBUTION BOX;BED;CHAMBERS;IN-SITU SOIL                                                                                                                                                                                      8
VAULT PRIVY                                                                                                                                                                                                                                                                     8
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;ROCK AND PIPE                                                                                                                                                                       7
SEPTIC TANK;DISTRIBUTION BOX                                                                                                                                                                                                                                                    7
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP                                                                                                                                                                                                                                    7
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND                                                                                                                                                                      6
DISTRIBUTION BOX                                                                                                                                                                                                                                                                6
SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;CHAMBERS;SAND FILTER;SECONDARY SAND                                                                                                                                                                          6
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;EFFLUENT LINE;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;CHAMBERS                                                                                                                                               6
SEPTIC TANK;MANIFOLD;GRAVITY DISTRIBUTION;BED;CHAMBERS;IN-SITU SOIL                                                                                                                                                                                                             6
SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;ROCK AND PIPE;SAND FILTER;SECONDARY SAND                                                                                                                                                                     6
BUILDING SEWER;SEPTIC TANK;GRAVITY DISTRIBUTION;MANIFOLD;BED;IN-SITU SOIL;ROCK AND PIPE                                                                                                                                                                                         6
BUILDING SEWER;SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;ROCK AND PIPE                                                                                                                                                      6
SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;ROCK AND PIPE                                                                                                                                                                     5
BUILDING SEWER;SEPTIC TANK;MANIFOLD;GRAVITY DISTRIBUTION;BED;ROCK AND PIPE;IN-SITU SOIL                                                                                                                                                                                         5
BUILDING SEWER;SEPTIC TANK;GRAVITY DISTRIBUTION;DISTRIBUTION BOX;BED;IN-SITU SOIL;CHAMBERS                                                                                                                                                                                      5
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;BED;ROCK AND PIPE                                                                                                                                                                       4
SEPTIC TANK;MANIFOLD;BED;ROCK AND PIPE;IN-SITU SOIL                                                                                                                                                                                                                             4
SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;CHAMBERS                                                                                                                                                                          4
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;CHAMBERS;BED                                                                                                                                                             4
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;BED;ROCK AND PIPE                                                                                                                                                        4
BUILDING SEWER;LIFT STATION PUMP                                                                                                                                                                                                                                                4
BUILDING SEWER;SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;CHAMBERS;SAND FILTER;SECONDARY SAND                                                                                                                                                           4
SEPTIC TANK;GRAVITY DISTRIBUTION;DISTRIBUTION BOX;BED;CHAMBERS;IN-SITU SOIL                                                                                                                                                                                                     4
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;CHAMBERS;IN-SITU SOIL                                                                                                                                                                                          3
SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;BED                                                                                                                                                                                   3
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;CHAMBERS;SAND FILTER;SECONDARY SAND                                                                                                                                                             3
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;BED                                                                                                                                                                                     3
BUILDING SEWER;SEPTIC TANK;GRAVITY DISTRIBUTION;DISTRIBUTION BOX;TRENCH;CHAMBERS;IN-SITU SOIL                                                                                                                                                                                   3
SEPTIC TANK;GRAVITY DISTRIBUTION;MANIFOLD;BED;IN-SITU SOIL;ROCK AND PIPE                                                                                                                                                                                                        3
BUILDING SEWER;SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND                                                                                                                                                                    3
HOUSE CONNECT;BUILDING SEWER;SEPTIC TANK                                                                                                                                                                                                                                        3
SEPTIC TANK;MANIFOLD;BED;CHAMBERS;IN-SITU SOIL                                                                                                                                                                                                                                  3
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;ROCK AND PIPE;BED                                                                                                                                                        3
BUILDING SEWER;SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;ROCK AND PIPE;BED                                                                                                                                                      3
BUILDING SEWER;SEPTIC TANK;MANIFOLD;GRAVITY DISTRIBUTION;BED;IN-SITU SOIL                                                                                                                                                                                                       3
SEPTIC TANK;GRAVITY DISTRIBUTION;MANIFOLD;BED;ROCK AND PIPE;IN-SITU SOIL                                                                                                                                                                                                        3
BUILDING SEWER;SEPTIC TANK;GRAVITY DISTRIBUTION;MANIFOLD;BED;ROCK AND PIPE;IN-SITU SOIL                                                                                                                                                                                         2
HOUSE CONNECT;BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;EFFLUENT LINE;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;CHAMBERS                                                                                                                                 2
HOUSE CONNECT;BUILDING SEWER;SEPTIC TANK;GRAVITY DISTRIBUTION;IN-SITU SOIL;CHAMBERS;BED                                                                                                                                                                                         2
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;RIP AND REPLACE                                                                                                                                                                     2
SEPTIC TANK;LIFT STATION PUMP;AUTOMATIC DISTRIBUTION VALVE;MANIFOLD;BED;CHAMBERS;IN-SITU SOIL;PRESSURE DISTRIBUTION                                                                                                                                                             2
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;BED;SAND FILTER;SECONDARY SAND                                                                                                                                                                               2
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;AUTOMATIC DISTRIBUTION VALVE;BED;IN-SITU SOIL;CHAMBERS                                                                                                                                                       2
BUILDING SEWER;SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;SECONDARY SAND;CHAMBERS                                                                                                                                                           2
SAND FILTER;SECONDARY SAND;ROCK AND PIPE;BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED                                                                                                                                                        2
SEPTIC TANK;LIFT STATION PUMP;PUMP TO GRAVITY DISTRIBUTION                                                                                                                                                                                                                      2
BUILDING SEWER;SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;BED;ROCK AND PIPE;SAND FILTER;SECONDARY SAND                                                                                                                                                      2
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;ROCK AND PIPE;SAND FILTER;PREFERRED SAND                                                                                                                                                                       2
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;SAND FILTER;ROCK AND PIPE                                                                                                                                                                       2
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;AUTOMATIC DISTRIBUTION VALVE;BED;BED;CHAMBERS;SAND FILTER;SECONDARY SAND                                                                                                                                                    2
SEPTIC TANK;GRAVITY DISTRIBUTION;MANIFOLD;BED;IN-SITU SOIL                                                                                                                                                                                                                      2
SEPTIC TANK;MANIFOLD;BED;GRAVITY DISTRIBUTION;ROCK AND PIPE;IN-SITU SOIL                                                                                                                                                                                                        2
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;BED                                                                                                                                                                      2
LIFT STATION PUMP                                                                                                                                                                                                                                                               2
BUILDING SEWER;SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;ROCK AND PIPE;SAND FILTER;SECONDARY SAND                                                                                                                                                        2
HOUSE CONNECT;BUILDING SEWER;SEPTIC TANK;LIFT STATION SIPHON;PRESSURE DISTRIBUTION;MANIFOLD;SAND FILTER;SECONDARY SAND;BED;ROCK AND PIPE                                                                                                                                        2
SEPTIC TANK;LIFT STATION PUMP;PRESSURE DISTRIBUTION;MANIFOLD;BED;ROCK AND PIPE;SAND FILTER;SECONDARY SAND;RIP AND REPLACE                                                                                                                                                       2

In [24]:
septicConv["zipCode"].value_counts()

80302.0    6332
80503.0    4014
80466.0    3117
80303.0    2976
80026.0    1731
80301.0    1707
80540.0    1556
80504.0    1389
80304.0    1363
80403.0    1236
80481.0    1113
80510.0     999
80455.0     551
80501.0     282
80027.0     218
80516.0     170
80020.0     160
80305.0      74
80513.0      16
80544.0       6
80471.0       6
80401.0       5
80533.0       5
0.0           5
80025.0       3
80514.0       2
80477.0       1
80226.0       1
80225.0       1
80220.0       1
80502.0       1
80023.0       1
Name: zipCode, dtype: int64

In [25]:
septicConv.loc[(~septicConv["zipCode"].isna()) & (septicConv["zipCode"].astype(str).str.contains("-"))]

Empty DataFrame
Columns: [b1ApplStatus, b1AppTypeAlias, b1AltId, typeOfSystem, dwellingType, areaOfLot, bedrooms, limitingLayer, treatmentDepth, installerName, installingFirm, engineerName, engineeringFirm, addressNumber, streetDirection, streetName, streetSuffix, b1UnitStart, city, zipCode]
Index: []

In [27]:
septicConv.loc[(~septicConv["zipCode"].isna()) & (septicConv["zipCode"].astype(str).str.len() < 5)]

,b1ApplStatus,b1AppTypeAlias,b1AltId,typeOfSystem,dwellingType,areaOfLot,bedrooms,limitingLayer,treatmentDepth,installerName,installingFirm,engineerName,engineeringFirm,addressNumber,streetDirection,streetName,streetSuffix,b1UnitStart,city,zipCode
15527,System Approved,OWTS New System,NEWP-1900-0001296,NaN,4. Other,410.00000,0,NaN,NaN,NaN,NaN,NaN,NaN,0,NaN,ARAPAHOE,ROAD,NaN,UNINCORPORATED,0.0
16179,System Approved,OWTS New System,NEWP-1900-0004356,NaN,4. Other,1000.00000,0,NaN,NaN,NaN,UNKNOWN,NaN,UNKNOWN,0,NaN,ARAPAHOE,ROAD,NaN,UNINCORPORATED,0.0
23242,System Approved,OWTS New System,NEWP-1976-0007167,NaN,1. Residential,2.00000,2,NaN,NaN,LARRY NELSON,NELSON EXCAVATING,NaN,NELSON EXCAVATING,0,N,75TH,STREET,NaN,UNINCORPORATED,0.0
25091,System Not Approved,OWTS Major Repair,MAJP-1900-0000323,NaN,1. Residential,0.00000,3,NaN,NaN,NaN,NaN,NaN,NaN,0,S,104TH,STREET,NaN,UNINCORPORATED,0.0
26633,System Not Approved,OWTS New System,NEWP-1900-0000325,NaN,1. Residential,120.00000,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0,S,104TH,STREET,NaN,UNINCORPORATED,0.0

In [28]:
a = septicConv.loc[septicConv.duplicated(subset=['b1AltId'],keep=False)]

In [29]:
a

Empty DataFrame
Columns: [b1ApplStatus, b1AppTypeAlias, b1AltId, typeOfSystem, dwellingType, areaOfLot, bedrooms, limitingLayer, treatmentDepth, installerName, installingFirm, engineerName, engineeringFirm, addressNumber, streetDirection, streetName, streetSuffix, b1UnitStart, city, zipCode]
Index: []

In [30]:
septicConv.shape

(29047, 20)