In [4]:
import sqlite3
import pandas as pd

In [16]:
conn = sqlite3.connect('/home/joe/DBs/datasetTracker.db')

In [19]:
df = pd.read_sql("select * from datasets",conn)

In [20]:
df.head()

,datasetTitle,shortDescription,4x4
0,2019 Novel Coronavirus COVID-19 (2019-nCoV) Da...,Repository listing source links and supporting...,rkuy-jxyz
1,Active Business Licenses Denver,Business licences in Denver including license ...,s9wt-dsfz
2,Activities of Charities Operating in Colorado,Charitable organizations’ activities for the c...,vewn-5ajx
3,Airports in Colorado,"Airport locations, nearby city, recreation in ...",x5bw-ax3d
4,All Special Districts in Colorado,Aggregated from thousands of local jurisdictio...,dm2a-biqr

In [37]:
df = pd.read_sql('select * from datasets  where "datasetTitle" = "Active Business Licenses Denver"',conn)

In [38]:
df

,datasetTitle,shortDescription,4x4
0,Active Business Licenses Denver,Business licences in Denver including license ...,s9wt-dsfz

In [28]:
vals = df[["4x4","datasetTitle","shortDescription"]].values

In [29]:
vals

array([['s9wt-dsfz', 'Active Business Licenses Denver',
        'Business licences in Denver including license type, status, end date, and entity details']],
      dtype=object)

In [32]:
display(vals[0][0],vals[0][1],vals[0][2])

's9wt-dsfz'

'Active Business Licenses Denver'

'Business licences in Denver including license type, status, end date, and entity details'