In [1]:
import pandas as pd
import datetime
import csv
import urllib.request as urllib
import urllib.request as urlRequest
from sodapy import Socrata
import numpy as np

import PySimpleGUI as sg
import pyglet,tkinter
from pyglet import font
# import OpenGL
# from OpenGL import GLU
font.add_file('/etc/fonts/fonts/CENTAUR.TTF')

In [14]:
xrefs = {
'Entity Id':"entityId",
'Org Name':"name",
"Ce A1sign Date":"authorizedOfficerSignedDate",
"Ce A2sign Date":"cfoSignedDate",
"Ce File Date":"registrationApprovedDate",
"Ce Date Paid":"paymentProcessedDate",
"Ce Org Txmpt Date":"IRSDeterminationDate",
"Date Formed":"dateFormed",
"Status Date":"statusDate",
"Expiration Date":"expirationDate"
}

In [3]:
fileC = "https://data.colorado.gov/resource/37wu-kn3g.csv"
headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"}
req = urlRequest.Request(f"{fileC}?$limit=999999999", headers = headers)
x = urlRequest.urlopen(req)
sourceCode = x.read()
sourceCode=sourceCode.decode("utf-8")
readerC = csv.DictReader(sourceCode.splitlines())        
nlines=0
linesC = {}
for line in readerC:
    eid = line["entityid"]
    nlines+=1
    if eid not in linesC:
        linesC[eid]=[]
    linesC[eid].append(line)
print(nlines)

234570

In [51]:
nlines=0
file="/home/joe/bic_etl/cdos/business/nonprofit/data_source/OLD/reg_finan-old.tsv"
finX = open(file,encoding="latin")
readerX = csv.DictReader(finX,delimiter='\t') 
linesX = {}
for line in readerX:
    eid = line["Entity Id"]
    nlines+=1
    if eid not in linesX:
        linesX[eid]=[]
    linesX[eid].append(line)
print(nlines)

211708

In [ ]:
file="/home/joe/bic_etl/cdos/business/nonprofit/data_source/reg_finan.tsv"
finO = open(file)
readerO = csv.DictReader(finO,delimiter='\t') 

file="/home/joe/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.csv"
finT = open(file)
readerT = csv.DictReader(finT) 
nlines=0

# fileC = "https://data.colorado.gov/resource/37wu-kn3g.csv"
# headers = {"User-Agent": "Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/47.0.2526.106 Safari/537.36"}
# req = urlRequest.Request(f"{fileC}?$limit=999999999", headers = headers)
# x = urlRequest.urlopen(req)
# sourceCode = x.read()
# sourceCode=sourceCode.decode("utf-8")
# readerC = csv.DictReader(sourceCode.splitlines())        


for lineO in readerO:
#    print(line)
    lineT = next(readerT)
   # lineC = next(readerC)
 #   print(lineC)
#    for key in lineO.keys():
    eid = lineO["Entity Id"]
    for key in ['Entity Id','Org Name',"Ce A1sign Date","Ce A2sign Date","Ce File Date","Ce Date Paid","Ce Org Txmpt Date","Date Formed",
        "Status Date","Expiration Date"]:
     #   if key.lower().find("date") > -1:
        xkey = xrefs[key]
        print(key,lineO[key],":",lineT[xkey])
    if eid in linesC:
        for lineC in linesC[eid]:
             for key in ['Entity Id','Org Name',"Ce A1sign Date","Ce A2sign Date","Ce File Date","Ce Date Paid","Ce Org Txmpt Date","Date Formed",
            "Status Date","Expiration Date"]:
                 xkey = xrefs[key].lower()
                 if xkey in lineC:
                    val = lineC[xkey]
                 else:
                    val = "NO NO"
                 print("  CIM ",key,val)
             print("    -----")
        print("    ######")
    if eid in linesX:
        for lineX in linesX[eid]:
             for key in ['Entity Id','Org Name',"Ce A1sign Date","Ce A2sign Date","Ce File Date","Ce Date Paid","Ce Org Txmpt Date","Date Formed",
            "Status Date","Expiration Date"]:
                 xkey = key
                 if xkey in lineX:
                    val = lineX[xkey]
                 else:
                    val = "NO NO"
                 print("  XXX ",key,val)
             print("    -----")
        print("    ######")
    else:
        print("None CIM None Cim")
    print("-----")
    nlines+=1
    if nlines > 10:
       break

OLD WAY 
Entity Id 20021314382 : 20021314382
Org Name THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC. : THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.

ORIGINAL SOURCE               TRANSFORMED
Ce A1sign Date 20021113    : 
Ce A2sign Date 20021112    : 12/20/2011
Ce File Date 20021115      : 
Ce Date Paid 20021113      : 
Ce Org Txmpt Date 08/10/73 : 10/19/2008
Date Formed 19730518       : 05/18/1973   *
Status Date 20240207       : 07/20/2002
Expiration Date 02/15/25   : 02/15/2025   *

Entity Id 20021314382 : 20021314382
Org Name THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC. : THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.
Ce A1sign Date 11/13/2002    :             :
Ce A2sign Date 11/12/2002    : 12/20/2011  : 12/20/2011
Ce File Date 11/15/2002      :             :
Ce Date Paid 11/13/2002      :             :
Ce Org Txmpt Date 08/10/1973 : 10/19/2008  : ("IRSDeterminationDate")TC   ('irsexemptiondate') API
Date Formed 05/18/1973       : 05/18/1973  : 05/18/1973
Status Date 02/07/2024       : 07/20/2002  : 07/20/2002
Expiration Date 02/15/2025   : 02/15/2025  : 02/15/2025

  CIM  Entity Id 20021314382
  CIM  Org Name THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.
  CIM  Ce A1sign Date 
  CIM  Ce A2sign Date 12/20/2011
  CIM  Ce File Date 
  CIM  Ce Date Paid 
  CIM  Ce Org Txmpt Date NO NO
  CIM  Date Formed 05/18/1973
  CIM  Status Date 07/20/2002
  CIM  Expiration Date 02/15/2025


  XXX  Entity Id 20021314382
  XXX  Org Name THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.
  XXX  Ce A1sign Date 20021113
  XXX  Ce A2sign Date 20021112
  XXX  Ce File Date 20021115
  XXX  Ce Date Paid 20021113
  XXX  Ce Org Txmpt Date 08/10/73
  XXX  Date Formed 19730518
  XXX  Status Date 20230201
  XXX  Expiration Date 02/15/24

In [ ]:
linesC

In [38]:
linesC.keys()

dict_keys(['20023003049'])

In [56]:
list(linesC.keys())[0]

'20023003049'

In [ ]:
linesC["20021314382"]

In [ ]:
lineO

In [60]:
file="/home/joe/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.tsv"
finO = open(file)
readerO = csv.reader(finO,delimiter='\t')

In [61]:
hist = {}
for line in readerO:
    nn = len(line)
    if nn not in hist:
        hist[nn] = 0
    hist[nn]+=1

In [62]:
hist

{92: 234571}

## Get Dataset Metadata for CIM

In [9]:
cimDatasets = []
cim_url_query = 'data.colorado.gov'
bicHome = "/home/joe/bic_etl"
with Socrata(cim_url_query, None) as client:
    datasets = client.datasets()
    for dataset in datasets:
        if dataset['owner']['display_name'] == 'Colorado Information Marketplace':
            cimDatasets.append(dataset)

WARNING:root:Requests made without an app_token will be subject to strict throttling limits.

## Get Metadata For Target Datasset

In [10]:
title='Registration of Charities, Paid Solicitors, Professional Fundraising Consultants, and for-profit Public Benefit Corporations in Colorado'
for ds in cimDatasets:
    if ds['resource']['name'] == title:
        break

In [ ]:
ds

In [5]:
# import json
# fout = open("reg_fin_meta.json","w")
# fout.write(json.dumps(ds))

## Get Column Metadata

In [11]:
hist={}
for nn,val in enumerate(ds['resource']['columns_name']):
    hist[nn]={}
    hist[nn]["Column"]=val

for nn,val in enumerate(ds['resource']['columns_field_name']):
    hist[nn]["fieldName"]=val

for nn,val in enumerate(ds['resource']['columns_datatype']):
    hist[nn]["dataType"]=val

for nn,val in enumerate(ds['resource']['columns_description']):
    hist[nn]["description"]=val


for nn,val in enumerate(ds['resource']['columns_format']):
    hist[nn]["format"]=val

In [13]:
h={}
for nn,dct in hist.items():
    dt = dct["dataType"]
    if dt not in h:
        h[dt]=0
    h[dt]+=1
    if dct["dataType"] == "Checkbox":
        print(f'{dct["Column"]:30.30s}  {dct["fieldName"]:30.30s}  {dct["dataType"]:15.15s}  {dct["format"]}  {dct["description"]}')

In [14]:
h

{'Text': 55, 'Calendar date': 11, 'Number': 26}

## GUI

In [ ]:
def GUI(hist):
    rows=[]
    for nn,dct in hist.items():
         row=[]
         row.append(sg.Input(dct["Column"],key=f"Column",font='Courier 15 bold ',size=(30,1)))
         row.append(sg.Input(dct["fieldName"],key=f"fieldName",font='Courier 15 bold ',size=(30,1)))
         row.append(sg.Input(dct["dataType"],key=f"dataType",font='Courier 15 bold ',size=(30,1)))
         row.append(sg.Input(dct["format"],key=f"format",font='Courier 15 bold ',size=(30,1)))
         row.append(sg.Input(dct["description"],key=f"description",font='Courier 15 bold ',size=(30,1)))
         rows.append([sg.Frame("",[row],size=(1800,50))])
        
       
    row=[]
    rowsl=[]
    row.append(sg.Button("Close"))
#    row.append(sg.Button("Add XREF Field"))
    rowsl.append(row)
    row=[]
    row.append(sg.Column(rows,scrollable=True,pad=(20,20),size=(1800,1200))) 
    rowsl.append(row)
    layout = [[sg.Column(rowsl,scrollable=True)]]
    window = sg.Window('CIM Dataset Metadata',layout,finalize=True,resizable=True,size=(715,607))
    
    a = window.CurrentLocation()
    print("STARTING")
    
    # screen_width, screen_height = window.get_screen_dimensions()
    # win_width, win_height = window.size
    # x, y = (screen_width - win_width)//2, (screen_height - win_height)//2
 
    x=200
    y=200
 #   window.move(x, y)
    windowsOpen = {}
    windowsOpen["main"] = []
    windowsOpen["unique"] = []
    numWindows=0
    print("Going to Loop")
    while True:
        try:
            wid, event, values = sg.read_all_windows()
            
            print("MAIN ",wid)
            print("MAIN ",event)
            print("MAIN ",values)
            if event == sg.WIN_CLOSED or event == 'Close':
            
                break
        except Exception as err:
            print("ERROR ",err)
GUI(hist)

## Detailed Analysis

In [88]:
def getAsciiCodes():
    codesdf = pd.read_excel("/home/joe/Python/ascii-codes.xlsx",engine='openpyxl')
    asciiCodes={}
    for index,row in codesdf.iterrows():
        asciiCodes[row['DEC']] = {}
        asciiCodes[row['DEC']]['symbol'] = row['Symbol']
        asciiCodes[row['DEC']]['desc'] = row['Description']
    return asciiCodes

def analyzeString(line,nchars,histo,histc):
    for c in line:
        n = ord(c)
        nchars+=1
        if n not in histo:
            histo[n]=0
        histo[n]+=1    
        if c not in histc:
            histc[c]=0
        histc[c]+=1    
    return nchars

asciiCodes = getAsciiCodes()
histo = {}
histc = {}

## Get COlumns that are NUMBERS
check = {}
for nn,dct in hist.items():
    if dct["dataType"] == "Number":
        print(nn,dct["Column"])
        check[dct["Column"]]=1

0 programServiceRatio
7 revenueFromOther
14 permanentlyRestrictedAssets
15 temporarilyRestrictedAssets
17 endOfYearTotalLiabilities
18 endOfYearAssests
19 expensesTotal
21 expensesOther
22 expensesAffiliates
23 expensesFundraising
24 expensesFromProgramServices
25 revenueFromSpecialEvents
26 revenueFromInvestments
27 programServiceRevenue
28 revenueFromGovernment
29 revenueFromContibutions
34 totalExpensesPlusManagementGeneralDividedByContributions
35 expensesDividedByContributions
36 totalManagementGeneralExpensesPreviousYear
37 totalFundraisingExpensesPreviousYear
38 totalContributionsRaisedPreviousYear
39 outsideProfessionalFundraiserFees
84 endOfYearAssestsMinusLiabilities
85 expensesFromAdministrativeOther
86 revenueTotal
87 revenueFromSales

In [89]:
check

{'programServiceRatio': 1,
 'revenueFromOther': 1,
 'permanentlyRestrictedAssets': 1,
 'temporarilyRestrictedAssets': 1,
 'endOfYearTotalLiabilities': 1,
 'endOfYearAssests': 1,
 'expensesTotal': 1,
 'expensesOther': 1,
 'expensesAffiliates': 1,
 'expensesFundraising': 1,
 'expensesFromProgramServices': 1,
 'revenueFromSpecialEvents': 1,
 'revenueFromInvestments': 1,
 'programServiceRevenue': 1,
 'revenueFromGovernment': 1,
 'revenueFromContibutions': 1,
 'totalExpensesPlusManagementGeneralDividedByContributions': 1,
 'expensesDividedByContributions': 1,
 'totalManagementGeneralExpensesPreviousYear': 1,
 'totalFundraisingExpensesPreviousYear': 1,
 'totalContributionsRaisedPreviousYear': 1,
 'outsideProfessionalFundraiserFees': 1,
 'endOfYearAssestsMinusLiabilities': 1,
 'expensesFromAdministrativeOther': 1,
 'revenueTotal': 1,
 'revenueFromSales': 1}

## Analyze Source Data

In [91]:
asciiCodes = getAsciiCodes()
histo = {}
histc = {}
for col in check:
    histo[col]={}
    histc[col]={}

bad={}
file="/home/joe/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.tsv"
finO = open(file)
readerO = csv.DictReader(finO,delimiter='\t') 
nlines=0
nchars=0
bools={}
nlines=0
for line in readerO:
    nlines+=1
    for col,val in line.items():
        if isinstance(val,str):
            if val.lower() in ["y","n","yes","no","1","0","true","false",""]:
                if col not in bools:
                    bools[col]={}
                if val not in bools[col]:
                    bools[col][val]=0
                    
                bools[col][val]+=1
        if col in check:
           nchars = analyzeString(val,nchars,histo[col],histc[col])
           if len(val) == 1 and ord(val) == 45:
               print(col,val)
               if col not in bad:
                   bad[col]=0
               bad[col]+=1

In [111]:
columns = list(line.keys())

### Boolean Analysis

In [92]:
all = []
for col,dct in bools.items():
    tot=0
    tot = sum(dct.values())
    pp=100*tot/nlines
    if pp > 90: 
        print(col,nlines,tot,pp)
        for val,cnt in dct.items():
            print("   ",val,cnt,100*cnt/nlines)
    tmp=[]
    tmp.append(col)
    tmp.append(nlines)
    tmp.append(tot)
    tmp.append(pp)
    for val in ["y","n","yes","no","1","0","true","false",""]:
        if val in dct:
            cnt=dct[val]
        else:
            cnt=""
        tmp.append(cnt)
    all.append(tmp)
header= ["Column","Total Records","Boolean Records","Boolean %","y","n","yes","no","1","0","true","false",""]

actualFinancialsProvided 234570 234570 100.0
    N 32394 13.809950121498913
    Y 196337 83.70081425587244
     5839 2.4892356226286396
principalSddress2 234570 213787 91.13995822142644
     213787 91.13995822142644
principalProvince 234570 234450 99.9488425629876
     234450 99.9488425629876
mailingAddress2 234570 218694 93.23187108325872
     218694 93.23187108325872
mailingProvince 234570 234509 99.9739949695187
     234509 99.9739949695187
taxExemptStatus 234570 234570 100.0
    Y 220589 94.03973227607963
    N 13981 5.9602677239203645
donationsTaxDeductible 234570 234570 100.0
    Y 213324 90.94257577695357
    N 21246 9.057424223046425
extensionFiled 234570 234570 100.0
    N 164386 70.07972033934433
    Y 70184 29.92027966065567
consolidatedRegistrationStatement 234570 234570 100.0
    N 229078 97.65869463273224
    Y 5492 2.3413053672677666
publicBenefitCorporation 234570 233969 99.74378650296286
    N 233918 99.72204459223259
    Y 51 0.02174191073027241
expensesDividedByContributions 234570 224450 95.68572281195378
     208485 88.87965212942832
    0 15436 6.580551647695784
    1 529 0.22551903482968835
totalExpensesPlusManagementGeneralDividedByContributions 234570 221373 94.37396086456069
     208485 88.87965212942832
    0 12674 5.403077972460246
    1 214 0.09123076267212346
relatedToOtherOrganization 234570 234570 100.0
    Y 43542 18.5624760199514
    N 182558 77.82666155092296
     8470 3.610862429125634
relatedOrganizationTaxExempt 234570 234570 100.0
    Y 39743 16.942916826533658
    N 186357 79.4462207443407
     8470 3.610862429125634
solicitedNonTaxDeductibleGifts 234570 234570 100.0
    N 210418 89.70371317730316
    Y 15682 6.685424393571215
     8470 3.610862429125634
statedGiftNotTaxDeductible 234570 234570 100.0
    N 212709 90.68039391226499
    Y 13391 5.708743658609371
     8470 3.610862429125634
pbcRecordingMethod 234570 234073 99.78812294837363
     234073 99.78812294837363
pbcPromotedBenefit 234570 234080 99.79110713219934
     234080 99.79110713219934
pbcBenefitReportSent 234570 234439 99.94415313126146
     234422 99.9369058276847
    NO 3 0.001278935925310142
    YES 14 0.005968367651447329
pbcAnnualBenefitReport 234570 234080 99.79110713219934
     234080 99.79110713219934
expensesAffiliates 234570 232796 99.2437225561666
    0 222285 94.76275738585497
     10510 4.480538858336531
    1 1 0.00042631197510338065
expensesOther 234570 229550 97.85991388498103
     12687 5.40862002813659
    0 216860 92.45001492091913
    1 3 0.001278935925310142
expensesOtherComment 234570 230746 98.36978300720467
     230744 98.36893038325447
    0 2 0.0008526239502067613
permanentlyRestrictedAssets 234570 222165 94.71159994884256
    0 213189 90.88502366031462
     8970 3.8240184166773243
    1 6 0.002557871850620284
conflictOfInterest 234570 234570 100.0
     233724 99.63934006906254
    N 807 0.3440337639084282
    Y 39 0.016626167029031847
conflictOfInterestAffirmation 234570 234570 100.0
     233829 99.6841028264484
    N 694 0.2958605107217462
    Y 47 0.02003666282985889
cfoName 234570 231324 98.61619132881442
     231324 98.61619132881442
cfoSignedDate 234570 231319 98.61405976893892
     231319 98.61405976893892

In [ ]:
all

In [ ]:
actualFinancialsProvided 234570 234570 100.0
taxExemptStatus 234570 234570 100.0
donationsTaxDeductible 234570 234570 100.0
extensionFiled 234570 234570 100.0
consolidatedRegistrationStatement 234570 234570 100.0

publicBenefitCorporation 234570 233969 99.74378650296286

relatedToOtherOrganization 234570 234570 100.0
relatedOrganizationTaxExempt 234570 234570 100.0
solicitedNonTaxDeductibleGifts 234570 234570 100.0
statedGiftNotTaxDeductible 234570 234570 100.0
pbcBenefitReportSent 234570 234439 99.94415313126146
permanentlyRestrictedAssets 234570 222165 94.71159994884256
    0 213189 90.88502366031462
     8970 3.8240184166773243
    1 6 0.002557871850620284
conflictOfInterest 234570 234570 100.0
conflictOfInterestAffirmation 234570 234570 100.0

In [ ]:
histo

In [ ]:
asciiCodes

### Number Analysis

In [101]:
allowed = [45,46,48,49,50,51,52,53,54,55,56,57]
string=""
for col,dct in histo.items():
  #  print(col)
    for ci,cnt in dct.items():
        if ci not in allowed:
            print(col,ci,cnt,asciiCodes[ci]["symbol"],asciiCodes[ci]["desc"])
            string+=f"'{col}',"

revenueFromOther 44 93360 , Comma
permanentlyRestrictedAssets 44 17487 , Comma
temporarilyRestrictedAssets 44 36117 , Comma
endOfYearTotalLiabilities 44 190938 , Comma
endOfYearAssests 44 299188 , Comma
expensesTotal 44 299815 , Comma
expensesOther 44 4144 , Comma
expensesAffiliates 44 1642 , Comma
expensesFundraising 44 151884 , Comma
expensesFromProgramServices 44 279551 , Comma
revenueFromSpecialEvents 44 69090 , Comma
revenueFromInvestments 44 111392 , Comma
programServiceRevenue 44 126569 , Comma
revenueFromGovernment 44 64633 , Comma
revenueFromContibutions 44 272354 , Comma
totalManagementGeneralExpensesPreviousYear 44 209883 , Comma
totalFundraisingExpensesPreviousYear 44 150915 , Comma
totalContributionsRaisedPreviousYear 44 277147 , Comma
outsideProfessionalFundraiserFees 44 26392 , Comma
endOfYearAssestsMinusLiabilities 44 287049 , Comma
expensesFromAdministrativeOther 44 211485 , Comma
revenueTotal 44 304553 , Comma
revenueFromSales 44 36065 , Comma

In [102]:
string

"'revenueFromOther','permanentlyRestrictedAssets','temporarilyRestrictedAssets','endOfYearTotalLiabilities','endOfYearAssests','expensesTotal','expensesOther','expensesAffiliates','expensesFundraising','expensesFromProgramServices','revenueFromSpecialEvents','revenueFromInvestments','programServiceRevenue','revenueFromGovernment','revenueFromContibutions','totalManagementGeneralExpensesPreviousYear','totalFundraisingExpensesPreviousYear','totalContributionsRaisedPreviousYear','outsideProfessionalFundraiserFees','endOfYearAssestsMinusLiabilities','expensesFromAdministrativeOther','revenueTotal','revenueFromSales',"

In [69]:
a = {"Column1":{"replace":{(","):""}}}

In [104]:
 a = {"'revenueFromOther','permanentlyRestrictedAssets','temporarilyRestrictedAssets','endOfYearTotalLiabilities','endOfYearAssests','expensesTotal','expensesOther','expensesAffiliates','expensesFundraising','expensesFromProgramServices','revenueFromSpecialEvents','revenueFromInvestments','programServiceRevenue','revenueFromGovernment','revenueFromContibutions','totalManagementGeneralExpensesPreviousYear','totalFundraisingExpensesPreviousYear','totalContributionsRaisedPreviousYear','outsideProfessionalFundraiserFees','endOfYearAssestsMinusLiabilities','expensesFromAdministrativeOther','revenueTotal','revenueFromSales')":{"replace":{(","):""}}}

In [107]:
b=a.keys()

In [110]:
for b in a.keys():
    print(type(b),b)

<class 'str'> 'revenueFromOther','permanentlyRestrictedAssets','temporarilyRestrictedAssets','endOfYearTotalLiabilities','endOfYearAssests','expensesTotal','expensesOther','expensesAffiliates','expensesFundraising','expensesFromProgramServices','revenueFromSpecialEvents','revenueFromInvestments','programServiceRevenue','revenueFromGovernment','revenueFromContibutions','totalManagementGeneralExpensesPreviousYear','totalFundraisingExpensesPreviousYear','totalContributionsRaisedPreviousYear','outsideProfessionalFundraiserFees','endOfYearAssestsMinusLiabilities','expensesFromAdministrativeOther','revenueTotal','revenueFromSales')

In [71]:
toFix = {}
for col,dct in a.items():
    print(type(col),col)
    toFix[col]={}
    for what,dct2 in dct.items():
        toFix[col][what]={}
        for repl,wth in dct2.items():
            print(type(repl),repl)
            print(type(wth),wth)
            toFix[col][what]["from"] = []
            if isinstance(repl,tuple):             
                for val in repl:
                    toFix[col][what]["from"].append(val)
            else:
                    toFix[col][what]["from"].append(repl)
            toFix[col][what]["to"] = wth

<class 'str'> Column1
<class 'str'> ,
<class 'str'>

In [72]:
toFix

{'Column1': {'replace': {'from': [','], 'to': ''}}}

In [73]:
"".join(toFix["Column"]["replace"]["from"])

KeyError: 'Column'

In [74]:
if 'Column1' in toFix.keys():
    print("hit")

hit

In [75]:
toFix

{'Column1': {'replace': {'from': [','], 'to': ''}}}

In [76]:
for key in toFix.keys():
    if 'Column1' in key:
        print("HIT",key)

HIT Column1

In [114]:
df = pd.read_csv("/home/joe/bic_etl/cdos/business/nonprofit/data_source/reg_finan.tsv",delimiter="\t",encoding="latin")

/tmp/ipykernel_1194/2716722985.py:1: DtypeWarning: Columns (4,5,12,20,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/home/joe/bic_etl/cdos/business/nonprofit/data_source/reg_finan.tsv",delimiter="\t",encoding="latin")

In [115]:
df.head()

,Entity Id,Entity Type,Org Name,Ce Fein,Document Id,Ce Parent Id,Filing Type,Ce Actual Flg,Ce Paddr,Ce Paddr2,...,Os Perm Ass,Ce Ps Coi Flg,Ce Ps Coi Affirm,Legal Form,Place Formed,Date Formed,Current Status,Status Date,Expiration Date,Program Services Ratio
0,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20021314382,NaN,INITIAL REGISTRATION - ESTIMATES,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7978
1,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20033009561,20021314382,RENEWAL,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7854
2,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20043009759,20033009561,RENEWAL,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7831
3,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20053009471,20043009759,RENEWAL,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7344
4,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20063009958,20053009471,RENEWAL,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7543

In [116]:
df["Entity Type"].value_counts()

Entity Type
Charitable Organization      107218
Paid Solicitor                 1200
Paid Financial Consultant       236
Name: count, dtype: int64

In [119]:
dfT = pd.read_csv("/home/joe/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.tsv",delimiter="\t",encoding="latin")

/tmp/ipykernel_1194/3561289276.py:1: DtypeWarning: Columns (4,5,12,20,83,84) have mixed types. Specify dtype option on import or set low_memory=False.
  dfT = pd.read_csv("/home/joe/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.tsv",delimiter="\t",encoding="latin")

In [120]:
dfT.head()

,entityId,registrantTypeAbbr,name,fein,documentId,amendmentEntityId,filingType,actualFinancialsProvided,principalAddress,principalSddress2,...,permanentlyRestrictedAssets,conflictOfInterest,conflictOfInterestAffirmation,legalBusinessFormation,placeFormed,dateFormed,currentStatus,statusDate,expirationDate,programServiceRatio
0,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20021314382,NaN,INITIAL REGISTRATION - ESTIMATES,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7978
1,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20033009561,20021314382,RENEWAL,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7854
2,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20043009759,20033009561,RENEWAL,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7831
3,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20053009471,20043009759,RENEWAL,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7344
4,20021314382,Charitable Organization,"THE FOUNDATION FOR A CHRISTIAN CIVILIZATION, INC.",23-7325778,20063009958,20053009471,RENEWAL,N,1358 JEFFERSON RD.,NaN,...,0.0,NaN,NaN,CORPORATION,NY,05/18/1973,GOOD,02/07/2024,02/15/2025,0.7543

In [131]:
fin = open("/home/joe/bic_etl/cdos/business/nonprofit/data_transformed/reg_finan.tsv")

In [132]:
histn={}
histl={}
nline=0
for line in fin:
    nline+=1
    spl = line.split("\t")
    nn=len(spl)
    mm=len(line)
    if nn != 92:
        print(nline,nn)

    if nn not in histn:
        histn[nn]=0
    histn[nn]+=1

    if mm not in histl:
        histl[mm]=0
    histl[mm]+=1

In [133]:
histn

{92: 234571}

In [134]:
sorted(histl.keys())

[227,
 231,
 232,
 233,
 234,
 235,
 236,
 237,
 238,
 239,
 240,
 241,
 242,
 243,
 244,
 245,
 246,
 247,
 248,
 249,
 250,
 251,
 252,
 253,
 254,
 255,
 256,
 257,
 258,
 259,
 260,
 261,
 262,
 263,
 264,
 265,
 266,
 267,
 268,
 269,
 270,
 271,
 272,
 273,
 274,
 275,
 276,
 277,
 278,
 279,
 280,
 281,
 282,
 283,
 284,
 285,
 286,
 287,
 288,
 289,
 290,
 291,
 292,
 293,
 294,
 295,
 296,
 297,
 298,
 299,
 300,
 301,
 302,
 303,
 304,
 305,
 306,
 307,
 308,
 309,
 310,
 311,
 312,
 313,
 314,
 315,
 316,
 317,
 318,
 319,
 320,
 321,
 322,
 323,
 324,
 325,
 326,
 327,
 328,
 329,
 330,
 331,
 332,
 333,
 334,
 335,
 336,
 337,
 338,
 339,
 340,
 341,
 342,
 343,
 344,
 345,
 346,
 347,
 348,
 349,
 350,
 351,
 352,
 353,
 354,
 355,
 356,
 357,
 358,
 359,
 360,
 361,
 362,
 363,
 364,
 365,
 366,
 367,
 368,
 369,
 370,
 371,
 372,
 373,
 374,
 375,
 376,
 377,
 378,
 379,
 380,
 381,
 382,
 383,
 384,
 385,
 386,
 387,
 388,
 389,
 390,
 391,
 392,
 393,
 394,
 395,
 396,
 397,
 398,
 399,
 400,
 401,
 402,
 403,
 404,
 405,
 406,
 407,
 408,
 409,
 410,
 411,
 412,
 413,
 414,
 415,
 416,
 417,
 418,
 419,
 420,
 421,
 422,
 423,
 424,
 425,
 426,
 427,
 428,
 429,
 430,
 431,
 432,
 433,
 434,
 435,
 436,
 437,
 438,
 439,
 440,
 441,
 442,
 443,
 444,
 445,
 446,
 447,
 448,
 449,
 450,
 451,
 452,
 453,
 454,
 455,
 456,
 457,
 458,
 459,
 460,
 461,
 462,
 463,
 464,
 465,
 466,
 467,
 468,
 469,
 470,
 472,
 473,
 474,
 475,
 476,
 477,
 478,
 479,
 480,
 481,
 482,
 483,
 484,
 486,
 487,
 488,
 489,
 490,
 491,
 492,
 493,
 495,
 496,
 497,
 498,
 499,
 500,
 501,
 502,
 503,
 504,
 506,
 507,
 508,
 509,
 510,
 511,
 512,
 513,
 514,
 515,
 516,
 517,
 518,
 519,
 520,
 521,
 522,
 523,
 524,
 525,
 526,
 527,
 528,
 529,
 530,
 531,
 532,
 533,
 534,
 535,
 536,
 537,
 538,
 539,
 540,
 541,
 542,
 543,
 544,
 545,
 546,
 547,
 548,
 549,
 550,
 551,
 552,
 553,
 554,
 555,
 556,
 557,
 558,
 559,
 560,
 561,
 562,
 563,
 564,
 565,
 566,
 567,
 568,
 569,
 570,
 571,
 572,
 573,
 574,
 575,
 576,
 577,
 578,
 579,
 580,
 581,
 582,
 583,
 584,
 585,
 586,
 587,
 588,
 589,
 590,
 591,
 592,
 593,
 594,
 595,
 596,
 597,
 598,
 599,
 600,
 601,
 602,
 603,
 604,
 605,
 606,
 607,
 608,
 609,
 610,
 611,
 612,
 613,
 614,
 615,
 616,
 617,
 618,
 619,
 620,
 621,
 622,
 623,
 624,
 625,
 626,
 627,
 628,
 629,
 630,
 631,
 632,
 633,
 634,
 635,
 636,
 637,
 638,
 639,
 640,
 641,
 642,
 643,
 644,
 645,
 646,
 647,
 648,
 649,
 650,
 651,
 652,
 653,
 654,
 655,
 656,
 657,
 658,
 659,
 660,
 661,
 662,
 663,
 664,
 665,
 666,
 667,
 668,
 669,
 670,
 671,
 672,
 673,
 674,
 675,
 676,
 677,
 678,
 679,
 680,
 681,
 682,
 683,
 684,
 685,
 686,
 687,
 688,
 689,
 690,
 691,
 692,
 693,
 694,
 695,
 696,
 697,
 698,
 699,
 700,
 701,
 702,
 703,
 704,
 705,
 706,
 707,
 708,
 709,
 710,
 711,
 712,
 713,
 714,
 715,
 716,
 717,
 718,
 719,
 720,
 721,
 722,
 723,
 724,
 725,
 726,
 727,
 728,
 729,
 730,
 731,
 732,
 733,
 734,
 735,
 736,
 737,
 738,
 739,
 740,
 741,
 742,
 743,
 744,
 745,
 746,
 747,
 748,
 749,
 750,
 751,
 752,
 753,
 754,
 755,
 756,
 757,
 758,
 759,
 760,
 761,
 762,
 763,
 764,
 765,
 766,
 767,
 768,
 769,
 770,
 771,
 772,
 773,
 774,
 775,
 776,
 777,
 778,
 779,
 780,
 781,
 782,
 783,
 784,
 785,
 786,
 787,
 788,
 789,
 790,
 791,
 792,
 793,
 794,
 795,
 796,
 797,
 798,
 799,
 800,
 801,
 802,
 803,
 804,
 805,
 806,
 807,
 808,
 809,
 810,
 811,
 812,
 813,
 814,
 815,
 816,
 817,
 818,
 819,
 820,
 821,
 822,
 823,
 824,
 825,
 826,
 827,
 828,
 829,
 830,
 831,
 832,
 833,
 834,
 835,
 836,
 837,
 838,
 839,
 840,
 841,
 842,
 843,
 844,
 845,
 846,
 847,
 848,
 849,
 850,
 851,
 852,
 853,
 854,
 855,
 856,
 857,
 858,
 859,
 860,
 861,
 862,
 863,
 864,
 865,
 866,
 867,
 868,
 869,
 870,
 871,
 872,
 873,
 874,
 875,
 876,
 877,
 878,
 879,
 880,
 881,
 882,
 883,
 884,
 885,
 886,
 887,
 888,
 889,
 890,
 891,
 892,
 893,
 894,
 895,
 896,
 897,
 898,
 899,
 900,
 901,
 902,
 903,
 904,
 905,
 906,
 907,
 908,
 909,
 910,
 911,
 912,
 913,
 914,
 915,
 916,
 917,
 918,
 919,
 920,
 921,
 922,
 923,
 924,
 925,
 926,
 927,
 928,
 929,
 930,
 931,
 932,
 933,
 934,
 935,
 936,
 937,
 938,
 939,
 940,
 941,
 942,
 943,
 944,
 945,
 946,
 947,
 948,
 949,
 950,
 951,
 952,
 953,
 954,
 955,
 956,
 957,
 958,
 959,
 960,
 961,
 962,
 963,
 964,
 965,
 966,
 967,
 968,
 969,
 970,
 971,
 972,
 973,
 974,
 975,
 976,
 977,
 978,
 979,
 980,
 981,
 982,
 983,
 984,
 985,
 986,
 987,
 988,
 989,
 990,
 991,
 992,
 993,
 994,
 995,
 996,
 997,
 998,
 999,
 1000,
 1001,
 1002,
 1003,
 1004,
 1005,
 1006,
 1007,
 1008,
 1009,
 1010,
 1011,
 1012,
 1013,
 1014,
 1015,
 1016,
 1017,
 1018,
 1019,
 1020,
 1021,
 1022,
 1023,
 1024,
 1025,
 1026,
 1027,
 1028,
 1029,
 1030,
 1031,
 1032,
 1033,
 1034,
 1035,
 1036,
 1038,
 1040,
 1042,
 1043,
 1044,
 1045,
 1046,
 1047,
 1049,
 1050,
 1051,
 1052,
 1053,
 1054,
 1055,
 1056,
 1057,
 1059,
 1060,
 1061,
 1062,
 1064,
 1065,
 1067,
 1069,
 1070,
 1071,
 1072,
 1073,
 1074,
 1075,
 1076,
 1077,
 1078,
 1079,
 1081,
 1083,
 1084,
 1085,
 1086,
 1087,
 1088,
 1089,
 1090,
 1091,
 1092,
 1093,
 1094,
 1097,
 1099,
 1101,
 1102,
 1104,
 1106,
 1110,
 1112,
 1114,
 1116,
 1123,
 1133,
 1134,
 1137,
 1139,
 1142,
 1143,
 1144,
 1145,
 1146,
 1147,
 1148,
 1149,
 1152,
 1153,
 1154,
 1157,
 1158,
 1164,
 1169,
 1175,
 1189,
 1192,
 1199,
 1200,
 1201,
 1205,
 1206,
 1208,
 1209,
 1212,
 1215,
 1223,
 1224,
 1225,
 1226,
 1229,
 1231,
 1235,
 1236,
 1277,
 1287,
 1310,
 1367,
 1372,
 1396,
 1400,
 1433,
 1437,
 1439,
 1469,
 1488,
 1492,
 1504,
 1506,
 1507,
 1508,
 1515,
 1517,
 1520,
 1527,
 1528,
 1539,
 1559,
 1598,
 1607,
 1640,
 1642,
 1682,
 1694,
 1836]