In [1]:
import pandas as pd

In [3]:
df1=pd.read_csv("CountyCourtFilings.csv")
df1.head()

   Year  District  County      Crime-County  Ncounty
0  2014         1  Gilpin           Alcohol      7.0
1  2014         1  Gilpin  Animal Violation     37.0
2  2014         1  Gilpin             Arson      0.0
3  2014         1  Gilpin           Assault     15.0
4  2014         1  Gilpin    Bail Violation      0.0

In [5]:
df2=pd.read_csv("CountyCourtTrafficFilings.csv")
df2.head()

,Year,District,County,Crime,N
0,2014,1,Gilpin,"Driving Under Suspension, Revocation or\nDenial",173
1,2014,1,Gilpin,DUI-DWAI,123
2,2014,1,Gilpin,Motor Vehicle,325
3,2014,1,Jefferson,"Driving Under Suspension, Revocation or\nDenial",4101
4,2014,1,Jefferson,DUI-DWAI,1931

In [6]:
df3=pd.read_csv("District-AdultFilings.csv")
df3.head()

   Year  District                         Court Location Crime   N
0   NaN        20   Boulder-Longmont (county court only)   NaN NaN
1   NaN         5       Eagle-Basalt (county court only)   NaN NaN
2   NaN         8     Garfield-Rifle (county court only)   NaN NaN
3   NaN         8   Larimer-Loveland (county court only)   NaN NaN
4   NaN         9  Rio Blanco-Meeker (county court only)   NaN NaN

In [7]:
df4=pd.read_csv("District-JuvenileDelinquencyFilings.csv")
df4.head()

   Year  District                        Court Location CrimeJ  NJ
0   NaN        20  Boulder-Longmont (county court only)    NaN NaN
1   NaN         5      Eagle-Basalt (county court only)    NaN NaN
2   NaN         8    Garfield-Rifle (county court only)    NaN NaN
3   NaN         8  Larimer-Loveland (county court only)    NaN NaN
4   NaN         7                        Montrose-Nucla    NaN NaN

In [8]:
df4['Year'].value_counts()

2023.0    2368
2022.0    2368
2021.0    2368
2020.0    2368
2019.0    2368
2018.0    2304
2016.0    2240
2017.0    2239
2015.0    2176
2014.0    2176
Name: Year, dtype: int64