In [1]:
import pandas as pd
pd.set_option('display.max_rows', 500)
pd.set_option('display.max_columns', None)

In [5]:
df = pd.read_csv("Map_Datasets_NoCensus.csv")

In [6]:
df.head(100)

,UID,Name,Owner,Audience,Type
0,25ry-d5r8,Highway Traffic Counts in Colorado 2017 Map,Colorado Information Marketplace,public,map
1,vqx7-fwxd,Septic Permit,Colorado Information Marketplace,public,map
2,e7ye-tasg,Major Roads in Colorado,Colorado Information Marketplace,public,map
3,x5bw-ax3d,Airports in Colorado,Colorado Information Marketplace,public,map
4,dqd2-3hbj,Points of Interest in Denver - Map,Colorado Information Marketplace,public,map
5,knn6-7fy9,Wind Turbines in Colorado 2013,Colorado Information Marketplace,public,map
6,fypu-tup4,Biomethane Potential in Colorado 2014,Colorado Information Marketplace,public,map
7,mmq3-xrh7,Tree Canopy Assesment Denver - Map,Colorado Information Marketplace,public,map
8,v328-h7vn,Map of Recently Approved Liquor Licenses in Co...,Colorado Information Marketplace,public,map
9,5qqr-23dz,Municipal Annexations in Colorado,Colorado Information Marketplace,public,map
10,92n9-xx4r,Map of Liquor Licenses in Colorado,Colorado Information Marketplace,public,map
11,uksn-8qya,Lakes in Colorado,Colorado Information Marketplace,public,map
12,esrk-9vjd,School Districts in Colorado,Colorado Information Marketplace,public,map
13,4qh9-evw6,State Highway On-System Curb Ramps in Colorado,Colorado Information Marketplace,public,map
14,7nuk-vzhq,Cities in Colorado,Colorado Information Marketplace,public,map
15,9h8i-6khx,Cemetery Distrticts in Colorado,Colorado Information Marketplace,public,map
16,4h6z-rhfw,Highway Traffic Counts in Colorado 2014,Colorado Information Marketplace,public,map
17,dx5q-y5je,Road Traffic Counts in Colorado 2014,Colorado Information Marketplace,public,map
18,sfvq-tb9q,Noxious Weeds in Colorado 2013,Colorado Information Marketplace,public,map
19,hb4b-8v4q,Crude Oil Rail Terminals in Colorado 2014,Colorado Information Marketplace,public,map
20,wxzv-xh9i,Hospital Districts in Colorado,Colorado Information Marketplace,public,map
21,2h6w-z9ry,Highways in Colorado,Colorado Information Marketplace,public,map
22,67vn-ijga,Counties in Colorado,Colorado Information Marketplace,public,map
23,ua3v-vcuh,Fire Districts in Colorado,Colorado Information Marketplace,public,map
24,u943-ics6,Municipal Boundaries in Colorado,Colorado Information Marketplace,public,map
25,yajv-ea35,Wind Potential for Colorado 2014,Colorado Information Marketplace,public,map
26,pkue-zrfg,Business Improvement Districts in Denver Map,Colorado Information Marketplace,public,map
27,fwyp-a5y7,EV Charging and Alternative Fuels Stations in ...,Colorado Information Marketplace,public,map
28,3kjc-z9fd,Vacant Industrial and Commercial Parcels in Gr...,Colorado Information Marketplace,public,map
29,itzi-4q6v,Development Projects in Grand Junction Colorad...,Colorado Information Marketplace,public,map
30,rpvk-ifh4,Geothermal Potential in Colorado 2009,Colorado Information Marketplace,public,map
31,rtw9-6tit,Solar Global Horizontal Irradiance in Colorado...,Colorado Information Marketplace,public,map
32,w9zf-5neg,Highway Traffic Counts in Colorado 2016 Map,Colorado Information Marketplace,public,map
33,mguq-rjzb,Noxious Weeds in Colorado 2014,Colorado Information Marketplace,public,map
34,g7tq-rkfe,Map of Sales Rooms in Colorado,Colorado Information Marketplace,public,map
35,ewqz-5hmi,Scenic Byways in Colorado Map,Colorado Information Marketplace,public,map
36,dnyf-3m59,Construction Project Line Segments for Funded ...,Colorado Information Marketplace,public,map
37,t8ag-kzkw,Noxious Weeds in Colorado 2012,Colorado Information Marketplace,public,map
38,d6bs-3kgu,Water and Sanitation Districts in Colorado,Colorado Information Marketplace,public,map
39,q2iw-kpix,Grocery Stores in Grand Junction Colorado,Colorado Information Marketplace,public,map
40,8hx8-24k6,Noxious Weeds in Colorado 2010,Colorado Information Marketplace,public,map
41,xs2v-uzeg,Highway Routes in Colorado,Colorado Information Marketplace,public,map
42,x238-vje7,Streams in Colorado,Colorado Information Marketplace,public,map
43,fwb5-rzg5,Soil Districts in Colorado,Colorado Information Marketplace,public,map
44,x4sv-war6,Map of Recently Expired and Surrendered Liquor...,Colorado Information Marketplace,public,map
45,ws2k-4zj6,General Improvement Districts in Denver,Colorado Information Marketplace,public,map
46,853a-s2qz,Parks and Rec Districts in Colorado,Colorado Information Marketplace,public,map
47,yt78-xpzf,Neighborhood Business Revitalization Corridors...,Colorado Information Marketplace,public,map
48,knbf-ggf2,Metro Districts in Colorado,Colorado Information Marketplace,public,map
49,hpem-wb68,Railroads in Colorado,Colorado Information Marketplace,public,map
50,9syq-9vv5,Highway Milepoints in Colorado,Colorado Information Marketplace,public,map
51,3bgg-gcfa,Highway Traffic Counts in Colorado 2015,Colorado Information Marketplace,public,map
52,f325-6r9c,Solar PV Capacity Factor in Colorado 2015,Colorado Information Marketplace,public,map
53,mv3v-5qet,Crude Oil Pipelines in Colorado 2014,Colorado Information Marketplace,public,map
54,a26p-3wtg,Vacant Commercial / Industial Parcels,Colorado Information Marketplace,public,map
55,3thw-b7wj,Library Districts in Colorado,Colorado Information Marketplace,public,map
56,qvrk-xsmj,Local Roads in Colorado,Colorado Information Marketplace,public,map
57,hzmx-2dfk,Tree Inventory of Denver - Map,Colorado Information Marketplace,public,map
58,7bzf-viss,Construction Projects Endpoints for Funded Roa...,Colorado Information Marketplace,public,map
59,9bzu-nqxb,Biomass Potential in Colorado 2014,Colorado Information Marketplace,public,map
60,envj-hfws,Parcels in Denver Map,Colorado Information Marketplace,public,map
61,dm2a-biqr,All Special Districts in Colorado,Colorado Information Marketplace,public,map
62,unz2-68bn,Solar Direct Normal Irradiance in Colorado 2014,Colorado Information Marketplace,public,map
63,fkrf-c7qd,Food Stores in Denver Map,Colorado Information Marketplace,public,map
64,trm9-dm4m,Highway Mileposts in Colorado,Colorado Information Marketplace,public,map

In [2]:
df1 = pd.read_csv("Asset_Inventory.csv")

In [3]:
df1.shape

(2556, 111)

In [4]:
df1.columns

Index(['UID', 'Name', 'Description', 'Owner', 'Owner UID', 'Publication Stage',
       'Audience', 'Approval Status', 'Provenance', 'Type',
       ...
       'Data Quality: Stewardship Plan', 'Data Updates: Update Schedule',
       'Data Updates: Total Columns at Recent Update',
       'Dataset Summary: Progress',
       'Additional Dataset Documentation: Data Dictionary',
       'Department Metrics: Publishing Department',
       'Data Description: Oldest Record in Dataset',
       'Dataset Summary: Sub Agency',
       'Data Description: Date of Initial Dataset Creation',
       'Data Description: Collection Mode'],
      dtype='object', length=111)

In [5]:
dfm = pd.read_csv("Mondara_Maps.csv")

In [6]:
dfm.shape

(160, 7)

In [7]:
dfm.columns

Index(['name', 'domain', 'uid', 'link', 'createdAt', 'updatedAt',
       'child_views'],
      dtype='object')

In [8]:
for col in df1.columns:
    print(col)

UID
Name
Description
Owner
Owner UID
Publication Stage
Audience
Approval Status
Provenance
Type
Category
Tags
url
API Endpoint
Creation Date (UTC)
Last Metadata Updated Date (UTC)
Last Data Updated Date (UTC)
Domain
Derived View
Visits
Downloads
Row Label
Row Count
Column Count
Contact Email
License
Attribution
Attribution Link
Published Version Name
Published Version UID
Parent UID
Dataset Summary: Agency
Required Field Set: Primary Content Provider
Data Description: Newest Record in Dataset
Dataset Coverage: Geographic Coverage
Dataset Coverage: Unit of Analysis
Contributing Agency Information: Citation
Additional Dataset Documentation: FGDC Compliance (Geospatial Only)
Data.colorado.gov Dataset Descriptions: Time Period
Data Quality: Data Governance Plan
Geospatial: Coordinate System Disclaimer
Dataset Summary: Frequency
Geospatial: Web Display Coordinate System
Data.colorado.gov Dataset Descriptions: Stewardship Plan
Data Description: Related Datasets
Data Description: Data Collection Instrument
Data Quality: Applicable Information Quality Guideline Designation
Dataset Summary: Source
Dataset Summary: Suggested by Public
Required Field Set: Secondary Content Editor
Data Description: Collection Method
Data.colorado.gov Dataset Descriptions: Sub agency
Data Updates: Total Records at Recent Update
Geo Data Information: Positional Accuracy
Dataset Summary: Local Government Entity
Data.colorado.gov Dataset Descriptions: Frequency of Update
Data.colorado.gov Dataset Descriptions: Data Quality Certified
Geospatial: Positional Accuracy
Contributing Agency Information: Business Contact and Phone
Data.colorado.gov Dataset Descriptions: Purpose
Contributing Agency Information: Technical Contact and Phone
Data.colorado.gov Dataset Descriptions: Secondary Content Provider
Dataset Summary: Currentness Reference
Geo Data Information: Horizontal Coordinate System
Data Quality: Expected Update Frequency
Data Description: Long Description
Data.colorado.gov Dataset Descriptions: Agency
Contributing Agency Information: Agency Data Series Page
Data Updates: Update Method
Data Updates: Update Type
Required Field Set: Agency
Dataset Summary: High Value Dataset
Geospatial: Horizontal Accuracy
Additional Dataset Documentation: Technical Documentation
Geospatial: Horizontal Coordinate System
Data Updates: Date of Inital Publish
Dataset Summary: Time Period
Data.colorado.gov Dataset Descriptions: Date Created
Data Description: Field Names, comma delimited
Dataset Coverage: Granularity
Dataset Summary: Date Released
Additional Dataset Documentation: Additional Metadata
Contributing Agency Information: Agency Program Page
Data Updates: Total Records at Initial Publish
Contributing Agency Information: Data Source
Data.colorado.gov Dataset Descriptions: Last Updated
Data Quality: Privacy and Confidentiality
Dataset Summary: Purpose
Data Updates: File Size at Recent Update
Dataset Summary: Type
Dataset Summary: Date Updated
Data.colorado.gov Dataset Descriptions: Data Governance Plan
Data Quality: Data Quality Certification
Data Updates: Source Update Schedule
Flood 2013: Content type
Geo Data Information: Bounding Coordinates
Data Description: Single Row
Data.colorado.gov Dataset Descriptions: Status
Required Field Set: Frequency of Update
Geospatial: Collection Method
Dataset Summary: Category
Data Quality: Stewardship Plan
Data Updates: Update Schedule
Data Updates: Total Columns at Recent Update
Dataset Summary: Progress
Additional Dataset Documentation: Data Dictionary
Department Metrics: Publishing Department
Data Description: Oldest Record in Dataset
Dataset Summary: Sub Agency
Data Description: Date of Initial Dataset Creation
Data Description: Collection Mode

In [10]:
df1["Owner"].value_counts()

Colorado Information Marketplace    534
April Broome                        261
Tim Campbell                        148
Daniel Cisneros                      88
Futsum                               53
                                   ...
LuCash                                1
Bespoke Systems                       1
CBP                                   1
JohnnY Levy                           1
John Orr                              1
Name: Owner, Length: 526, dtype: int64

In [11]:
dfCIM = df1.loc[df1["Owner"] == "Colorado Information Marketplace"]

In [12]:
dfCIM.shape

(534, 111)

In [13]:
dfCIM.columns

Index(['UID', 'Name', 'Description', 'Owner', 'Owner UID', 'Publication Stage',
       'Audience', 'Approval Status', 'Provenance', 'Type',
       ...
       'Data Quality: Stewardship Plan', 'Data Updates: Update Schedule',
       'Data Updates: Total Columns at Recent Update',
       'Dataset Summary: Progress',
       'Additional Dataset Documentation: Data Dictionary',
       'Department Metrics: Publishing Department',
       'Data Description: Oldest Record in Dataset',
       'Dataset Summary: Sub Agency',
       'Data Description: Date of Initial Dataset Creation',
       'Data Description: Collection Mode'],
      dtype='object', length=111)

In [14]:
dfCIM["Type"].value_counts()

dataset     347
map         162
href         15
filter        7
datalens      3
Name: Type, dtype: int64

In [15]:
dfCIMMap = dfCIM.loc[dfCIM["Type"] == "map"]

In [16]:
dfCIMMap.shape

(162, 111)

In [18]:
dfCIMMap["Audience"].value_counts()

public     157
private      5
Name: Audience, dtype: int64

In [24]:
dfCIMMapCen = dfCIMMap.loc[dfCIMMap["Name"].str.lower().str.contains("census")]

In [25]:
dfCIMMapCen.shape

(92, 111)

In [28]:
dfCIMMapCen["Type"].value_counts()

map    92
Name: Type, dtype: int64

In [29]:
dfCIMMapCen

,UID,Name,Description,Owner,Owner UID,Publication Stage,Audience,Approval Status,Provenance,Type,Category,Tags,url,API Endpoint,Creation Date (UTC),Last Metadata Updated Date (UTC),Last Data Updated Date (UTC),Domain,Derived View,Visits,Downloads,Row Label,Row Count,Column Count,Contact Email,License,Attribution,Attribution Link,Published Version Name,Published Version UID,Parent UID,Dataset Summary: Agency,Required Field Set: Primary Content Provider,Data Description: Newest Record in Dataset,Dataset Coverage: Geographic Coverage,Dataset Coverage: Unit of Analysis,Contributing Agency Information: Citation,Additional Dataset Documentation: FGDC Compliance (Geospatial Only),Data.colorado.gov Dataset Descriptions: Time Period,Data Quality: Data Governance Plan,Geospatial: Coordinate System Disclaimer,Dataset Summary: Frequency,Geospatial: Web Display Coordinate System,Data.colorado.gov Dataset Descriptions: Stewardship Plan,Data Description: Related Datasets,Data Description: Data Collection Instrument,Data Quality: Applicable Information Quality Guideline Designation,Dataset Summary: Source,Dataset Summary: Suggested by Public,Required Field Set: Secondary Content Editor,Data Description: Collection Method,Data.colorado.gov Dataset Descriptions: Sub agency,Data Updates: Total Records at Recent Update,Geo Data Information: Positional Accuracy,Dataset Summary: Local Government Entity,Data.colorado.gov Dataset Descriptions: Frequency of Update,Data.colorado.gov Dataset Descriptions: Data Quality Certified,Geospatial: Positional Accuracy,Contributing Agency Information: Business Contact and Phone,Data.colorado.gov Dataset Descriptions: Purpose,Contributing Agency Information: Technical Contact and Phone,Data.colorado.gov Dataset Descriptions: Secondary Content Provider,Dataset Summary: Currentness Reference,Geo Data Information: Horizontal Coordinate System,Data Quality: Expected Update Frequency,Data Description: Long Description,Data.colorado.gov Dataset Descriptions: Agency,Contributing Agency Information: Agency Data Series Page,Data Updates: Update Method,Data Updates: Update Type,Required Field Set: Agency,Dataset Summary: High Value Dataset,Geospatial: Horizontal Accuracy,Additional Dataset Documentation: Technical Documentation,Geospatial: Horizontal Coordinate System,Data Updates: Date of Inital Publish,Dataset Summary: Time Period,Data.colorado.gov Dataset Descriptions: Date Created,"Data Description: Field Names, comma delimited",Dataset Coverage: Granularity,Dataset Summary: Date Released,Additional Dataset Documentation: Additional Metadata,Contributing Agency Information: Agency Program Page,Data Updates: Total Records at Initial Publish,Contributing Agency Information: Data Source,Data.colorado.gov Dataset Descriptions: Last Updated,Data Quality: Privacy and Confidentiality,Dataset Summary: Purpose,Data Updates: File Size at Recent Update,Dataset Summary: Type,Dataset Summary: Date Updated,Data.colorado.gov Dataset Descriptions: Data Governance Plan,Data Quality: Data Quality Certification,Data Updates: Source Update Schedule,Flood 2013: Content type,Geo Data Information: Bounding Coordinates,Data Description: Single Row,Data.colorado.gov Dataset Descriptions: Status,Required Field Set: Frequency of Update,Geospatial: Collection Method,Dataset Summary: Category,Data Quality: Stewardship Plan,Data Updates: Update Schedule,Data Updates: Total Columns at Recent Update,Dataset Summary: Progress,Additional Dataset Documentation: Data Dictionary,Department Metrics: Publishing Department,Data Description: Oldest Record in Dataset,Dataset Summary: Sub Agency,Data Description: Date of Initial Dataset Creation,Data Description: Collection Mode
356,n53p-giqe,Census Places in Colorado 2012,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"acs,american community survey,bic,census,color...",https://data.colorado.gov/d/n53p-giqe,https://data.colorado.gov/resource/n53p-giqe.json,04/08/2015 08:49:27 PM,09/06/2023 11:02:55 AM,04/08/2015 08:49:27 PM,data.colorado.gov,False,1534.0,134.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,The American Community Survey (ACS) is an ongo...,NaN,https://demography.dola.colorado.gov/gis/gis-d...,None,Static,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census place demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
359,gu6r-zvv2,Census Tracts in Colorado 2010,Census Data is collected every 10 years by mai...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"bic,census,colorado,commute,decennial,demograp...",https://data.colorado.gov/d/gu6r-zvv2,https://data.colorado.gov/resource/gu6r-zvv2.json,01/28/2015 08:11:19 PM,09/06/2023 11:02:29 AM,01/28/2015 08:11:19 PM,data.colorado.gov,False,2483.0,328.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://demography.dola.colorado.gov/gis/gis-d...,None,Static,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decennial census tract demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
360,sn6p-34bq,Census Counties in Colorado 2016,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"acs,american community survey,bic,census,color...",https://data.colorado.gov/d/sn6p-34bq,https://data.colorado.gov/resource/sn6p-34bq.json,02/27/2018 06:59:50 PM,09/06/2023 11:03:25 AM,04/01/2018 12:52:16 PM,data.colorado.gov,False,1243.0,128.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,Surveys,NaN,NaN,NaN,NaN,The 2000 census marked the last year that the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://demography.dola.colorado.gov/,None,Static,NaN,NaN,Census data is reliable as within the constrai...,NaN,NAD83/GCS_North_American_1985,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census counties demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,2016,TIGER line files
370,uman-zjh4,Census in Colorado 2017 Map,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,NaN,https://data.colorado.gov/d/uman-zjh4,https://data.colorado.gov/resource/uman-zjh4.json,02/19/2019 04:05:56 PM,02/19/2019 04:06:03 PM,02/15/2019 04:27:37 PM,data.colorado.gov,True,399.0,20.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/pacific/dola,NaN,NaN,jycn-t6wi,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,Surveys,NaN,NaN,NaN,NaN,The 2000 census marked the last year that the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not public,NaN,"Rob Kemp, robert.kemp@state.co.us",NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://demography.dola.colorado.gov/,NaN,NaN,NaN,NaN,Census data is reliable as within the constrai...,NaN,NAD83/GCS_North_American_1985,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/pacific/dola,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census state demographics,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2017,TIGER line files
371,azt3-ee77,Census in Colorado 2018 Map,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,NaN,https://data.colorado.gov/d/azt3-ee77,https://data.colorado.gov/resource/azt3-ee77.json,03/17/2021 12:20:30 AM,03/17/2021 12:27:12 AM,02/13/2020 09:49:31 PM,data.colorado.gov,True,332.0,12.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/pacific/dola,NaN,NaN,ph72-axst,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS85,NaN,NaN,Surveys,NaN,NaN,NaN,NaN,The 2000 census marked the last year that the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,not public,NaN,"Rob Kemp, robert.kemp@state.co.us",NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://demography.dola.colorado.gov/,None,Static,NaN,NaN,Census data is reliable as within the constrai...,NaN,NAD83/GCS_North_American_1986,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census state demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,2018,TIGER line files
372,9cn8-g4er,Census Places in Colorado 2014,Census data for places (geospatial extent) fro...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"american community survey,bic,census,colorado,...",https://data.colorado.gov/d/9cn8-g4er,https://data.colorado.gov/resource/9cn8-g4er.json,02/24/2016 06:53:33 PM,09/06/2023 11:03:08 AM,02/24/2016 06:53:33 PM,data.colorado.gov,False,1373.0,272.0,Census place,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,Surveys,NaN,NaN,NaN,NaN,The 2000 census marked the last year that the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://www.census.gov/geo/maps-data/,None,Static,NaN,NaN,Census data is reliable as within the constrai...,NaN,NAD83/GCS_North_American_1983,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census place demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,2010,TIGER line files
382,gafi-svtb,Census Congressional Districts in Colorado 2014,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"acs,american community survey,bic,census,color...",https://data.colorado.gov/d/gafi-svtb,https://data.colorado.gov/resource/gafi-svtb.json,03/01/2018 09:13:19 PM,09/06/2023 11:03:30 AM,05/29/2019 04:48:18 PM,data.colorado.gov,False,1053.0,108.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,Surveys,NaN,NaN,NaN,NaN,The 2000 census marked the last year that the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://demography.dola.colorado.gov/,None,Static,NaN,NaN,Census data is reliable as within the constrai...,NaN,NAD83/GCS_North_American_1985,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/pacific/dola,7,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census congressional districts demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,2014,TIGER line files
384,qx2d-46a5,Census Core Based Statistical Area in Colorado...,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"acs,american community survey,bic,census,color...",https://data.colorado.gov/d/qx2d-46a5,https://data.colorado.gov/resource/qx2d-46a5.json,04/08/2015 09:08:23 PM,09/06/2023 11:02:54 AM,04/08/2015 09:08:23 PM,data.colorado.gov,False,1736.0,110.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,The American Community Survey (ACS) is an ongo...,NaN,https://www.census.gov/geo/maps-data/,None,Static,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census core based statistical area demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
387,khe9-7d2c,Census Zip Codes SF1 in Colorado 2000,Census Data is collected every 10 years by mai...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"bic,census,colorado,commute,decennial,demograp...",https://data.colorado.gov/d/khe9-7d2c,https://data.colorado.gov/resource/khe9-7d2c.json,01/29/2015 04:24:24 PM,09/06/2023 11:02:36 AM,01/29/2015 04:24:24 PM,data.colorado.gov,False,1607.0,198.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://www.census.gov/geo/maps-data/,None,Static,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decennial census zop codes demographics from s...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
521,v56b-yh3u,Census Core Based Statistical Area in Colorado...,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"acs,american community survey,bic,census,color...",https://data.colorado.gov/d/v56b-yh3u,https://data.colorado.gov/resource/v56b-yh3u.json,04/08/2015 09:12:07 PM,09/06/2023 11:02:51 AM,04/08/2015 09:12:07 PM,data.colorado.gov,False,1549.0,126.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,The American Community Survey (ACS) is an ongo...,NaN,https://www.census.gov/geo/maps-data/,None,Static,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census core based statistical area demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
546,mxmm-svgz,Census County Subdivisions in Colorado 2012,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"acs,american community survey,bic,census,color...",https://data.colorado.gov/d/mxmm-svgz,https://data.colorado.gov/resource/mxmm-svgz.json,04/06/2015 11:12:27 PM,09/06/2023 11:02:47 AM,04/06/2015 11:12:27 PM,data.colorado.gov,False,1428.0,116.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,The American Community Survey (ACS) is an ongo...,NaN,https://demography.dola.colorado.gov/gis/gis-d...,None,Static,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census county subdivision demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
553,f3th-4ste,Census County Subdivisions SF3 in Colorado 2000,Census Data is collected every 10 years by mai...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"bic,census,colorado,commute,counties,decennial...",https://data.colorado.gov/d/f3th-4ste,https://data.colorado.gov/resource/f3th-4ste.json,01/29/2015 03:53:50 PM,09/06/2023 11:02:39 AM,01/29/2015 03:53:50 PM,data.colorado.gov,False,1464.0,104.0,NaN,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://www.census.gov/geo/maps-data/,None,Static,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Decennial census county subdivision demographi...,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
554,9gri-r239,Census Block Groups in Colorado 2013,American Community Survey Census data includes...,Colorado Information Marketplace,8cet-tw9x,published,public,approved,official,map,Demographics,"acs,american community survey,bic,census,color...",https://data.colorado.gov/d/9gri-r239,https://data.colorado.gov/resource/9gri-r239.json,03/09/2017 11:06:27 PM,09/06/2023 11:03:18 AM,04/01/2018 12:50:06 PM,data.colorado.gov,False,1253.0,96.0,Census Block Group,NaN,NaN,NaN,Public Domain,DOLA,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,State,Vector polygon,DOLA - Department of Local Affairs,NaN,NaN,NaN,"NOTE: To maintain source projection, select “E...",NaN,WGS84,NaN,NaN,Surveys,NaN,NaN,NaN,NaN,The 2000 census marked the last year that the ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Static,Census Data is collected every 10 years by mai...,NaN,https://demography.dola.colorado.gov/,None,Static,NaN,NaN,Census data is reliable as within the constrai...,NaN,NAD83/GCS_North_American_1988,NaN,NaN,NaN,https://data.colorado.gov/Demographics/Census-...,NaN,NaN,NaN,https://www.colorado.gov/pacific/dola,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,Census block group demographics,NaN,NaN,NaN,NaN,NaN,None,NaN,NaN,NaN,NaN,NaN,NaN,2013,TIGER line files

In [31]:
import streamlit as st
from st_aggrid import AgGrid, GridUpdateMode
from st_aggrid.grid_options_builder import GridOptionsBuilder

In [32]:
df = dfCIMMapCen
gd = GridOptionsBuilder.from_dataframe(df)
gd.configure_selection(selection_mode='multiple', use_checkbox=True)
gridoptions = gd.build()

grid_table = AgGrid(df, height=250, gridOptions=gridoptions,
                    update_mode=GridUpdateMode.SELECTION_CHANGED)

st.write('## Selected')
selected_row = grid_table["selected_rows"]
st.dataframe(selected_row)

2023-09-20 09:58:14.340
  Warning: to view this Streamlit app on a browser, run it with the following
  command:

    streamlit run /home/joe/anaconda3/envs/bic/lib/python3.6/site-packages/ipykernel_launcher.py [ARGUMENTS]

DeltaGenerator(_root_container=0, _provided_cursor=None, _parent=None, _block_type=None, _form_data=None)